static const char entitiesStringpool[] =
    "smidnprecUbreveboxplusgtquestquesteqandslopecirmidsstarfuuarrororfrac23Sfrointltlarrrarrlpascrcempty"
    "vhopfUnderBracketngeqqtcytimesbarquaternionscapbrcupPfrrdquorlBarrMediumSpacerangminusduEcaroncedigt"
    "rarrGreaterEqualKscrenspZacutehellipiffspadesnleqqsubsetneqqxicsupDopfnvltrieLeftTeeArrowCscrRBarrca"
    "pcapdashRightTeeVectorThereforeJscrRightTriangleEqualeqcircnvlttimesdcirxlarryumlncymnplusCHcyodblac"
    "barveeuparrowREGdArrnLeftrightarrowplusermoustVerticalSeparatorbigcapsacutegEucirSHcyLessSlantEqualU"
    "nderParenthesiscupsIukcyRightTriangleisinEnaturalscuescsimplussqufbcymapstoupdrcropboxDLtrpeziumsup3"
    "awintgesdotogfrRightTeeVfrmuograveImacrJopfiacutelessdotefrnlsimsimenleftrightarrowsubseteqqquatints"
    "olprertrifhyphenIntersectionScydbkarowgElsuccapproxKopfUpdownarrowOmacrapeexclpluscirsimrarrstarfCol"
    "onDoubleLeftRightArrownvDashAgravcopftildenltNestedLessLessamalglatyacutlbbrkrtimesYacutgtrlesspsivD"
    "ashurcropQopfdrcornrrarrboxhDpimcysqsupseteqnedotvdashDcyboxuLcopysrLeftTeeVectorcularrrightthreetim"
    "esLshBarwedackjcyxuplusleftarrowtaileqslantgtrnparttrianglerightCloseCurlyQuoteDownLeftTeeVectorOcir"
    "cOpenCurlyQuoteqfrcsupeolineuumlNotLeftTriangleBarKappaneacuteangmsdaanivflligupharpoonrightvopfRigh"
    "tCeilingZfrcurarrmrxdotplusKJcysubsublgBernoullisSacutesubmultbnotcoloneqsupneycircthetauharlstrnsnG"
    "gflatlneqqCupCapgimelprecneqqitildeprurelvarproptoblacktriangleleftprofsurfelsdotlesgOslasscnEnhparf"
    "scrrtrilrtrirightrightarrowsBfrgeldHarrealshyIacutetwoheadleftarrowbopfplusZopfEcircdzcyprapOumhslas"
    "hEcyffrImpliesIogonenglsimeaposctdotNotSucceedsTildeCcircDoubleUpDownArrowDoubleLongLeftRightArrowlt"
    "questsubsetneqnLtslarrzscrldshrarrplSquareSupersetOverBarrsquorrfrSmallCircletwoheadrightarrowycysme"
    "parslsquarenumiumllnEnparslprecucyumlzigrarrrnmidClockwiseContourIntegralnotindototilddtrifIotalaquo"
    "notrdquoLeftVectorBarDoubleLeftArrowNotSubsetEqualncaronprodtelrecimaglineDZcycwintnearrowagraveurtr"
    "iepsivangrtangddotsequtildeAmacrfrac34LeftUpDownVectorOverParenthesisperiodDoubleLeftTeeNtildlthreei"
    "infincheckmarkOgravpertenkNotTildeEqualboxboxveebarzeetrfasympTabNotDoubleVerticalBarUgraveblk12csub"
    "GammadoteqMapNotHumpEqualcuwedthickapproxboxdllongmapstolsolbarOacuteprecequpuparrowsfrac13suphsubra"
    "rrbJcircequivDDorigofNotTildeTildecupcupLongRightArrowlmoustoscrrbrackProductbbrktbrkheartsuitwreath"
    "anddtfrMfrcfrQUOTbethawconintnGtvLangudblacbbrkgammadrarrRightAngleBracketgbreveHatsimnevarkappadiam"
    "ondEacuteDownarrowPartialDRightFloordeXscrsigmafScnaturnsupseteqnwarrowSquareIntersectionGreaterTild"
    "ecurlyveedzigrarrparparbetardldharubrcyglEleftharpoonupdfishtpoundosolnapEpmnlessEacutmacrLJcyldrdha"
    "rwedbarprnEOdblacincaresupsetneqnsccuengesbernoudtdotforkDotEqualeerationalsscpolintsqcapvcyroanglEg"
    "bigveeNcaronlgEgenbspexponentialespadesuitPrecedesEqualgnsimangmsdaeiiotaxscrtcarondaggerDJcyhksearo"
    "wvpropbetweengeqENGquestdoublebarwedgelsimropfnwnearboxDltriangleiczdotbcongxfrwfrnvrArrapidLeftarro"
    "wnrArrDoubleLongLeftArrowtrieDoubleUpArrowqintbackconggsimboxuRfrac45uplusCircleMinusCenterDotncupno"
    "tnivcprEmultimapplanckhurcornergneqharrwocyIgravevBarvfrownitbdquosmtecirscirpreparpoundeltaraquxrar"
    "rsubsupnvlenapscOrcongdotntrianglerightsmtesDoubleRightTeentriangleleftequarrwedgeGammadntrianglelef"
    "tlvnEemsp14ohbarNewLineUringnvgtorarrIscrNotRightTriangleBarglaDfrsrarrNotNestedLessLessdividelessgt"
    "rOcirsmtNotGreaterLessboxulpopflAarrshLcyegsodivLeftDownTeeVectorgtlParlegnvrtrieaeligequalsnhArrMuo"
    "cirocirdcaronringfrac38gsimegtreqqlessdharllotimesrarrtlTopfNotSucceedsEqualUpsilonratailleqslantcir"
    "esupsupsupsuptoeaxutriDownArrowUpArrowAlphalparmhorobrkOfracdBackslashnpolintFcyeqslantlessRightUpVe"
    "ctorBarscircnotinvcLeftFlooriiiintnsqsubedtriCcaronDownLeftRightVectornleqnlebulletDoubleRightArrowc"
    "udarrrhorbarlbrksldparsimPirparLeftDownVectorparallelprnapsup2backsimswarrowapproxeqnsqsupedivonxDow"
    "nRightTeeVectordivlmidotorrotimesAumlvarsupsetneqSquarenleftarrowNotCongruentsubrarrrtriltrirlharsub"
    "xveeccedilcirceqlbarrprnsimthorotimesrdcaSqrtKfrnlArrlscrmapstodownimageuopfVeeelintersboxUlvartheta"
    "LarrplussimtriplussectogonZetaLtNscrShortLeftArrowbumpeqandvucircnLeftarrowxmapUpsiLopfethgesdotolns"
    "imezhcynotinESigmaAfrlceilPscrsupsubjcyNotLessGreaterleftrightharpoonsgcircrshracutebottomrmoustache"
    "StarxodotlnsimrAarrsubneufishtNfrutrifArinLstroketaparaLongLeftArrowdemptyvboxdLdownarrowangmsdabnsu"
    "bsetproflinefrac1frac1LessEqualGreatershortparallelLeftDownVectorBarsharpccaronlcaronchiUdblactstrok"
    "dstroknleqslantEquilibriumsuccneqqastmapstonoisindotsimlEcommaintedotegraveTcedilconintdharrKHcylowa"
    "stnLlccedisupsupcenterdotdownharpoonlefthamiltRacuteboxhrightharpoonupvarrholarrfsesimmldrleftleftar"
    "rowstshcyAumradicUpArrowBarLowerLeftArrowqopfCcedilIumReverseElementForAllbigcuptopbotcirclearrowrig"
    "htoSprofalarcheckrightsquigarrowltxcupLleftarrowpointintgjcyUumseArrblocklooparrowrightrightharpoond"
    "ownmicryucylcedilprecnapproxsolbsqsubseteqexpectationjsercysimgEupharpoonleftMopfsmileNotEqualTildeI"
    "cyrcySucceedsSlantEqualnotninshortmidCirclePlusldquorMcyYUcynotinorslopesuccnsimugravecompdotdsolpri"
    "megtdotPrimeufrnbumpOumlOverBracegvnEofcirDiacriticalDoubleAcuteUbrcyGreaterGreaterllarrordervarsups"
    "etneqqvltribigodotcapssupedotominusHilbertSpaceandsigmaogtolarrfrac35Psinearhknrarrwsdotbdienumeroln"
    "approxnjcyubreveLeftCeilinglatesboxurscetimesbHfrinfinleqblacktrianglexhArrcopsubEtriangledownyscrat"
    "ildordfThetaSquareSubsetEqualccapsnesearheartsdlcornplustwoRhorarrsimtintIacutisinsvfrac14lhblkeuroR"
    "ightUpDownVectorangrtvbdcscrlErarrcPcyTcyrsqbPlusMinusNotSupersetWscrLcedilProportiondopfNotLeftTria"
    "ngleEqualescrtosaInvisibleCommancongdotsfriecybigsqcupbscrRightArrowfemaleomegaotimesasrealpartUacut"
    "nVdashhookrightarrowsupsimcirENJcyeopfiotawrcircleddashddrhovcudarrlrlarrsimeqDownRightVectorbackpri"
    "melowbaroplustimeYAcyjcircVertReverseUpEquilibriumRarrtlintprodNotGreaterSlantEqualcaronlesdotorYuml"
    "RcediltraderdshboxvlbracephoneumacrtimesgeslesncedilequestlambdaFilledVerySmallSquarelesccLeftUpTeeV"
    "ectormodelsPrYcynVDashthetasymlangvfrboxUrgeslNcyrfloorangmsdafnisupdownarrowrharunsubseteqdarrigrav"
    "eZHcyiquestnlEyeeacutruluhardalethkappaUpEquilibriumWopflfrOopfRightDownTeeVectorintercalhomthtSubse"
    "tEqualarinLmidotfallingdotseqscaronldquowopfCircleDotGdiamondsuitfnofnsubseteqqSOFTcynexistsDDangzar"
    "rbsemilnapGfrbsimenotnivbplusdoccupsmstposkopfdoteqdotCrossbsolhsubnsupsetRightVectorBarUnderBraceca"
    "pNotGreaterEqualboxULsucccurlyeqLeftAngleBracketdscrleftharpoondownrectsqcuperarrprecapproxecircabre"
    "veNotGreatermalteserHarRightUpTeeVectorThinSpaceLTlshtritimeSquareUnionemsp13apacirfrac25wcircgesccU"
    "pArrowDownArrowangrtvbrBarrrbrksldsetmnGreaterEqualLessthkapNestedGreaterGreaterQfrIJligtopNotLeftTr"
    "ianglecomplementNueumlyumDoubleDotomidIopfnangrarrapscnsimphivcurvearrowleftsubnEmumapGcedilcwconint"
    "shchcyleqqoeligGcircacirclfishtapproxtscyOmicroncapandstraightepsilonPoincareplaneboxHzopfnisduacutL"
    "caroncrarrleftrightarrowscomplexesalephAacutloplusIcirclneqbNotbothairsprbarrnearrConintntildeNegati"
    "veThickSpaceharryennotinvbswArrpermilmscrBopfLeftrightarrowScaronVscrdlcropQscrintcalTaunacuteRevers"
    "eEquilibriumColonealefsymtwixtHumpEqualRightVectorifrjfrblk14supeboxDReastersup1lmoustacheoumsecngeS"
    "hortRightArrowiscrGtminustopfYopfgnapsimgOverBracketloangpitchforkordordordUacutecopybepsiverbarvart"
    "rianglerightbarwedsumBarvcrossnwArrthetavffligolcircupbrcapnesimVerticalBarboxVrltrieRfrnuUscrexiste"
    "mptysetfltnszcyhalfrfishtUcycaretnbsrbbrkhoarrBumpeqAgraveiukcynequivGdotlongleftrightarrowuArrrisin"
    "gdotseqhardcyltrisccuesqcupsaumlEcirNotPrecedesrsquoscEcurreminusdorvAopfoopfinodotdjcyAcirEogonbump"
    "olcrossvnsupsubevarromicronNotEqualNotRightTriangleNotExistsDaggerPrecedesTildelesdotprimesTfrlarrMi"
    "nusPlusangmsdachybullScircimagpartNtildelelongrightarrowrightarroweumSscrzetanumsplarrbeplusblacktri"
    "angledownetsucceqellboxvRcencurlywedgegtiiupsilrharpivNcedilsoftcyvBarsungNotElementCounterClockwise"
    "ContourIntegralRightUpVectorNotGreaterTildeCfrlrmsubplusLessFullEqualBetanvsimlanglevnsubncongrArrLe"
    "ftUpVectorxnisHscrrationaposNotTildeFullEqualYIcyacycupdotLeftTriangleBarNotLessLessefDotnscepartamp"
    "khcyodashNotSucceedsSlantEqualkcedilCircleTimesTildeFullEqualvsubneMellintrfLambdaNotRightTriangleEq"
    "ualboxVmaltegsdotUarrociroltkgreennscLeftRightArrowasympeqCdotOgraveDownTeengeqslantstarGreaterLessN"
    "opfsqsubmiddotNotTildeLessGreateremacrforallLowerRightArrowShortDownArrowUcircboxUReDDotlarrlpnvlArr"
    "AringsupsetcircledSgneDownLeftVectorBarVcybprimeXfrJcyoacutETBcyNotCupCapintegersOtimesblacktriangle"
    "rightplusaciriiintFilledSmallSquaremidcirthinspEfrLongleftarrownsimeqlatailxoplusZeroWidthSpacefpart"
    "inttbrkDownTeeArrowsdoteOcygNotReverseElementGcyhcirccommatemptyracesimdotloparisinnrarrsdotsigmavRi"
    "ghtArrowLeftArrowplusbVdashSopfAbreveboxdrLeftDoubleBracketImfrac15lateltcirphigapmarkerrarrbfsVeryT"
    "hinSpacentildcapcupfrac56rbracercedilvarsubsetneqqboxHUdblacCupdeglrhardangenablaNegativeVeryThinSpa"
    "ceXopforderofEsimaelimicroroparrhardsqcapsoacutesimlTSHcycularrpkcyScedilTRADEVDashbacksimeqddaggerr"
    "lmDownRightVectorBarHorizontalLinelbrkslunpreceqzacuteRightTriangleBarbkarowcircledcircDiacriticalDo"
    "tkscrPrecedesSuperDotecolonPopfltimesUnderBargammaTripleDotthksimjscrzwnjRightarrowDotltcciocyyacyeg"
    "COPharrcirmidastDiacriticalTildeExistsbnequivNotVerticalBarsearrpuncsprealinellcornerxlArrdotminusof"
    "rangmsdagdrbkarowtrisbAEliIdotngtrRuleDelayedlbrackranglellhardSupersetforkvgestrianglelefteqnprprec"
    "simwscricircsupENotNestedGreaterGreaterboxDrdownharpoonrightsqsubsetyfrAtildSubrbrkslulaemptyvngEnsc"
    "rGscrRightArrowBarcedilUnioncirclearrowleftGTVerbarangmsdahnexistcapdotsearhktriminusAogonbigtriangl"
    "edownlopfDstrokpropvrtrinotnivaraemptyvsubdotEgravelarrsimProportionalloarrlozfbigwedgelsimgOtildbox"
    "VRvertparslbackepsilonEscrafrbecausechcyApplyFunctionlrarrsparlozengeleftthreetimesnsucceqAssignblk3"
    "4EqualTildeOmegadowndownarrowsjopfplusdushcyangstnvapCongruentutdotgggnRightarrowoperplstroknfrduarr"
    "NotPrecedesEqualdiamecarongsimlleftrightsquigarrowNonBreakingSpacelfloorrharulnpredotsquareFopfscyJs"
    "ercyiogonnsimLongrightarrowfjlignsupseteqqnLtvccircNotGreaterFullEqualUmacrdollarnvdashSquareSuperse"
    "tEqualNotPrecedesSlantEqualLessLessovbarsubsimigravldcaJukcyChiRshsubseteqboxVheqsimgraveraquoyacute"
    "GgimathNegativeThinSpacecolonefrac18rarrfsGreaterFullEqualLessTildeRrightarrowscapIcirugravbigoplusE"
    "quallparltDownArrowBarzfroslashRoundImpliesSHCHcyVdashlboxvrSquareSubsetsqsupGJcyNotSubsetntlgEmptyS"
    "mallSquareesdotprcuegtcirupsihgtrsimprecnsimeDotsupdotcurarrsfrownquohkswarowuumReldrusharIntnbumpea"
    "tildebiguplusSucceedsEqualoumlEdotboxhublacksquareicypfrrealssupsetneqqgtrapproxvsubnEiexcthere4equi"
    "vDoubleVerticalBarrightarrowtailNotSucceedstridotzwjcongUpArrowDcaronUogonbumpeiopfrtrieFfrbullclubs"
    "uithookleftarrowlooparrowleftthicksimTHORNfiligutriSupsetboxvHdividsubsetLeftArrowRightArrowltrifnap"
    "proxddarrntrianglerighteqalphaxdtricurlyeqsuccaringgnEUpperRightArrowaogoneqvparslleftarrowlharubnen"
    "ltriDiacriticalAcutengeqsuphsolTScysbquosupseteqRcynrtrieRscrUumlnrtrivarnothingDoubleLongRightArrow"
    "planckHopfhstrokLeftVectorggkappavAMOacutxharrUfrkfrrpargtvartriangleleftshortmidLeftTeeLeftRightVec"
    "torNacuteEgravrceilIEcybigtriangleupltrPareparslregRightDoubleBracketvscrTHORelgneqqgeqslantvsupnENo"
    "tSquareSubsetUtildeZscrluruharglssetmnHARDcyAscrbsolnprcuepercntsqsupsetuscrboxdRcircledastNotSupers"
    "etEqualvarsubsetneqresupplusNotnldrWedgeacutfrac3rscrsetminussupseteqqaacutengsimrangeYscrlltriquots"
    "mallsetminusBscrgdotlesdotoboxHuvellipimacriprodJfreogonlAtailgljagravanglebrvbarqprimeCconintgtrdot"
    "rAtailHcircLaplacetrfcueprImaginaryIacirnaturalnparallelomacrumHumpDownHumptopforkmacElementboxtimes"
    "UcirgacuteprsimlesseqgtrDiamondEmptyVerySmallSquareuringEopfgvertneqqisinvNegativeMediumSpaceblacklo"
    "zengeblankrarrhkbsimGreaterSlantEqualandandscsimmcommavarphilaquangsphyicyrcaronUpDownArrowDownBreve"
    "compfnTildeTildeDarrboxVleqcolonncapdcycircledRCopfGbreveDifferentialDlarrtlurcornKcedilxwedgeHacekL"
    "eftTriangletargetcircuogonwedgeqAacuteCayleysboxHDhscrlcubgnapproxlharulimofTscrlesseqqgtrNotSquareS"
    "upersetEqualSucceedsLfrbfrnotinvafrac78middoicirnlesLeftArrowBarssmileecyswarhknsubEDoubleDownArrowr"
    "opluslangdDotDotljcyplusmUpperLeftArrownsubvArroslasotildebsolbsmashpboxminusrightleftarrowsfrac16cu"
    "rvearrowrightfrac58simnltrieCapnsupEcacuteSucceedsTildeEummeasuredanglexrArreacutecdotboxvLDoubleCon"
    "tourIntegralDscrWfrcentiquesxotimenrarrcsubedotVopfvarepsilonsuplarrnshortparallelwpZdotclubsgtreqle"
    "sspcyNotSquareSupersetRightDownVectorBarndashEtanmidodotCcedilcyqscrepsivlbrkeboxVHngtnharrvarpiEuml"
    "RcaronlHarsqsupeDiacriticalGravecupcapulcornFscrNotLessdigammapreccurlyeqrarrwuwanglehArrsearrowOsla"
    "shdwangleiacutswarrNoBreakgtccamacrstraightphiExponentialEMscrdashvneArrLeftTriangleEqualcolonlrcorn"
    "errightleftharpoonsDashvsopfNotHumpDownHumpbarwedgeAtildeYcircdiamsREaopfNotGreaterGreaterbigstarscn"
    "aptauIumlIgravVvdashlesgesSumacEinnvgeboxhUmapxcapxopfyopfcurlyeqprecUarrIfrNotLessEqualthereforeUgr"
    "avVerticalTildeimpeduacuteOtildenvHarrulcropbrvbabumpESubsetZcyfcymfrCoproducttriangleleftboxvhcsube"
    "coprodInvisibleTimesinfintielozCacuteLongLeftRightArrowLongleftrightarrowfflligdivideontimesphmmatfr"
    "aslnrightarrownwarrDownArrowmlcpEpsilonItildeBreveveeHstrokgesdotlacutenvinfinnlarrsquarfPhielsnGtss"
    "crswnwarSuchThatintlarhkDelRarrocircapEgscrecirecirveeeqszligntglbigotimesdisinnparduharDownLeftVect"
    "orsextisinspscrxcircRightTeeArrowcuveelsquoruhblkVbarAEligOscrmDDotmidSupersetEqualKcyvsupneRightDow"
    "nVectorlarrbfssqsuberoarrijligudharbecausboxhdoastemptyvnsmidrcubscedilOpenCurlyDoubleQuoteUnionPlus"
    "zcaronnapidmalesupmultleslurdsharCedillaLllArremspETHultrilesssimlvertneqqtscrmptcedilTildeEqualrthr"
    "eeplankvuHarltdotfrac12lsquonopfoparfopfjukcylhardYacuteCapitalDifferentialDsupnErppolintaacutLscrwe"
    "ierpordmUopfLacuteszliIntegralcurrenlobrkYfrcylctyLeftUpVectorBaraumAcyangrtrbrkeNotLessSlantEqualla"
    "granmapstoleftiumamvzigzagbigcircUparrowtrianglerighteqtdotRopfdfrnspargeqqnsupTstroksemiupsilonCOPY"
    "boxVLodsoldPrecedesSlantEqualcirfnintjmaththornlarrhkmopfGopfgcyiexclbemptyvlongleftarrowrsaquoZcaro"
    "naflapuharrhbarmdashnsuccudarrboxHdFouriertrfLeftArrowThickSpacebowtielneUpTeeArrowogravleftrightarr"
    "owulcornerXiangmsdadDDotrahdllminusbperpohmEmacrWcirctriangleqlessapproxsupdsubQUOherconnsubetopcira"
    "ngmsdcuporlsqbxsqcupVerticalLineCloseCurlyDoubleQuoteDeltagopfShortUpArrowplusmnnisqutprimedscyffili"
    "gseswarAMPvarsigmaTildelarrplContourIntegralnsuperangdAcircUpTeeaprhobreveproptoBecauseegravRangboxv"
    "lDScysuccAndTcaronNotLessTildecupOEligepsilonlsaquoIOcysuccsimhfrsuccnapproxNotSquareSubsetEqualLnwa"
    "rhkccupssm"
  ;

static const EntitiesEntry entitiesEntries[] = {
    {  4, 0,     0, {  0x2223,     0x0 } }, // smid
    {  5, 0,     4, {  0x2280,     0x0 } }, // nprec
    {  6, 1,     9, {   0x16c,     0x0 } }, // Ubreve
    {  7, 0,    15, {  0x229e,     0x0 } }, // boxplus
    {  7, 0,    22, {  0x2a7c,     0x0 } }, // gtquest
    {  7, 0,    29, {  0x225f,     0x0 } }, // questeq
    {  8, 0,    36, {  0x2a58,     0x0 } }, // andslope
    {  6, 0,    44, {  0x2aef,     0x0 } }, // cirmid
    {  6, 1,    50, {  0x22c6,     0x0 } }, // sstarf
    {  5, 0,    56, {  0x21c8,     0x0 } }, // uuarr
    {  4, 0,    61, {  0x2a56,     0x0 } }, // oror
    {  6, 0,    65, {  0x2154,     0x0 } }, // frac23
    {  3, 1,    71, { 0x1d516,     0x0 } }, // Sfr
    {  4, 0,    74, {  0x222e,     0x0 } }, // oint
    {  6, 0,    78, {  0x2976,     0x0 } }, // ltlarr
    {  6, 0,    84, {  0x21ac,     0x0 } }, // rarrlp
    {  4, 0,    90, { 0x1d4b6,     0x0 } }, // ascr
    {  7, 0,    94, {  0x29b2,     0x0 } }, // cemptyv
    {  4, 0,   101, { 0x1d559,     0x0 } }, // hopf
    { 12, 1,   105, {  0x23b5,     0x0 } }, // UnderBracket
    {  5, 0,   117, {  0x2267,   0x338 } }, // ngeqq
    {  3, 0,   122, {   0x442,     0x0 } }, // tcy
    {  8, 0,   125, {  0x2a31,     0x0 } }, // timesbar
    { 11, 0,   133, {  0x210d,     0x0 } }, // quaternions
    {  8, 0,   144, {  0x2a49,     0x0 } }, // capbrcup
    {  3, 0,   152, { 0x1d513,     0x0 } }, // Pfr
    {  6, 0,   155, {  0x201d,     0x0 } }, // rdquor
    {  5, 0,   161, {  0x290e,     0x0 } }, // lBarr
    { 11, 1,   166, {  0x205f,     0x0 } }, // MediumSpace
    {  4, 0,   177, {  0x27e9,     0x0 } }, // rang
    {  7, 0,   181, {  0x2a2a,     0x0 } }, // minusdu
    {  6, 1,   188, {   0x11a,     0x0 } }, // Ecaron
    {  4, 1,   194, {    0xb8,     0x0 } }, // cedi
    {  6, 0,   198, {  0x2978,     0x0 } }, // gtrarr
    { 12, 1,   204, {  0x2265,     0x0 } }, // GreaterEqual
    {  4, 0,   216, { 0x1d4a6,     0x0 } }, // Kscr
    {  4, 0,   220, {  0x2002,     0x0 } }, // ensp
    {  6, 1,   224, {   0x179,     0x0 } }, // Zacute
    {  6, 1,   230, {  0x2026,     0x0 } }, // hellip
    {  3, 1,   236, {  0x21d4,     0x0 } }, // iff
    {  6, 0,   239, {  0x2660,     0x0 } }, // spades
    {  5, 1,   245, {  0x2266,   0x338 } }, // nleqq
    { 10, 1,   250, {  0x2acb,     0x0 } }, // subsetneqq
    {  2, 0,   260, {   0x3be,     0x0 } }, // xi
    {  4, 0,   262, {  0x2ad0,     0x0 } }, // csup
    {  4, 1,   266, { 0x1d53b,     0x0 } }, // Dopf
    {  7, 0,   270, {  0x22b4,  0x20d2 } }, // nvltrie
    { 12, 0,   277, {  0x21a4,     0x0 } }, // LeftTeeArrow
    {  4, 1,   289, { 0x1d49e,     0x0 } }, // Cscr
    {  5, 1,   293, {  0x2910,     0x0 } }, // RBarr
    {  6, 1,   298, {  0x2a4b,     0x0 } }, // capcap
    {  4, 0,   304, {  0x2010,     0x0 } }, // dash
    { 14, 1,   308, {  0x295b,     0x0 } }, // RightTeeVector
    {  9, 0,   322, {  0x2234,     0x0 } }, // Therefore
    {  4, 0,   331, { 0x1d4a5,     0x0 } }, // Jscr
    { 18, 1,   335, {  0x22b5,     0x0 } }, // RightTriangleEqual
    {  6, 1,   353, {  0x2256,     0x0 } }, // eqcirc
    {  4, 0,   359, {    0x3c,  0x20d2 } }, // nvlt
    {  6, 0,   363, {  0x2a30,     0x0 } }, // timesd
    {  3, 1,   369, {  0x25cb,     0x0 } }, // cir
    {  5, 1,   372, {  0x27f5,     0x0 } }, // xlarr
    {  4, 0,   377, {    0xff,     0x0 } }, // yuml
    {  3, 0,   381, {   0x43d,     0x0 } }, // ncy
    {  6, 0,   384, {  0x2213,     0x0 } }, // mnplus
    {  4, 0,   390, {   0x427,     0x0 } }, // CHcy
    {  6, 0,   394, {   0x151,     0x0 } }, // odblac
    {  6, 1,   400, {  0x22bd,     0x0 } }, // barvee
    {  7, 0,   406, {  0x2191,     0x0 } }, // uparrow
    {  3, 0,   413, {    0xae,     0x0 } }, // REG
    {  4, 0,   416, {  0x21d3,     0x0 } }, // dArr
    { 15, 1,   420, {  0x21ce,     0x0 } }, // nLeftrightarrow
    {  5, 0,   435, {  0x2a72,     0x0 } }, // pluse
    {  6, 0,   440, {  0x23b1,     0x0 } }, // rmoust
    { 17, 1,   446, {  0x2758,     0x0 } }, // VerticalSeparator
    {  6, 1,   463, {  0x22c2,     0x0 } }, // bigcap
    {  6, 0,   469, {   0x15b,     0x0 } }, // sacute
    {  2, 0,   475, {  0x2267,     0x0 } }, // gE
    {  4, 0,   477, {    0xfb,     0x0 } }, // ucir
    {  4, 0,   481, {   0x428,     0x0 } }, // SHcy
    { 14, 1,   485, {  0x2a7d,     0x0 } }, // LessSlantEqual
    { 16, 1,   499, {  0x23dd,     0x0 } }, // UnderParenthesis
    {  4, 0,   515, {  0x222a,  0xfe00 } }, // cups
    {  5, 1,   519, {   0x406,     0x0 } }, // Iukcy
    { 13, 0,   524, {  0x22b3,     0x0 } }, // RightTriangle
    {  5, 0,   537, {  0x22f9,     0x0 } }, // isinE
    {  8, 0,   542, {  0x2115,     0x0 } }, // naturals
    {  5, 1,   550, {  0x22df,     0x0 } }, // cuesc
    {  7, 0,   555, {  0x2a24,     0x0 } }, // simplus
    {  4, 0,   562, {  0x25aa,     0x0 } }, // squf
    {  3, 1,   566, {   0x431,     0x0 } }, // bcy
    {  8, 0,   569, {  0x21a5,     0x0 } }, // mapstoup
    {  6, 0,   577, {  0x230c,     0x0 } }, // drcrop
    {  5, 1,   583, {  0x2557,     0x0 } }, // boxDL
    {  8, 0,   588, {  0x23e2,     0x0 } }, // trpezium
    {  4, 0,   596, {    0xb3,     0x0 } }, // sup3
    {  5, 1,   600, {  0x2a11,     0x0 } }, // awint
    {  7, 1,   605, {  0x2a82,     0x0 } }, // gesdoto
    {  3, 0,   612, { 0x1d524,     0x0 } }, // gfr
    {  8, 1,   615, {  0x22a2,     0x0 } }, // RightTee
    {  3, 1,   623, { 0x1d519,     0x0 } }, // Vfr
    {  2, 1,   626, {   0x3bc,     0x0 } }, // mu
    {  6, 0,   628, {    0xf2,     0x0 } }, // ograve
    {  5, 1,   634, {   0x12a,     0x0 } }, // Imacr
    {  4, 0,   639, { 0x1d541,     0x0 } }, // Jopf
    {  6, 1,   643, {    0xed,     0x0 } }, // iacute
    {  7, 0,   649, {  0x22d6,     0x0 } }, // lessdot
    {  3, 0,   656, { 0x1d522,     0x0 } }, // efr
    {  5, 0,   659, {  0x2274,     0x0 } }, // nlsim
    {  4, 0,   664, {  0x2243,     0x0 } }, // sime
    { 15, 1,   668, {  0x21ae,     0x0 } }, // nleftrightarrow
    {  9, 0,   683, {  0x2ac5,     0x0 } }, // subseteqq
    {  7, 0,   692, {  0x2a16,     0x0 } }, // quatint
    {  3, 0,   699, {    0x2f,     0x0 } }, // sol
    {  3, 0,   702, {  0x2aaf,     0x0 } }, // pre
    {  5, 0,   705, {  0x25b8,     0x0 } }, // rtrif
    {  6, 0,   710, {  0x2010,     0x0 } }, // hyphen
    { 12, 1,   716, {  0x22c2,     0x0 } }, // Intersection
    {  3, 1,   728, {   0x421,     0x0 } }, // Scy
    {  7, 0,   731, {  0x290f,     0x0 } }, // dbkarow
    {  3, 0,   738, {  0x2a8c,     0x0 } }, // gEl
    { 10, 0,   741, {  0x2ab8,     0x0 } }, // succapprox
    {  4, 1,   751, { 0x1d542,     0x0 } }, // Kopf
    { 11, 0,   755, {  0x21d5,     0x0 } }, // Updownarrow
    {  5, 1,   766, {   0x14c,     0x0 } }, // Omacr
    {  3, 0,   771, {  0x224a,     0x0 } }, // ape
    {  4, 0,   774, {    0x21,     0x0 } }, // excl
    {  7, 1,   778, {  0x2a22,     0x0 } }, // pluscir
    {  7, 1,   785, {  0x2972,     0x0 } }, // simrarr
    {  5, 0,   792, {  0x2605,     0x0 } }, // starf
    {  5, 0,   797, {  0x2237,     0x0 } }, // Colon
    { 20, 1,   802, {  0x21d4,     0x0 } }, // DoubleLeftRightArrow
    {  6, 0,   822, {  0x22ad,     0x0 } }, // nvDash
    {  5, 0,   828, {    0xc0,     0x0 } }, // Agrav
    {  4, 1,   833, { 0x1d554,     0x0 } }, // copf
    {  5, 0,   837, {   0x2dc,     0x0 } }, // tilde
    {  3, 0,   842, {  0x226e,     0x0 } }, // nlt
    { 14, 1,   845, {  0x226a,     0x0 } }, // NestedLessLess
    {  5, 0,   859, {  0x2a3f,     0x0 } }, // amalg
    {  3, 1,   864, {  0x2aab,     0x0 } }, // lat
    {  5, 0,   867, {    0xfd,     0x0 } }, // yacut
    {  5, 1,   872, {  0x2772,     0x0 } }, // lbbrk
    {  6, 0,   877, {  0x22ca,     0x0 } }, // rtimes
    {  5, 1,   883, {    0xdd,     0x0 } }, // Yacut
    {  7, 1,   888, {  0x2277,     0x0 } }, // gtrless
    {  3, 0,   895, {   0x3c8,     0x0 } }, // psi
    {  5, 0,   898, {  0x22a8,     0x0 } }, // vDash
    {  6, 0,   903, {  0x230e,     0x0 } }, // urcrop
    {  4, 0,   909, {  0x211a,     0x0 } }, // Qopf
    {  6, 1,   913, {  0x231f,     0x0 } }, // drcorn
    {  5, 0,   919, {  0x21c9,     0x0 } }, // rrarr
    {  5, 0,   924, {  0x2565,     0x0 } }, // boxhD
    {  2, 0,   929, {   0x3c0,     0x0 } }, // pi
    {  3, 0,   931, {   0x43c,     0x0 } }, // mcy
    { 10, 0,   934, {  0x2292,     0x0 } }, // sqsupseteq
    {  5, 1,   944, {  0x2250,   0x338 } }, // nedot
    {  5, 0,   949, {  0x22a2,     0x0 } }, // vdash
    {  3, 0,   954, {   0x414,     0x0 } }, // Dcy
    {  5, 1,   957, {  0x255b,     0x0 } }, // boxuL
    {  6, 0,   962, {  0x2117,     0x0 } }, // copysr
    { 13, 1,   968, {  0x295a,     0x0 } }, // LeftTeeVector
    {  6, 0,   981, {  0x21b6,     0x0 } }, // cularr
    { 15, 0,   987, {  0x22cc,     0x0 } }, // rightthreetimes
    {  3, 0,  1002, {  0x21b0,     0x0 } }, // Lsh
    {  6, 1,  1005, {  0x2306,     0x0 } }, // Barwed
    {  2, 0,  1011, {  0x223e,     0x0 } }, // ac
    {  4, 1,  1013, {   0x45c,     0x0 } }, // kjcy
    {  6, 0,  1017, {  0x2a04,     0x0 } }, // xuplus
    { 13, 0,  1023, {  0x21a2,     0x0 } }, // leftarrowtail
    { 10, 0,  1036, {  0x2a96,     0x0 } }, // eqslantgtr
    {  5, 1,  1046, {  0x2202,   0x338 } }, // npart
    { 13, 0,  1051, {  0x25b9,     0x0 } }, // triangleright
    { 15, 1,  1064, {  0x2019,     0x0 } }, // CloseCurlyQuote
    { 17, 1,  1079, {  0x295e,     0x0 } }, // DownLeftTeeVector
    {  5, 1,  1096, {    0xd4,     0x0 } }, // Ocirc
    { 14, 1,  1101, {  0x2018,     0x0 } }, // OpenCurlyQuote
    {  3, 0,  1115, { 0x1d52e,     0x0 } }, // qfr
    {  5, 1,  1118, {  0x2ad2,     0x0 } }, // csupe
    {  5, 1,  1123, {  0x203e,     0x0 } }, // oline
    {  4, 0,  1128, {    0xfc,     0x0 } }, // uuml
    { 18, 0,  1132, {  0x29cf,   0x338 } }, // NotLeftTriangleBar
    {  5, 1,  1150, {   0x39a,     0x0 } }, // Kappa
    {  2, 0,  1155, {  0x2260,     0x0 } }, // ne
    {  5, 0,  1157, {    0xb4,     0x0 } }, // acute
    {  8, 1,  1162, {  0x29a8,     0x0 } }, // angmsdaa
    {  3, 0,  1170, {  0x220b,     0x0 } }, // niv
    {  5, 1,  1173, {  0xfb02,     0x0 } }, // fllig
    { 14, 1,  1178, {  0x21be,     0x0 } }, // upharpoonright
    {  4, 0,  1192, { 0x1d567,     0x0 } }, // vopf
    { 12, 1,  1196, {  0x2309,     0x0 } }, // RightCeiling
    {  3, 1,  1208, {  0x2128,     0x0 } }, // Zfr
    {  7, 1,  1211, {  0x293c,     0x0 } }, // curarrm
    {  2, 0,  1218, {  0x211e,     0x0 } }, // rx
    {  7, 0,  1220, {  0x2214,     0x0 } }, // dotplus
    {  4, 1,  1227, {   0x40c,     0x0 } }, // KJcy
    {  6, 0,  1231, {  0x2ad5,     0x0 } }, // subsub
    {  2, 0,  1237, {  0x2276,     0x0 } }, // lg
    { 10, 1,  1239, {  0x212c,     0x0 } }, // Bernoullis
    {  6, 1,  1249, {   0x15a,     0x0 } }, // Sacute
    {  7, 0,  1255, {  0x2ac1,     0x0 } }, // submult
    {  4, 1,  1262, {  0x2310,     0x0 } }, // bnot
    {  7, 0,  1266, {  0x2254,     0x0 } }, // coloneq
    {  5, 1,  1273, {  0x228b,     0x0 } }, // supne
    {  5, 0,  1278, {   0x177,     0x0 } }, // ycirc
    {  5, 0,  1283, {   0x3b8,     0x0 } }, // theta
    {  5, 0,  1288, {  0x21bf,     0x0 } }, // uharl
    {  5, 0,  1293, {    0xaf,     0x0 } }, // strns
    {  3, 0,  1298, {  0x22d9,   0x338 } }, // nGg
    {  4, 1,  1301, {  0x266d,     0x0 } }, // flat
    {  5, 0,  1305, {  0x2268,     0x0 } }, // lneqq
    {  6, 1,  1310, {  0x224d,     0x0 } }, // CupCap
    {  5, 0,  1316, {  0x2137,     0x0 } }, // gimel
    {  8, 0,  1321, {  0x2ab5,     0x0 } }, // precneqq
    {  6, 1,  1329, {   0x129,     0x0 } }, // itilde
    {  6, 0,  1335, {  0x22b0,     0x0 } }, // prurel
    {  9, 0,  1341, {  0x221d,     0x0 } }, // varpropto
    { 17, 1,  1350, {  0x25c2,     0x0 } }, // blacktriangleleft
    {  8, 0,  1367, {  0x2313,     0x0 } }, // profsurf
    {  6, 1,  1375, {  0x2a97,     0x0 } }, // elsdot
    {  4, 0,  1381, {  0x22da,  0xfe00 } }, // lesg
    {  5, 1,  1385, {    0xd8,     0x0 } }, // Oslas
    {  4, 0,  1390, {  0x2ab6,     0x0 } }, // scnE
    {  5, 0,  1394, {  0x2af2,     0x0 } }, // nhpar
    {  4, 1,  1399, { 0x1d4bb,     0x0 } }, // fscr
    {  4, 0,  1403, {  0x25b9,     0x0 } }, // rtri
    {  5, 0,  1407, {  0x22bf,     0x0 } }, // lrtri
    { 16, 0,  1412, {  0x21c9,     0x0 } }, // rightrightarrows
    {  3, 1,  1428, { 0x1d505,     0x0 } }, // Bfr
    {  3, 0,  1431, {  0x22db,     0x0 } }, // gel
    {  4, 1,  1434, {  0x2965,     0x0 } }, // dHar
    {  4, 1,  1438, {  0x211c,     0x0 } }, // real
    {  3, 0,  1442, {    0xad,     0x0 } }, // shy
    {  6, 0,  1445, {    0xcd,     0x0 } }, // Iacute
    { 16, 0,  1451, {  0x219e,     0x0 } }, // twoheadleftarrow
    {  4, 1,  1467, { 0x1d553,     0x0 } }, // bopf
    {  4, 0,  1471, {    0x2b,     0x0 } }, // plus
    {  4, 0,  1475, {  0x2124,     0x0 } }, // Zopf
    {  5, 1,  1479, {    0xca,     0x0 } }, // Ecirc
    {  4, 1,  1484, {   0x45f,     0x0 } }, // dzcy
    {  4, 0,  1488, {  0x2ab7,     0x0 } }, // prap
    {  3, 1,  1492, {    0xd6,     0x0 } }, // Oum
    {  6, 0,  1495, {  0x210f,     0x0 } }, // hslash
    {  3, 1,  1501, {   0x42d,     0x0 } }, // Ecy
    {  3, 0,  1504, { 0x1d523,     0x0 } }, // ffr
    {  7, 1,  1507, {  0x21d2,     0x0 } }, // Implies
    {  5, 1,  1514, {   0x12e,     0x0 } }, // Iogon
    {  3, 1,  1519, {   0x14b,     0x0 } }, // eng
    {  5, 0,  1522, {  0x2a8d,     0x0 } }, // lsime
    {  4, 1,  1527, {    0x27,     0x0 } }, // apos
    {  5, 0,  1531, {  0x22ef,     0x0 } }, // ctdot
    { 16, 0,  1536, {  0x227f,   0x338 } }, // NotSucceedsTilde
    {  5, 1,  1552, {   0x108,     0x0 } }, // Ccirc
    { 17, 0,  1557, {  0x21d5,     0x0 } }, // DoubleUpDownArrow
    { 24, 1,  1574, {  0x27fa,     0x0 } }, // DoubleLongLeftRightArrow
    {  7, 0,  1598, {  0x2a7b,     0x0 } }, // ltquest
    {  9, 0,  1605, {  0x228a,     0x0 } }, // subsetneq
    {  3, 1,  1614, {  0x226a,  0x20d2 } }, // nLt
    {  5, 0,  1617, {  0x2190,     0x0 } }, // slarr
    {  4, 0,  1622, { 0x1d4cf,     0x0 } }, // zscr
    {  4, 0,  1626, {  0x21b2,     0x0 } }, // ldsh
    {  6, 0,  1630, {  0x2945,     0x0 } }, // rarrpl
    { 14, 0,  1636, {  0x2290,     0x0 } }, // SquareSuperset
    {  7, 0,  1650, {  0x203e,     0x0 } }, // OverBar
    {  6, 0,  1657, {  0x2019,     0x0 } }, // rsquor
    {  3, 0,  1663, { 0x1d52f,     0x0 } }, // rfr
    { 11, 1,  1666, {  0x2218,     0x0 } }, // SmallCircle
    { 17, 0,  1677, {  0x21a0,     0x0 } }, // twoheadrightarrow
    {  3, 0,  1694, {   0x44b,     0x0 } }, // ycy
    {  8, 1,  1697, {  0x29e4,     0x0 } }, // smeparsl
    {  6, 0,  1705, {  0x25a1,     0x0 } }, // square
    {  3, 0,  1711, {    0x23,     0x0 } }, // num
    {  4, 1,  1714, {    0xef,     0x0 } }, // iuml
    {  3, 1,  1718, {  0x2268,     0x0 } }, // lnE
    {  6, 0,  1721, {  0x2afd,  0x20e5 } }, // nparsl
    {  4, 1,  1727, {  0x227a,     0x0 } }, // prec
    {  3, 0,  1731, {   0x443,     0x0 } }, // ucy
    {  3, 0,  1734, {    0xa8,     0x0 } }, // uml
    {  7, 0,  1737, {  0x21dd,     0x0 } }, // zigrarr
    {  5, 0,  1744, {  0x2aee,     0x0 } }, // rnmid
    { 24, 1,  1749, {  0x2232,     0x0 } }, // ClockwiseContourIntegral
    {  8, 0,  1773, {  0x22f5,   0x338 } }, // notindot
    {  5, 0,  1781, {    0xf5,     0x0 } }, // otild
    {  5, 0,  1786, {  0x25be,     0x0 } }, // dtrif
    {  4, 1,  1791, {   0x399,     0x0 } }, // Iota
    {  5, 1,  1795, {    0xab,     0x0 } }, // laquo
    {  3, 1,  1800, {    0xac,     0x0 } }, // not
    {  5, 0,  1803, {  0x201d,     0x0 } }, // rdquo
    { 13, 0,  1808, {  0x2952,     0x0 } }, // LeftVectorBar
    { 15, 1,  1821, {  0x21d0,     0x0 } }, // DoubleLeftArrow
    { 14, 0,  1836, {  0x2288,     0x0 } }, // NotSubsetEqual
    {  6, 0,  1850, {   0x148,     0x0 } }, // ncaron
    {  4, 0,  1856, {  0x220f,     0x0 } }, // prod
    {  6, 0,  1860, {  0x2315,     0x0 } }, // telrec
    {  8, 0,  1866, {  0x2110,     0x0 } }, // imagline
    {  4, 1,  1874, {   0x40f,     0x0 } }, // DZcy
    {  5, 0,  1878, {  0x2231,     0x0 } }, // cwint
    {  7, 0,  1883, {  0x2197,     0x0 } }, // nearrow
    {  6, 1,  1890, {    0xe0,     0x0 } }, // agrave
    {  5, 0,  1896, {  0x25f9,     0x0 } }, // urtri
    {  4, 1,  1901, {   0x3b5,     0x0 } }, // epsi
    {  6, 0,  1905, {  0x299c,     0x0 } }, // vangrt
    {  3, 1,  1911, {  0x2220,     0x0 } }, // ang
    {  7, 1,  1914, {  0x2a77,     0x0 } }, // ddotseq
    {  6, 0,  1921, {   0x169,     0x0 } }, // utilde
    {  5, 1,  1927, {   0x100,     0x0 } }, // Amacr
    {  6, 0,  1932, {    0xbe,     0x0 } }, // frac34
    { 16, 1,  1938, {  0x2951,     0x0 } }, // LeftUpDownVector
    { 15, 0,  1954, {  0x23dc,     0x0 } }, // OverParenthesis
    {  6, 0,  1969, {    0x2e,     0x0 } }, // period
    { 13, 0,  1975, {  0x2ae4,     0x0 } }, // DoubleLeftTee
    {  5, 0,  1988, {    0xd1,     0x0 } }, // Ntild
    {  6, 0,  1993, {  0x22cb,     0x0 } }, // lthree
    {  6, 0,  1999, {  0x29dc,     0x0 } }, // iinfin
    {  9, 0,  2005, {  0x2713,     0x0 } }, // checkmark
    {  5, 1,  2014, {    0xd2,     0x0 } }, // Ograv
    {  7, 0,  2019, {  0x2031,     0x0 } }, // pertenk
    { 13, 0,  2026, {  0x2244,     0x0 } }, // NotTildeEqual
    {  6, 0,  2039, {  0x29c9,     0x0 } }, // boxbox
    {  6, 1,  2045, {  0x22bb,     0x0 } }, // veebar
    {  6, 0,  2051, {  0x2128,     0x0 } }, // zeetrf
    {  5, 0,  2057, {  0x2248,     0x0 } }, // asymp
    {  3, 0,  2062, {     0x9,     0x0 } }, // Tab
    { 20, 1,  2065, {  0x2226,     0x0 } }, // NotDoubleVerticalBar
    {  6, 1,  2085, {    0xd9,     0x0 } }, // Ugrave
    {  5, 0,  2091, {  0x2592,     0x0 } }, // blk12
    {  4, 0,  2096, {  0x2acf,     0x0 } }, // csub
    {  5, 1,  2100, {   0x393,     0x0 } }, // Gamma
    {  5, 0,  2105, {  0x2250,     0x0 } }, // doteq
    {  3, 1,  2110, {  0x2905,     0x0 } }, // Map
    { 12, 1,  2113, {  0x224f,   0x338 } }, // NotHumpEqual
    {  5, 1,  2125, {  0x22cf,     0x0 } }, // cuwed
    { 11, 0,  2130, {  0x2248,     0x0 } }, // thickapprox
    {  5, 1,  2141, {  0x2510,     0x0 } }, // boxdl
    { 10, 1,  2146, {  0x27fc,     0x0 } }, // longmapsto
    {  1, 1,  2156, {    0x3c,     0x0 } }, // l
    {  6, 0,  2157, {  0x233f,     0x0 } }, // solbar
    {  6, 1,  2163, {    0xd3,     0x0 } }, // Oacute
    {  6, 0,  2169, {  0x2aaf,     0x0 } }, // preceq
    { 10, 0,  2175, {  0x21c8,     0x0 } }, // upuparrows
    {  6, 0,  2185, {  0x2153,     0x0 } }, // frac13
    {  7, 0,  2191, {  0x2ad7,     0x0 } }, // suphsub
    {  5, 0,  2198, {  0x21e5,     0x0 } }, // rarrb
    {  5, 1,  2203, {   0x134,     0x0 } }, // Jcirc
    {  7, 1,  2208, {  0x2a78,     0x0 } }, // equivDD
    {  6, 0,  2215, {  0x22b6,     0x0 } }, // origof
    { 13, 1,  2221, {  0x2249,     0x0 } }, // NotTildeTilde
    {  6, 0,  2234, {  0x2a4a,     0x0 } }, // cupcup
    { 14, 1,  2240, {  0x27f6,     0x0 } }, // LongRightArrow
    {  6, 0,  2254, {  0x23b0,     0x0 } }, // lmoust
    {  4, 1,  2260, {  0x2134,     0x0 } }, // oscr
    {  6, 0,  2264, {    0x5d,     0x0 } }, // rbrack
    {  7, 1,  2270, {  0x220f,     0x0 } }, // Product
    {  8, 0,  2277, {  0x23b6,     0x0 } }, // bbrktbrk
    {  9, 0,  2285, {  0x2665,     0x0 } }, // heartsuit
    {  6, 0,  2294, {  0x2240,     0x0 } }, // wreath
    {  4, 1,  2300, {  0x2a5c,     0x0 } }, // andd
    {  3, 0,  2304, { 0x1d531,     0x0 } }, // tfr
    {  3, 1,  2307, { 0x1d510,     0x0 } }, // Mfr
    {  3, 0,  2310, { 0x1d520,     0x0 } }, // cfr
    {  4, 0,  2313, {    0x22,     0x0 } }, // QUOT
    {  4, 0,  2317, {  0x2136,     0x0 } }, // beth
    {  8, 0,  2321, {  0x2233,     0x0 } }, // awconint
    {  4, 0,  2329, {  0x226b,   0x338 } }, // nGtv
    {  4, 1,  2333, {  0x27ea,     0x0 } }, // Lang
    {  6, 0,  2337, {   0x171,     0x0 } }, // udblac
    {  4, 1,  2343, {  0x23b5,     0x0 } }, // bbrk
    {  6, 1,  2347, {   0x3dd,     0x0 } }, // gammad
    {  4, 0,  2353, {  0x2192,     0x0 } }, // rarr
    { 17, 1,  2357, {  0x27e9,     0x0 } }, // RightAngleBracket
    {  6, 0,  2374, {   0x11f,     0x0 } }, // gbreve
    {  3, 0,  2380, {    0x5e,     0x0 } }, // Hat
    {  5, 1,  2383, {  0x2246,     0x0 } }, // simne
    {  8, 0,  2388, {   0x3f0,     0x0 } }, // varkappa
    {  7, 0,  2396, {  0x22c4,     0x0 } }, // diamond
    {  6, 0,  2403, {    0xc9,     0x0 } }, // Eacute
    {  9, 0,  2409, {  0x21d3,     0x0 } }, // Downarrow
    {  8, 0,  2418, {  0x2202,     0x0 } }, // PartialD
    { 10, 1,  2426, {  0x230b,     0x0 } }, // RightFloor
    {  2, 0,  2436, {    0xb0,     0x0 } }, // de
    {  4, 0,  2438, { 0x1d4b3,     0x0 } }, // Xscr
    {  6, 0,  2442, {   0x3c2,     0x0 } }, // sigmaf
    {  2, 0,  2448, {  0x2abc,     0x0 } }, // Sc
    {  5, 1,  2450, {  0x266e,     0x0 } }, // natur
    {  9, 1,  2455, {  0x2289,     0x0 } }, // nsupseteq
    {  7, 0,  2464, {  0x2196,     0x0 } }, // nwarrow
    { 18, 0,  2471, {  0x2293,     0x0 } }, // SquareIntersection
    { 12, 1,  2489, {  0x2273,     0x0 } }, // GreaterTilde
    {  8, 1,  2501, {  0x22ce,     0x0 } }, // curlyvee
    {  8, 1,  2509, {  0x27ff,     0x0 } }, // dzigrarr
    {  3, 1,  2517, {  0x2225,     0x0 } }, // par
    {  3, 0,  2520, {    0xb6,     0x0 } }, // par
    {  4, 0,  2523, {   0x3b2,     0x0 } }, // beta
    {  7, 0,  2527, {  0x2969,     0x0 } }, // rdldhar
    {  5, 0,  2534, {   0x45e,     0x0 } }, // ubrcy
    {  3, 1,  2539, {  0x2a92,     0x0 } }, // glE
    { 13, 0,  2542, {  0x21bc,     0x0 } }, // leftharpoonup
    {  6, 1,  2555, {  0x297f,     0x0 } }, // dfisht
    {  5, 0,  2561, {    0xa3,     0x0 } }, // pound
    {  4, 0,  2566, {  0x2298,     0x0 } }, // osol
    {  4, 1,  2570, {  0x2a70,   0x338 } }, // napE
    {  2, 0,  2574, {    0xb1,     0x0 } }, // pm
    {  5, 0,  2576, {  0x226e,     0x0 } }, // nless
    {  5, 1,  2581, {    0xc9,     0x0 } }, // Eacut
    {  4, 0,  2586, {    0xaf,     0x0 } }, // macr
    {  4, 1,  2590, {   0x409,     0x0 } }, // LJcy
    {  7, 1,  2594, {  0x2967,     0x0 } }, // ldrdhar
    {  6, 0,  2601, {  0x2a5f,     0x0 } }, // wedbar
    {  4, 0,  2607, {  0x2ab5,     0x0 } }, // prnE
    {  6, 0,  2611, {   0x150,     0x0 } }, // Odblac
    {  6, 1,  2617, {  0x2105,     0x0 } }, // incare
    {  9, 0,  2623, {  0x228b,     0x0 } }, // supsetneq
    {  6, 0,  2632, {  0x22e1,     0x0 } }, // nsccue
    {  4, 0,  2638, {  0x2a7e,   0x338 } }, // nges
    {  6, 1,  2642, {  0x212c,     0x0 } }, // bernou
    {  5, 1,  2648, {  0x22f1,     0x0 } }, // dtdot
    {  4, 0,  2653, {  0x22d4,     0x0 } }, // fork
    {  8, 0,  2657, {  0x2250,     0x0 } }, // DotEqual
    {  2, 1,  2665, {  0x2147,     0x0 } }, // ee
    {  9, 1,  2667, {  0x211a,     0x0 } }, // rationals
    {  8, 1,  2676, {  0x2a13,     0x0 } }, // scpolint
    {  5, 1,  2684, {  0x2293,     0x0 } }, // sqcap
    {  3, 0,  2689, {   0x432,     0x0 } }, // vcy
    {  5, 0,  2692, {  0x27ed,     0x0 } }, // roang
    {  3, 0,  2697, {  0x2a8b,     0x0 } }, // lEg
    {  6, 0,  2700, {  0x22c1,     0x0 } }, // bigvee
    {  6, 1,  2706, {   0x147,     0x0 } }, // Ncaron
    {  3, 0,  2712, {  0x2a91,     0x0 } }, // lgE
    {  2, 1,  2715, {  0x2265,     0x0 } }, // ge
    {  4, 0,  2717, {    0xa0,     0x0 } }, // nbsp
    { 12, 1,  2721, {  0x2147,     0x0 } }, // exponentiale
    {  9, 0,  2733, {  0x2660,     0x0 } }, // spadesuit
    { 13, 1,  2742, {  0x2aaf,     0x0 } }, // PrecedesEqual
    {  5, 0,  2755, {  0x22e7,     0x0 } }, // gnsim
    {  8, 0,  2760, {  0x29ac,     0x0 } }, // angmsdae
    {  5, 0,  2768, {  0x2129,     0x0 } }, // iiota
    {  4, 0,  2773, { 0x1d4cd,     0x0 } }, // xscr
    {  6, 0,  2777, {   0x165,     0x0 } }, // tcaron
    {  6, 0,  2783, {  0x2020,     0x0 } }, // dagger
    {  4, 1,  2789, {   0x402,     0x0 } }, // DJcy
    {  8, 1,  2793, {  0x2925,     0x0 } }, // hksearow
    {  5, 0,  2801, {  0x221d,     0x0 } }, // vprop
    {  7, 1,  2806, {  0x226c,     0x0 } }, // between
    {  3, 0,  2813, {  0x2265,     0x0 } }, // geq
    {  3, 0,  2816, {   0x14a,     0x0 } }, // ENG
    {  5, 0,  2819, {    0x3f,     0x0 } }, // quest
    { 14, 0,  2824, {  0x2306,     0x0 } }, // doublebarwedge
    {  4, 1,  2838, {  0x2272,     0x0 } }, // lsim
    {  4, 0,  2842, { 0x1d563,     0x0 } }, // ropf
    {  6, 0,  2846, {  0x2927,     0x0 } }, // nwnear
    {  5, 0,  2852, {  0x2556,     0x0 } }, // boxDl
    {  8, 0,  2857, {  0x25b5,     0x0 } }, // triangle
    {  2, 1,  2865, {  0x2063,     0x0 } }, // ic
    {  4, 0,  2867, {   0x17c,     0x0 } }, // zdot
    {  5, 0,  2871, {  0x224c,     0x0 } }, // bcong
    {  3, 0,  2876, { 0x1d535,     0x0 } }, // xfr
    {  3, 0,  2879, { 0x1d534,     0x0 } }, // wfr
    {  6, 0,  2882, {  0x2903,     0x0 } }, // nvrArr
    {  4, 0,  2888, {  0x224b,     0x0 } }, // apid
    {  9, 1,  2892, {  0x21d0,     0x0 } }, // Leftarrow
    {  5, 0,  2901, {  0x21cf,     0x0 } }, // nrArr
    { 19, 1,  2906, {  0x27f8,     0x0 } }, // DoubleLongLeftArrow
    {  4, 0,  2925, {  0x225c,     0x0 } }, // trie
    { 13, 1,  2929, {  0x21d1,     0x0 } }, // DoubleUpArrow
    {  4, 0,  2942, {  0x2a0c,     0x0 } }, // qint
    {  8, 1,  2946, {  0x224c,     0x0 } }, // backcong
    {  4, 0,  2954, {  0x2273,     0x0 } }, // gsim
    {  5, 1,  2958, {  0x2558,     0x0 } }, // boxuR
    {  6, 1,  2963, {  0x2158,     0x0 } }, // frac45
    {  5, 0,  2969, {  0x228e,     0x0 } }, // uplus
    { 11, 0,  2974, {  0x2296,     0x0 } }, // CircleMinus
    {  9, 0,  2985, {    0xb7,     0x0 } }, // CenterDot
    {  4, 1,  2994, {  0x2a42,     0x0 } }, // ncup
    {  7, 0,  2998, {  0x22fd,     0x0 } }, // notnivc
    {  3, 0,  3005, {  0x2ab3,     0x0 } }, // prE
    {  8, 1,  3008, {  0x22b8,     0x0 } }, // multimap
    {  7, 0,  3016, {  0x210e,     0x0 } }, // planckh
    {  8, 0,  3023, {  0x231d,     0x0 } }, // urcorner
    {  4, 1,  3031, {  0x2a88,     0x0 } }, // gneq
    {  5, 0,  3035, {  0x21ad,     0x0 } }, // harrw
    {  3, 0,  3040, {   0x43e,     0x0 } }, // ocy
    {  6, 0,  3043, {    0xcc,     0x0 } }, // Igrave
    {  5, 0,  3049, {  0x2ae9,     0x0 } }, // vBarv
    {  5, 1,  3054, {  0x2322,     0x0 } }, // frown
    {  2, 0,  3059, {  0x2062,     0x0 } }, // it
    {  5, 0,  3061, {  0x201e,     0x0 } }, // bdquo
    {  4, 0,  3066, {  0x2aac,     0x0 } }, // smte
    {  7, 1,  3070, {  0x29c2,     0x0 } }, // cirscir
    {  2, 0,  3077, {  0x227a,     0x0 } }, // pr
    {  4, 1,  3079, {  0x22d5,     0x0 } }, // epar
    {  4, 0,  3083, {    0xa3,     0x0 } }, // poun
    {  5, 1,  3087, {   0x3b4,     0x0 } }, // delta
    {  4, 1,  3092, {    0xbb,     0x0 } }, // raqu
    {  5, 0,  3096, {  0x27f6,     0x0 } }, // xrarr
    {  6, 0,  3101, {  0x2ad3,     0x0 } }, // subsup
    {  4, 0,  3107, {  0x2264,  0x20d2 } }, // nvle
    {  3, 1,  3111, {  0x2249,     0x0 } }, // nap
    {  2, 0,  3114, {  0x227b,     0x0 } }, // sc
    {  2, 1,  3116, {  0x2a54,     0x0 } }, // Or
    {  7, 1,  3118, {  0x2a6d,     0x0 } }, // congdot
    { 14, 1,  3125, {  0x22eb,     0x0 } }, // ntriangleright
    {  5, 0,  3139, {  0x2aac,  0xfe00 } }, // smtes
    { 14, 1,  3144, {  0x22a8,     0x0 } }, // DoubleRightTee
    { 15, 1,  3158, {  0x22ec,     0x0 } }, // ntrianglelefteq
    {  4, 1,  3173, {  0x2191,     0x0 } }, // uarr
    {  5, 0,  3177, {  0x2227,     0x0 } }, // wedge
    {  6, 0,  3182, {   0x3dc,     0x0 } }, // Gammad
    { 13, 0,  3188, {  0x22ea,     0x0 } }, // ntriangleleft
    {  4, 0,  3201, {  0x2268,  0xfe00 } }, // lvnE
    {  6, 0,  3205, {  0x2005,     0x0 } }, // emsp14
    {  5, 0,  3211, {  0x29b5,     0x0 } }, // ohbar
    {  7, 0,  3216, {     0xa,     0x0 } }, // NewLine
    {  5, 0,  3223, {   0x16e,     0x0 } }, // Uring
    {  4, 1,  3228, {    0x3e,  0x20d2 } }, // nvgt
    {  5, 0,  3232, {  0x21bb,     0x0 } }, // orarr
    {  4, 1,  3237, {  0x2110,     0x0 } }, // Iscr
    { 19, 1,  3241, {  0x29d0,   0x338 } }, // NotRightTriangleBar
    {  3, 0,  3260, {  0x2aa5,     0x0 } }, // gla
    {  3, 1,  3263, { 0x1d507,     0x0 } }, // Dfr
    {  5, 0,  3266, {  0x2192,     0x0 } }, // srarr
    { 17, 1,  3271, {  0x2aa1,   0x338 } }, // NotNestedLessLess
    {  6, 0,  3288, {    0xf7,     0x0 } }, // divide
    {  7, 0,  3294, {  0x2276,     0x0 } }, // lessgtr
    {  4, 0,  3301, {    0xd4,     0x0 } }, // Ocir
    {  3, 0,  3305, {  0x2aaa,     0x0 } }, // smt
    { 14, 1,  3308, {  0x2279,     0x0 } }, // NotGreaterLess
    {  5, 1,  3322, {  0x2518,     0x0 } }, // boxul
    {  4, 0,  3327, { 0x1d561,     0x0 } }, // popf
    {  5, 1,  3331, {  0x21da,     0x0 } }, // lAarr
    {  2, 0,  3336, {    0xad,     0x0 } }, // sh
    {  3, 1,  3338, {   0x41b,     0x0 } }, // Lcy
    {  3, 0,  3341, {  0x2a96,     0x0 } }, // egs
    {  4, 0,  3344, {  0x2a38,     0x0 } }, // odiv
    { 17, 1,  3348, {  0x2961,     0x0 } }, // LeftDownTeeVector
    {  6, 1,  3365, {  0x2995,     0x0 } }, // gtlPar
    {  3, 0,  3371, {  0x22da,     0x0 } }, // leg
    {  7, 0,  3374, {  0x22b5,  0x20d2 } }, // nvrtrie
    {  5, 0,  3381, {    0xe6,     0x0 } }, // aelig
    {  6, 0,  3386, {    0x3d,     0x0 } }, // equals
    {  5, 0,  3392, {  0x21ce,     0x0 } }, // nhArr
    {  2, 1,  3397, {   0x39c,     0x0 } }, // Mu
    {  4, 1,  3399, {  0x229a,     0x0 } }, // ocir
    {  4, 0,  3403, {    0xf4,     0x0 } }, // ocir
    {  6, 1,  3407, {   0x10f,     0x0 } }, // dcaron
    {  4, 0,  3413, {   0x2da,     0x0 } }, // ring
    {  6, 1,  3417, {  0x215c,     0x0 } }, // frac38
    {  5, 0,  3423, {  0x2a8e,     0x0 } }, // gsime
    { 10, 0,  3428, {  0x2a8c,     0x0 } }, // gtreqqless
    {  5, 0,  3438, {  0x21c3,     0x0 } }, // dharl
    {  7, 0,  3443, {  0x2a34,     0x0 } }, // lotimes
    {  6, 0,  3450, {  0x21a3,     0x0 } }, // rarrtl
    {  4, 0,  3456, { 0x1d54b,     0x0 } }, // Topf
    { 16, 0,  3460, {  0x2ab0,   0x338 } }, // NotSucceedsEqual
    {  7, 0,  3476, {   0x3a5,     0x0 } }, // Upsilon
    {  6, 0,  3483, {  0x291a,     0x0 } }, // ratail
    {  8, 0,  3489, {  0x2a7d,     0x0 } }, // leqslant
    {  4, 1,  3497, {  0x2257,     0x0 } }, // cire
    {  3, 1,  3501, {    0xb9,     0x0 } }, // sup
    {  3, 1,  3504, {    0xb2,     0x0 } }, // sup
    {  3, 1,  3507, {    0xb3,     0x0 } }, // sup
    {  3, 1,  3510, {  0x2283,     0x0 } }, // sup
    {  4, 0,  3513, {  0x2928,     0x0 } }, // toea
    {  5, 0,  3517, {  0x25b3,     0x0 } }, // xutri
    { 16, 0,  3522, {  0x21f5,     0x0 } }, // DownArrowUpArrow
    {  5, 1,  3538, {   0x391,     0x0 } }, // Alpha
    {  4, 1,  3543, {    0x28,     0x0 } }, // lpar
    {  3, 0,  3547, {  0x2127,     0x0 } }, // mho
    {  5, 0,  3550, {  0x27e7,     0x0 } }, // robrk
    {  3, 1,  3555, { 0x1d512,     0x0 } }, // Ofr
    {  3, 0,  3558, {  0x223f,     0x0 } }, // acd
    {  9, 1,  3561, {  0x2216,     0x0 } }, // Backslash
    {  7, 0,  3570, {  0x2a14,     0x0 } }, // npolint
    {  3, 0,  3577, {   0x424,     0x0 } }, // Fcy
    { 11, 0,  3580, {  0x2a95,     0x0 } }, // eqslantless
    { 16, 1,  3591, {  0x2954,     0x0 } }, // RightUpVectorBar
    {  5, 0,  3607, {   0x15d,     0x0 } }, // scirc
    {  7, 0,  3612, {  0x22f6,     0x0 } }, // notinvc
    {  9, 1,  3619, {  0x230a,     0x0 } }, // LeftFloor
    {  6, 1,  3628, {  0x2a0c,     0x0 } }, // iiiint
    {  7, 0,  3634, {  0x22e2,     0x0 } }, // nsqsube
    {  4, 0,  3641, {  0x25bf,     0x0 } }, // dtri
    {  6, 0,  3645, {   0x10c,     0x0 } }, // Ccaron
    { 19, 0,  3651, {  0x2950,     0x0 } }, // DownLeftRightVector
    {  4, 0,  3670, {  0x2270,     0x0 } }, // nleq
    {  3, 0,  3674, {  0x2270,     0x0 } }, // nle
    {  6, 0,  3677, {  0x2022,     0x0 } }, // bullet
    { 16, 1,  3683, {  0x21d2,     0x0 } }, // DoubleRightArrow
    {  7, 0,  3699, {  0x2935,     0x0 } }, // cudarrr
    {  6, 1,  3706, {  0x2015,     0x0 } }, // horbar
    {  7, 0,  3712, {  0x298f,     0x0 } }, // lbrksld
    {  6, 0,  3719, {  0x2af3,     0x0 } }, // parsim
    {  2, 1,  3725, {   0x3a0,     0x0 } }, // Pi
    {  4, 0,  3727, {    0x29,     0x0 } }, // rpar
    { 14, 1,  3731, {  0x21c3,     0x0 } }, // LeftDownVector
    {  8, 1,  3745, {  0x2225,     0x0 } }, // parallel
    {  5, 0,  3753, {  0x2ab9,     0x0 } }, // prnap
    {  4, 0,  3758, {    0xb2,     0x0 } }, // sup2
    {  7, 1,  3762, {  0x223d,     0x0 } }, // backsim
    {  7, 0,  3769, {  0x2199,     0x0 } }, // swarrow
    {  8, 0,  3776, {  0x224a,     0x0 } }, // approxeq
    {  7, 0,  3784, {  0x22e3,     0x0 } }, // nsqsupe
    {  6, 0,  3791, {  0x22c7,     0x0 } }, // divonx
    { 18, 1,  3797, {  0x295f,     0x0 } }, // DownRightTeeVector
    {  3, 1,  3815, {    0xf7,     0x0 } }, // div
    {  6, 1,  3818, {   0x140,     0x0 } }, // lmidot
    {  2, 1,  3824, {  0x2228,     0x0 } }, // or
    {  7, 0,  3826, {  0x2a35,     0x0 } }, // rotimes
    {  4, 0,  3833, {    0xc4,     0x0 } }, // Auml
    { 12, 0,  3837, {  0x228b,  0xfe00 } }, // varsupsetneq
    {  6, 1,  3849, {  0x25a1,     0x0 } }, // Square
    { 10, 0,  3855, {  0x219a,     0x0 } }, // nleftarrow
    { 12, 0,  3865, {  0x2262,     0x0 } }, // NotCongruent
    {  7, 0,  3877, {  0x2979,     0x0 } }, // subrarr
    {  8, 0,  3884, {  0x29ce,     0x0 } }, // rtriltri
    {  5, 0,  3892, {  0x21cc,     0x0 } }, // rlhar
    {  3, 1,  3897, {  0x2282,     0x0 } }, // sub
    {  4, 0,  3900, {  0x22c1,     0x0 } }, // xvee
    {  6, 1,  3904, {    0xe7,     0x0 } }, // ccedil
    {  6, 1,  3910, {  0x2257,     0x0 } }, // circeq
    {  5, 1,  3916, {  0x290c,     0x0 } }, // lbarr
    {  6, 1,  3921, {  0x22e8,     0x0 } }, // prnsim
    {  4, 0,  3927, {    0xfe,     0x0 } }, // thor
    {  6, 0,  3931, {  0x2297,     0x0 } }, // otimes
    {  4, 0,  3937, {  0x2937,     0x0 } }, // rdca
    {  4, 0,  3941, {  0x221a,     0x0 } }, // Sqrt
    {  3, 0,  3945, { 0x1d50e,     0x0 } }, // Kfr
    {  5, 0,  3948, {  0x21cd,     0x0 } }, // nlArr
    {  4, 0,  3953, { 0x1d4c1,     0x0 } }, // lscr
    { 10, 0,  3957, {  0x21a7,     0x0 } }, // mapstodown
    {  5, 0,  3967, {  0x2111,     0x0 } }, // image
    {  4, 0,  3972, { 0x1d566,     0x0 } }, // uopf
    {  3, 0,  3976, {  0x22c1,     0x0 } }, // Vee
    {  8, 0,  3979, {  0x23e7,     0x0 } }, // elinters
    {  5, 1,  3987, {  0x255c,     0x0 } }, // boxUl
    {  8, 0,  3992, {   0x3d1,     0x0 } }, // vartheta
    {  4, 0,  4000, {  0x219e,     0x0 } }, // Larr
    {  7, 1,  4004, {  0x2a26,     0x0 } }, // plussim
    {  7, 0,  4011, {  0x2a39,     0x0 } }, // triplus
    {  4, 0,  4018, {    0xa7,     0x0 } }, // sect
    {  4, 0,  4022, {   0x2db,     0x0 } }, // ogon
    {  4, 0,  4026, {   0x396,     0x0 } }, // Zeta
    {  2, 1,  4030, {  0x226a,     0x0 } }, // Lt
    {  4, 1,  4032, { 0x1d4a9,     0x0 } }, // Nscr
    { 14, 0,  4036, {  0x2190,     0x0 } }, // ShortLeftArrow
    {  6, 0,  4050, {  0x224f,     0x0 } }, // bumpeq
    {  4, 0,  4056, {  0x2a5a,     0x0 } }, // andv
    {  5, 0,  4060, {    0xfb,     0x0 } }, // ucirc
    { 10, 0,  4065, {  0x21cd,     0x0 } }, // nLeftarrow
    {  4, 0,  4075, {  0x27fc,     0x0 } }, // xmap
    {  4, 0,  4079, {   0x3d2,     0x0 } }, // Upsi
    {  4, 1,  4083, { 0x1d543,     0x0 } }, // Lopf
    {  3, 1,  4087, {    0xf0,     0x0 } }, // eth
    {  8, 1,  4090, {  0x2a84,     0x0 } }, // gesdotol
    {  5, 1,  4098, {  0x2244,     0x0 } }, // nsime
    {  4, 0,  4103, {   0x436,     0x0 } }, // zhcy
    {  6, 0,  4107, {  0x22f9,   0x338 } }, // notinE
    {  5, 0,  4113, {   0x3a3,     0x0 } }, // Sigma
    {  3, 0,  4118, { 0x1d504,     0x0 } }, // Afr
    {  5, 0,  4121, {  0x2308,     0x0 } }, // lceil
    {  4, 0,  4126, { 0x1d4ab,     0x0 } }, // Pscr
    {  6, 0,  4130, {  0x2ad4,     0x0 } }, // supsub
    {  3, 0,  4136, {   0x439,     0x0 } }, // jcy
    { 14, 0,  4139, {  0x2278,     0x0 } }, // NotLessGreater
    { 17, 0,  4153, {  0x21cb,     0x0 } }, // leftrightharpoons
    {  5, 1,  4170, {   0x11d,     0x0 } }, // gcirc
    {  3, 0,  4175, {  0x21b1,     0x0 } }, // rsh
    {  6, 0,  4178, {   0x155,     0x0 } }, // racute
    {  6, 1,  4184, {  0x22a5,     0x0 } }, // bottom
    { 10, 0,  4190, {  0x23b1,     0x0 } }, // rmoustache
    {  4, 0,  4200, {  0x22c6,     0x0 } }, // Star
    {  5, 0,  4204, {  0x2a00,     0x0 } }, // xodot
    {  5, 0,  4209, {  0x22e6,     0x0 } }, // lnsim
    {  5, 1,  4214, {  0x21db,     0x0 } }, // rAarr
    {  5, 0,  4219, {  0x228a,     0x0 } }, // subne
    {  6, 0,  4224, {  0x297e,     0x0 } }, // ufisht
    {  3, 1,  4230, { 0x1d511,     0x0 } }, // Nfr
    {  5, 0,  4233, {  0x25b4,     0x0 } }, // utrif
    {  4, 0,  4238, {    0xc5,     0x0 } }, // Arin
    {  6, 1,  4242, {   0x141,     0x0 } }, // Lstrok
    {  3, 1,  4248, {   0x3b7,     0x0 } }, // eta
    {  4, 0,  4251, {    0xb6,     0x0 } }, // para
    { 13, 1,  4255, {  0x27f5,     0x0 } }, // LongLeftArrow
    {  7, 0,  4268, {  0x29b1,     0x0 } }, // demptyv
    {  5, 1,  4275, {  0x2555,     0x0 } }, // boxdL
    {  9, 0,  4280, {  0x2193,     0x0 } }, // downarrow
    {  8, 1,  4289, {  0x29a9,     0x0 } }, // angmsdab
    {  7, 0,  4297, {  0x2282,  0x20d2 } }, // nsubset
    {  8, 0,  4304, {  0x2312,     0x0 } }, // profline
    {  5, 1,  4312, {    0xbd,     0x0 } }, // frac1
    {  5, 0,  4317, {    0xbc,     0x0 } }, // frac1
    { 16, 0,  4322, {  0x22da,     0x0 } }, // LessEqualGreater
    { 13, 0,  4338, {  0x2225,     0x0 } }, // shortparallel
    { 17, 1,  4351, {  0x2959,     0x0 } }, // LeftDownVectorBar
    {  5, 0,  4368, {  0x266f,     0x0 } }, // sharp
    {  6, 1,  4373, {   0x10d,     0x0 } }, // ccaron
    {  6, 0,  4379, {   0x13e,     0x0 } }, // lcaron
    {  3, 0,  4385, {   0x3c7,     0x0 } }, // chi
    {  6, 0,  4388, {   0x170,     0x0 } }, // Udblac
    {  6, 0,  4394, {   0x167,     0x0 } }, // tstrok
    {  6, 1,  4400, {   0x111,     0x0 } }, // dstrok
    {  9, 0,  4406, {  0x2a7d,   0x338 } }, // nleqslant
    { 11, 0,  4415, {  0x21cc,     0x0 } }, // Equilibrium
    {  8, 0,  4426, {  0x2ab6,     0x0 } }, // succneqq
    {  3, 1,  4434, {    0x2a,     0x0 } }, // ast
    {  6, 0,  4437, {  0x21a6,     0x0 } }, // mapsto
    {  2, 0,  4443, {    0xac,     0x0 } }, // no
    {  7, 1,  4445, {  0x22f5,     0x0 } }, // isindot
    {  5, 0,  4452, {  0x2a9f,     0x0 } }, // simlE
    {  5, 1,  4457, {    0x2c,     0x0 } }, // comma
    {  3, 0,  4462, {  0x222b,     0x0 } }, // int
    {  4, 1,  4465, {   0x117,     0x0 } }, // edot
    {  6, 0,  4469, {    0xe8,     0x0 } }, // egrave
    {  6, 1,  4475, {   0x162,     0x0 } }, // Tcedil
    {  6, 1,  4481, {  0x222e,     0x0 } }, // conint
    {  5, 0,  4487, {  0x21c2,     0x0 } }, // dharr
    {  4, 1,  4492, {   0x425,     0x0 } }, // KHcy
    {  6, 1,  4496, {  0x2217,     0x0 } }, // lowast
    {  3, 0,  4502, {  0x22d8,   0x338 } }, // nLl
    {  5, 1,  4505, {    0xe7,     0x0 } }, // ccedi
    {  6, 0,  4510, {  0x2ad6,     0x0 } }, // supsup
    {  9, 1,  4516, {    0xb7,     0x0 } }, // centerdot
    { 15, 1,  4525, {  0x21c3,     0x0 } }, // downharpoonleft
    {  6, 0,  4540, {  0x210b,     0x0 } }, // hamilt
    {  6, 0,  4546, {   0x154,     0x0 } }, // Racute
    {  4, 0,  4552, {  0x2500,     0x0 } }, // boxh
    { 14, 0,  4556, {  0x21c0,     0x0 } }, // rightharpoonup
    {  6, 0,  4570, {   0x3f1,     0x0 } }, // varrho
    {  6, 0,  4576, {  0x291d,     0x0 } }, // larrfs
    {  4, 0,  4582, {  0x2242,     0x0 } }, // esim
    {  4, 0,  4586, {  0x2026,     0x0 } }, // mldr
    { 14, 0,  4590, {  0x21c7,     0x0 } }, // leftleftarrows
    {  5, 0,  4604, {   0x45b,     0x0 } }, // tshcy
    {  3, 0,  4609, {    0xc4,     0x0 } }, // Aum
    {  5, 0,  4612, {  0x221a,     0x0 } }, // radic
    { 10, 0,  4617, {  0x2912,     0x0 } }, // UpArrowBar
    { 14, 1,  4627, {  0x2199,     0x0 } }, // LowerLeftArrow
    {  4, 0,  4641, { 0x1d562,     0x0 } }, // qopf
    {  6, 1,  4645, {    0xc7,     0x0 } }, // Ccedil
    {  3, 1,  4651, {    0xcf,     0x0 } }, // Ium
    { 14, 0,  4654, {  0x220b,     0x0 } }, // ReverseElement
    {  6, 1,  4668, {  0x2200,     0x0 } }, // ForAll
    {  6, 1,  4674, {  0x22c3,     0x0 } }, // bigcup
    {  6, 0,  4680, {  0x2336,     0x0 } }, // topbot
    { 16, 1,  4686, {  0x21bb,     0x0 } }, // circlearrowright
    {  2, 1,  4702, {  0x24c8,     0x0 } }, // oS
    {  8, 0,  4704, {  0x232e,     0x0 } }, // profalar
    {  5, 0,  4712, {  0x2713,     0x0 } }, // check
    { 15, 0,  4717, {  0x219d,     0x0 } }, // rightsquigarrow
    {  2, 1,  4732, {    0x3c,     0x0 } }, // lt
    {  4, 0,  4734, {  0x22c3,     0x0 } }, // xcup
    { 10, 0,  4738, {  0x21da,     0x0 } }, // Lleftarrow
    {  8, 0,  4748, {  0x2a15,     0x0 } }, // pointint
    {  4, 0,  4756, {   0x453,     0x0 } }, // gjcy
    {  3, 0,  4760, {    0xdc,     0x0 } }, // Uum
    {  5, 0,  4763, {  0x21d8,     0x0 } }, // seArr
    {  5, 1,  4768, {  0x2588,     0x0 } }, // block
    { 14, 0,  4773, {  0x21ac,     0x0 } }, // looparrowright
    { 16, 0,  4787, {  0x21c1,     0x0 } }, // rightharpoondown
    {  4, 1,  4803, {    0xb5,     0x0 } }, // micr
    {  4, 0,  4807, {   0x44e,     0x0 } }, // yucy
    {  6, 1,  4811, {   0x13c,     0x0 } }, // lcedil
    { 11, 1,  4817, {  0x2ab9,     0x0 } }, // precnapprox
    {  4, 0,  4828, {  0x29c4,     0x0 } }, // solb
    { 10, 0,  4832, {  0x2291,     0x0 } }, // sqsubseteq
    { 11, 1,  4842, {  0x2130,     0x0 } }, // expectation
    {  6, 1,  4853, {   0x458,     0x0 } }, // jsercy
    {  5, 1,  4859, {  0x2aa0,     0x0 } }, // simgE
    { 13, 0,  4864, {  0x21bf,     0x0 } }, // upharpoonleft
    {  4, 1,  4877, { 0x1d544,     0x0 } }, // Mopf
    {  5, 0,  4881, {  0x2323,     0x0 } }, // smile
    { 13, 0,  4886, {  0x2242,   0x338 } }, // NotEqualTilde
    {  3, 0,  4899, {   0x418,     0x0 } }, // Icy
    {  3, 0,  4902, {   0x440,     0x0 } }, // rcy
    { 18, 1,  4905, {  0x227d,     0x0 } }, // SucceedsSlantEqual
    {  5, 1,  4923, {  0x220c,     0x0 } }, // notni
    {  9, 0,  4928, {  0x2224,     0x0 } }, // nshortmid
    { 10, 1,  4937, {  0x2295,     0x0 } }, // CirclePlus
    {  6, 0,  4947, {  0x201e,     0x0 } }, // ldquor
    {  3, 1,  4953, {   0x41c,     0x0 } }, // Mcy
    {  4, 0,  4956, {   0x42e,     0x0 } }, // YUcy
    {  5, 0,  4960, {  0x2209,     0x0 } }, // notin
    {  7, 1,  4965, {  0x2a57,     0x0 } }, // orslope
    {  8, 1,  4972, {  0x22e9,     0x0 } }, // succnsim
    {  6, 0,  4980, {    0xf9,     0x0 } }, // ugrave
    {  4, 1,  4986, {  0x2201,     0x0 } }, // comp
    {  3, 1,  4990, {   0x2d9,     0x0 } }, // dot
    {  4, 1,  4993, {  0x29f6,     0x0 } }, // dsol
    {  5, 0,  4997, {  0x2032,     0x0 } }, // prime
    {  5, 0,  5002, {  0x22d7,     0x0 } }, // gtdot
    {  5, 1,  5007, {  0x2033,     0x0 } }, // Prime
    {  3, 0,  5012, { 0x1d532,     0x0 } }, // ufr
    {  5, 0,  5015, {  0x224e,   0x338 } }, // nbump
    {  4, 1,  5020, {    0xd6,     0x0 } }, // Ouml
    {  9, 1,  5024, {  0x23de,     0x0 } }, // OverBrace
    {  4, 1,  5033, {  0x2269,  0xfe00 } }, // gvnE
    {  5, 0,  5037, {  0x29bf,     0x0 } }, // ofcir
    { 22, 1,  5042, {   0x2dd,     0x0 } }, // DiacriticalDoubleAcute
    {  5, 0,  5064, {   0x40e,     0x0 } }, // Ubrcy
    { 14, 1,  5069, {  0x2aa2,     0x0 } }, // GreaterGreater
    {  5, 1,  5083, {  0x21c7,     0x0 } }, // llarr
    {  5, 1,  5088, {  0x2134,     0x0 } }, // order
    { 13, 1,  5093, {  0x2acc,  0xfe00 } }, // varsupsetneqq
    {  5, 0,  5106, {  0x22b2,     0x0 } }, // vltri
    {  7, 1,  5111, {  0x2a00,     0x0 } }, // bigodot
    {  4, 0,  5118, {  0x2229,  0xfe00 } }, // caps
    {  7, 0,  5122, {  0x2ac4,     0x0 } }, // supedot
    {  6, 0,  5129, {  0x2296,     0x0 } }, // ominus
    { 12, 1,  5135, {  0x210b,     0x0 } }, // HilbertSpace
    {  3, 1,  5147, {  0x2227,     0x0 } }, // and
    {  5, 0,  5150, {   0x3c3,     0x0 } }, // sigma
    {  3, 1,  5155, {  0x29c1,     0x0 } }, // ogt
    {  5, 0,  5158, {  0x21ba,     0x0 } }, // olarr
    {  6, 0,  5163, {  0x2157,     0x0 } }, // frac35
    {  3, 0,  5169, {   0x3a8,     0x0 } }, // Psi
    {  6, 0,  5172, {  0x2924,     0x0 } }, // nearhk
    {  6, 1,  5178, {  0x219d,   0x338 } }, // nrarrw
    {  5, 0,  5184, {  0x22a1,     0x0 } }, // sdotb
    {  3, 1,  5189, {    0xa8,     0x0 } }, // die
    {  6, 0,  5192, {  0x2116,     0x0 } }, // numero
    {  8, 1,  5198, {  0x2a89,     0x0 } }, // lnapprox
    {  4, 1,  5206, {   0x45a,     0x0 } }, // njcy
    {  6, 0,  5210, {   0x16d,     0x0 } }, // ubreve
    { 11, 1,  5216, {  0x2308,     0x0 } }, // LeftCeiling
    {  5, 0,  5227, {  0x2aad,  0xfe00 } }, // lates
    {  5, 1,  5232, {  0x2514,     0x0 } }, // boxur
    {  3, 0,  5237, {  0x2ab0,     0x0 } }, // sce
    {  6, 0,  5240, {  0x22a0,     0x0 } }, // timesb
    {  3, 0,  5246, {  0x210c,     0x0 } }, // Hfr
    {  5, 1,  5249, {  0x221e,     0x0 } }, // infin
    {  3, 0,  5254, {  0x2264,     0x0 } }, // leq
    { 13, 0,  5257, {  0x25b4,     0x0 } }, // blacktriangle
    {  5, 0,  5270, {  0x27fa,     0x0 } }, // xhArr
    {  3, 0,  5275, {    0xa9,     0x0 } }, // cop
    {  4, 1,  5278, {  0x2ac5,     0x0 } }, // subE
    { 12, 1,  5282, {  0x25bf,     0x0 } }, // triangledown
    {  4, 0,  5294, { 0x1d4ce,     0x0 } }, // yscr
    {  5, 0,  5298, {    0xe3,     0x0 } }, // atild
    {  4, 0,  5303, {    0xaa,     0x0 } }, // ordf
    {  5, 0,  5307, {   0x398,     0x0 } }, // Theta
    { 17, 0,  5312, {  0x2291,     0x0 } }, // SquareSubsetEqual
    {  5, 1,  5329, {  0x2a4d,     0x0 } }, // ccaps
    {  6, 0,  5334, {  0x2928,     0x0 } }, // nesear
    {  6, 0,  5340, {  0x2665,     0x0 } }, // hearts
    {  6, 1,  5346, {  0x231e,     0x0 } }, // dlcorn
    {  7, 0,  5352, {  0x2a27,     0x0 } }, // plustwo
    {  3, 0,  5359, {   0x3a1,     0x0 } }, // Rho
    {  7, 1,  5362, {  0x2974,     0x0 } }, // rarrsim
    {  4, 0,  5369, {  0x222d,     0x0 } }, // tint
    {  5, 0,  5373, {    0xcd,     0x0 } }, // Iacut
    {  6, 0,  5378, {  0x22f3,     0x0 } }, // isinsv
    {  6, 1,  5384, {    0xbc,     0x0 } }, // frac14
    {  5, 0,  5390, {  0x2584,     0x0 } }, // lhblk
    {  4, 0,  5395, {  0x20ac,     0x0 } }, // euro
    { 17, 1,  5399, {  0x294f,     0x0 } }, // RightUpDownVector
    {  8, 1,  5416, {  0x299d,     0x0 } }, // angrtvbd
    {  4, 1,  5424, { 0x1d4b8,     0x0 } }, // cscr
    {  2, 1,  5428, {  0x2266,     0x0 } }, // lE
    {  5, 0,  5430, {  0x2933,     0x0 } }, // rarrc
    {  3, 1,  5435, {   0x41f,     0x0 } }, // Pcy
    {  3, 0,  5438, {   0x422,     0x0 } }, // Tcy
    {  4, 0,  5441, {    0x5d,     0x0 } }, // rsqb
    {  9, 0,  5445, {    0xb1,     0x0 } }, // PlusMinus
    { 11, 1,  5454, {  0x2283,  0x20d2 } }, // NotSuperset
    {  4, 0,  5465, { 0x1d4b2,     0x0 } }, // Wscr
    {  6, 1,  5469, {   0x13b,     0x0 } }, // Lcedil
    { 10, 1,  5475, {  0x2237,     0x0 } }, // Proportion
    {  4, 0,  5485, { 0x1d555,     0x0 } }, // dopf
    { 20, 0,  5489, {  0x22ec,     0x0 } }, // NotLeftTriangleEqual
    {  4, 0,  5509, {  0x212f,     0x0 } }, // escr
    {  4, 0,  5513, {  0x2929,     0x0 } }, // tosa
    { 14, 0,  5517, {  0x2063,     0x0 } }, // InvisibleComma
    {  8, 1,  5531, {  0x2a6d,   0x338 } }, // ncongdot
    {  3, 0,  5539, { 0x1d530,     0x0 } }, // sfr
    {  4, 0,  5542, {   0x435,     0x0 } }, // iecy
    {  8, 0,  5546, {  0x2a06,     0x0 } }, // bigsqcup
    {  4, 0,  5554, { 0x1d4b7,     0x0 } }, // bscr
    { 10, 0,  5558, {  0x2192,     0x0 } }, // RightArrow
    {  6, 1,  5568, {  0x2640,     0x0 } }, // female
    {  5, 1,  5574, {   0x3c9,     0x0 } }, // omega
    {  8, 1,  5579, {  0x2a36,     0x0 } }, // otimesas
    {  8, 0,  5587, {  0x211c,     0x0 } }, // realpart
    {  5, 1,  5595, {    0xda,     0x0 } }, // Uacut
    {  6, 0,  5600, {  0x22ae,     0x0 } }, // nVdash
    { 14, 1,  5606, {  0x21aa,     0x0 } }, // hookrightarrow
    {  6, 0,  5620, {  0x2ac8,     0x0 } }, // supsim
    {  4, 0,  5626, {  0x29c3,     0x0 } }, // cirE
    {  4, 1,  5630, {   0x40a,     0x0 } }, // NJcy
    {  4, 0,  5634, { 0x1d556,     0x0 } }, // eopf
    {  4, 0,  5638, {   0x3b9,     0x0 } }, // iota
    {  2, 0,  5642, {  0x2240,     0x0 } }, // wr
    { 11, 1,  5644, {  0x229d,     0x0 } }, // circleddash
    {  2, 0,  5655, {  0x2146,     0x0 } }, // dd
    {  4, 0,  5657, {   0x3f1,     0x0 } }, // rhov
    {  7, 1,  5661, {  0x2938,     0x0 } }, // cudarrl
    {  5, 1,  5668, {  0x21c4,     0x0 } }, // rlarr
    {  5, 0,  5673, {  0x2243,     0x0 } }, // simeq
    { 15, 1,  5678, {  0x21c1,     0x0 } }, // DownRightVector
    {  9, 1,  5693, {  0x2035,     0x0 } }, // backprime
    {  6, 0,  5702, {    0x5f,     0x0 } }, // lowbar
    {  5, 1,  5708, {  0x2295,     0x0 } }, // oplus
    {  4, 0,  5713, {    0xd7,     0x0 } }, // time
    {  4, 0,  5717, {   0x42f,     0x0 } }, // YAcy
    {  5, 0,  5721, {   0x135,     0x0 } }, // jcirc
    {  4, 0,  5726, {  0x2016,     0x0 } }, // Vert
    { 20, 0,  5730, {  0x296f,     0x0 } }, // ReverseUpEquilibrium
    {  6, 1,  5750, {  0x2916,     0x0 } }, // Rarrtl
    {  7, 0,  5756, {  0x2a3c,     0x0 } }, // intprod
    { 20, 1,  5763, {  0x2a7e,   0x338 } }, // NotGreaterSlantEqual
    {  5, 0,  5783, {   0x2c7,     0x0 } }, // caron
    {  8, 0,  5788, {  0x2a83,     0x0 } }, // lesdotor
    {  4, 0,  5796, {   0x178,     0x0 } }, // Yuml
    {  6, 0,  5800, {   0x156,     0x0 } }, // Rcedil
    {  5, 0,  5806, {  0x2122,     0x0 } }, // trade
    {  4, 0,  5811, {  0x21b3,     0x0 } }, // rdsh
    {  4, 1,  5815, {  0x2502,     0x0 } }, // boxv
    {  6, 1,  5819, {    0x7b,     0x0 } }, // lbrace
    {  5, 0,  5825, {  0x260e,     0x0 } }, // phone
    {  5, 0,  5830, {   0x16b,     0x0 } }, // umacr
    {  5, 0,  5835, {    0xd7,     0x0 } }, // times
    {  6, 1,  5840, {  0x2a94,     0x0 } }, // gesles
    {  6, 0,  5846, {   0x146,     0x0 } }, // ncedil
    {  6, 1,  5852, {  0x225f,     0x0 } }, // equest
    {  6, 0,  5858, {   0x3bb,     0x0 } }, // lambda
    { 21, 1,  5864, {  0x25aa,     0x0 } }, // FilledVerySmallSquare
    {  5, 0,  5885, {  0x2aa8,     0x0 } }, // lescc
    { 15, 1,  5890, {  0x2960,     0x0 } }, // LeftUpTeeVector
    {  6, 0,  5905, {  0x22a7,     0x0 } }, // models
    {  2, 0,  5911, {  0x2abb,     0x0 } }, // Pr
    {  3, 0,  5913, {   0x42b,     0x0 } }, // Ycy
    {  6, 1,  5916, {  0x22af,     0x0 } }, // nVDash
    {  8, 0,  5922, {   0x3d1,     0x0 } }, // thetasym
    {  4, 1,  5930, {  0x27e8,     0x0 } }, // lang
    {  3, 0,  5934, { 0x1d533,     0x0 } }, // vfr
    {  5, 1,  5937, {  0x2559,     0x0 } }, // boxUr
    {  4, 0,  5942, {  0x22db,  0xfe00 } }, // gesl
    {  3, 1,  5946, {   0x41d,     0x0 } }, // Ncy
    {  6, 0,  5949, {  0x230b,     0x0 } }, // rfloor
    {  8, 1,  5955, {  0x29ad,     0x0 } }, // angmsdaf
    {  3, 0,  5963, {  0x22fc,     0x0 } }, // nis
    { 11, 0,  5966, {  0x2195,     0x0 } }, // updownarrow
    {  5, 0,  5977, {  0x21c0,     0x0 } }, // rharu
    {  9, 0,  5982, {  0x2288,     0x0 } }, // nsubseteq
    {  4, 1,  5991, {  0x2193,     0x0 } }, // darr
    {  6, 0,  5995, {    0xec,     0x0 } }, // igrave
    {  4, 1,  6001, {   0x416,     0x0 } }, // ZHcy
    {  6, 0,  6005, {    0xbf,     0x0 } }, // iquest
    {  3, 0,  6011, {  0x2266,   0x338 } }, // nlE
    {  2, 0,  6014, {    0xa5,     0x0 } }, // ye
    {  5, 1,  6016, {    0xe9,     0x0 } }, // eacut
    {  7, 0,  6021, {  0x2968,     0x0 } }, // ruluhar
    {  6, 1,  6028, {  0x2138,     0x0 } }, // daleth
    {  5, 0,  6034, {   0x3ba,     0x0 } }, // kappa
    { 13, 1,  6039, {  0x296e,     0x0 } }, // UpEquilibrium
    {  4, 1,  6052, { 0x1d54e,     0x0 } }, // Wopf
    {  3, 0,  6056, { 0x1d529,     0x0 } }, // lfr
    {  4, 1,  6059, { 0x1d546,     0x0 } }, // Oopf
    { 18, 0,  6063, {  0x295d,     0x0 } }, // RightDownTeeVector
    {  8, 0,  6081, {  0x22ba,     0x0 } }, // intercal
    {  6, 0,  6089, {  0x223b,     0x0 } }, // homtht
    { 11, 1,  6095, {  0x2286,     0x0 } }, // SubsetEqual
    {  4, 0,  6106, {    0xe5,     0x0 } }, // arin
    {  6, 0,  6110, {   0x13f,     0x0 } }, // Lmidot
    { 13, 1,  6116, {  0x2252,     0x0 } }, // fallingdotseq
    {  6, 0,  6129, {   0x161,     0x0 } }, // scaron
    {  5, 0,  6135, {  0x201c,     0x0 } }, // ldquo
    {  4, 0,  6140, { 0x1d568,     0x0 } }, // wopf
    {  9, 1,  6144, {  0x2299,     0x0 } }, // CircleDot
    {  1, 1,  6153, {    0x3e,     0x0 } }, // G
    { 11, 1,  6154, {  0x2666,     0x0 } }, // diamondsuit
    {  4, 1,  6165, {   0x192,     0x0 } }, // fnof
    { 10, 0,  6169, {  0x2ac5,   0x338 } }, // nsubseteqq
    {  6, 1,  6179, {   0x42c,     0x0 } }, // SOFTcy
    {  7, 0,  6185, {  0x2204,     0x0 } }, // nexists
    {  2, 1,  6192, {  0x2145,     0x0 } }, // DD
    {  7, 0,  6194, {  0x237c,     0x0 } }, // angzarr
    {  5, 0,  6201, {  0x204f,     0x0 } }, // bsemi
    {  4, 0,  6206, {  0x2a89,     0x0 } }, // lnap
    {  3, 0,  6210, { 0x1d50a,     0x0 } }, // Gfr
    {  5, 1,  6213, {  0x22cd,     0x0 } }, // bsime
    {  7, 1,  6218, {  0x22fe,     0x0 } }, // notnivb
    {  6, 0,  6225, {  0x2214,     0x0 } }, // plusdo
    {  5, 0,  6231, {  0x2a4c,     0x0 } }, // ccups
    {  6, 0,  6236, {  0x223e,     0x0 } }, // mstpos
    {  4, 0,  6242, { 0x1d55c,     0x0 } }, // kopf
    {  8, 0,  6246, {  0x2251,     0x0 } }, // doteqdot
    {  5, 1,  6254, {  0x2a2f,     0x0 } }, // Cross
    {  8, 0,  6259, {  0x27c8,     0x0 } }, // bsolhsub
    {  7, 0,  6267, {  0x2283,  0x20d2 } }, // nsupset
    { 14, 0,  6274, {  0x2953,     0x0 } }, // RightVectorBar
    { 10, 1,  6288, {  0x23df,     0x0 } }, // UnderBrace
    {  3, 0,  6298, {  0x2229,     0x0 } }, // cap
    { 15, 1,  6301, {  0x2271,     0x0 } }, // NotGreaterEqual
    {  5, 1,  6316, {  0x255d,     0x0 } }, // boxUL
    { 11, 0,  6321, {  0x227d,     0x0 } }, // succcurlyeq
    { 16, 1,  6332, {  0x27e8,     0x0 } }, // LeftAngleBracket
    {  4, 0,  6348, { 0x1d4b9,     0x0 } }, // dscr
    { 15, 1,  6352, {  0x21bd,     0x0 } }, // leftharpoondown
    {  4, 0,  6367, {  0x25ad,     0x0 } }, // rect
    {  5, 0,  6371, {  0x2294,     0x0 } }, // sqcup
    {  5, 1,  6376, {  0x2971,     0x0 } }, // erarr
    { 10, 0,  6381, {  0x2ab7,     0x0 } }, // precapprox
    {  5, 0,  6391, {    0xea,     0x0 } }, // ecirc
    {  6, 0,  6396, {   0x103,     0x0 } }, // abreve
    { 10, 1,  6402, {  0x226f,     0x0 } }, // NotGreater
    {  7, 0,  6412, {  0x2720,     0x0 } }, // maltese
    {  4, 0,  6419, {  0x2964,     0x0 } }, // rHar
    { 16, 1,  6423, {  0x295c,     0x0 } }, // RightUpTeeVector
    {  9, 0,  6439, {  0x2009,     0x0 } }, // ThinSpace
    {  2, 1,  6448, {    0x3c,     0x0 } }, // LT
    {  3, 0,  6450, {  0x21b0,     0x0 } }, // lsh
    {  7, 0,  6453, {  0x2a3b,     0x0 } }, // tritime
    { 11, 1,  6460, {  0x2294,     0x0 } }, // SquareUnion
    {  6, 0,  6471, {  0x2004,     0x0 } }, // emsp13
    {  6, 1,  6477, {  0x2a6f,     0x0 } }, // apacir
    {  6, 0,  6483, {  0x2156,     0x0 } }, // frac25
    {  5, 0,  6489, {   0x175,     0x0 } }, // wcirc
    {  5, 0,  6494, {  0x2aa9,     0x0 } }, // gescc
    { 16, 1,  6499, {  0x21c5,     0x0 } }, // UpArrowDownArrow
    {  7, 0,  6515, {  0x22be,     0x0 } }, // angrtvb
    {  5, 1,  6522, {  0x290f,     0x0 } }, // rBarr
    {  7, 0,  6527, {  0x298e,     0x0 } }, // rbrksld
    {  5, 0,  6534, {  0x2216,     0x0 } }, // setmn
    { 16, 1,  6539, {  0x22db,     0x0 } }, // GreaterEqualLess
    {  5, 0,  6555, {  0x2248,     0x0 } }, // thkap
    { 20, 1,  6560, {  0x226b,     0x0 } }, // NestedGreaterGreater
    {  3, 0,  6580, { 0x1d514,     0x0 } }, // Qfr
    {  5, 1,  6583, {   0x132,     0x0 } }, // IJlig
    {  3, 0,  6588, {  0x22a4,     0x0 } }, // top
    { 15, 1,  6591, {  0x22ea,     0x0 } }, // NotLeftTriangle
    { 10, 0,  6606, {  0x2201,     0x0 } }, // complement
    {  2, 0,  6616, {   0x39d,     0x0 } }, // Nu
    {  4, 1,  6618, {    0xeb,     0x0 } }, // euml
    {  3, 0,  6622, {    0xff,     0x0 } }, // yum
    {  9, 1,  6625, {    0xa8,     0x0 } }, // DoubleDot
    {  4, 0,  6634, {  0x29b6,     0x0 } }, // omid
    {  4, 0,  6638, { 0x1d540,     0x0 } }, // Iopf
    {  4, 0,  6642, {  0x2220,  0x20d2 } }, // nang
    {  6, 1,  6646, {  0x2975,     0x0 } }, // rarrap
    {  6, 0,  6652, {  0x22e9,     0x0 } }, // scnsim
    {  4, 0,  6658, {   0x3d5,     0x0 } }, // phiv
    { 14, 0,  6662, {  0x21b6,     0x0 } }, // curvearrowleft
    {  5, 0,  6676, {  0x2acb,     0x0 } }, // subnE
    {  5, 0,  6681, {  0x22b8,     0x0 } }, // mumap
    {  6, 1,  6686, {   0x122,     0x0 } }, // Gcedil
    {  8, 1,  6692, {  0x2232,     0x0 } }, // cwconint
    {  6, 0,  6700, {   0x449,     0x0 } }, // shchcy
    {  4, 0,  6706, {  0x2266,     0x0 } }, // leqq
    {  5, 0,  6710, {   0x153,     0x0 } }, // oelig
    {  5, 1,  6715, {   0x11c,     0x0 } }, // Gcirc
    {  5, 0,  6720, {    0xe2,     0x0 } }, // acirc
    {  6, 0,  6725, {  0x297c,     0x0 } }, // lfisht
    {  6, 1,  6731, {  0x2248,     0x0 } }, // approx
    {  4, 0,  6737, {   0x446,     0x0 } }, // tscy
    {  7, 0,  6741, {   0x39f,     0x0 } }, // Omicron
    {  6, 0,  6748, {  0x2a44,     0x0 } }, // capand
    { 15, 0,  6754, {   0x3f5,     0x0 } }, // straightepsilon
    { 13, 1,  6769, {  0x210c,     0x0 } }, // Poincareplane
    {  4, 1,  6782, {  0x2550,     0x0 } }, // boxH
    {  4, 0,  6786, { 0x1d56b,     0x0 } }, // zopf
    {  4, 1,  6790, {  0x22fa,     0x0 } }, // nisd
    {  5, 0,  6794, {    0xfa,     0x0 } }, // uacut
    {  6, 1,  6799, {   0x13d,     0x0 } }, // Lcaron
    {  5, 1,  6805, {  0x21b5,     0x0 } }, // crarr
    { 15, 0,  6810, {  0x21c6,     0x0 } }, // leftrightarrows
    {  9, 0,  6825, {  0x2102,     0x0 } }, // complexes
    {  5, 0,  6834, {  0x2135,     0x0 } }, // aleph
    {  5, 0,  6839, {    0xc1,     0x0 } }, // Aacut
    {  6, 0,  6844, {  0x2a2d,     0x0 } }, // loplus
    {  5, 1,  6850, {    0xce,     0x0 } }, // Icirc
    {  4, 0,  6855, {  0x2a87,     0x0 } }, // lneq
    {  4, 0,  6859, {  0x2aed,     0x0 } }, // bNot
    {  3, 1,  6863, {  0x22a5,     0x0 } }, // bot
    {  6, 1,  6866, {  0x200a,     0x0 } }, // hairsp
    {  5, 0,  6872, {  0x290d,     0x0 } }, // rbarr
    {  5, 0,  6877, {  0x2197,     0x0 } }, // nearr
    {  6, 0,  6882, {  0x222f,     0x0 } }, // Conint
    {  6, 0,  6888, {    0xf1,     0x0 } }, // ntilde
    { 18, 0,  6894, {  0x200b,     0x0 } }, // NegativeThickSpace
    {  4, 1,  6912, {  0x2194,     0x0 } }, // harr
    {  3, 0,  6916, {    0xa5,     0x0 } }, // yen
    {  7, 1,  6919, {  0x22f7,     0x0 } }, // notinvb
    {  5, 0,  6926, {  0x21d9,     0x0 } }, // swArr
    {  6, 0,  6931, {  0x2030,     0x0 } }, // permil
    {  4, 0,  6937, { 0x1d4c2,     0x0 } }, // mscr
    {  4, 0,  6941, { 0x1d539,     0x0 } }, // Bopf
    { 14, 0,  6945, {  0x21d4,     0x0 } }, // Leftrightarrow
    {  6, 0,  6959, {   0x160,     0x0 } }, // Scaron
    {  4, 1,  6965, { 0x1d4b1,     0x0 } }, // Vscr
    {  6, 0,  6969, {  0x230d,     0x0 } }, // dlcrop
    {  4, 0,  6975, { 0x1d4ac,     0x0 } }, // Qscr
    {  6, 0,  6979, {  0x22ba,     0x0 } }, // intcal
    {  3, 1,  6985, {   0x3a4,     0x0 } }, // Tau
    {  6, 0,  6988, {   0x144,     0x0 } }, // nacute
    { 18, 0,  6994, {  0x21cb,     0x0 } }, // ReverseEquilibrium
    {  6, 1,  7012, {  0x2a74,     0x0 } }, // Colone
    {  7, 1,  7018, {  0x2135,     0x0 } }, // alefsym
    {  5, 0,  7025, {  0x226c,     0x0 } }, // twixt
    {  9, 1,  7030, {  0x224f,     0x0 } }, // HumpEqual
    { 11, 1,  7039, {  0x21c0,     0x0 } }, // RightVector
    {  3, 1,  7050, { 0x1d526,     0x0 } }, // ifr
    {  3, 0,  7053, { 0x1d527,     0x0 } }, // jfr
    {  5, 1,  7056, {  0x2591,     0x0 } }, // blk14
    {  4, 0,  7061, {  0x2287,     0x0 } }, // supe
    {  5, 1,  7065, {  0x2554,     0x0 } }, // boxDR
    {  6, 0,  7070, {  0x2a6e,     0x0 } }, // easter
    {  4, 0,  7076, {    0xb9,     0x0 } }, // sup1
    { 10, 1,  7080, {  0x23b0,     0x0 } }, // lmoustache
    {  3, 1,  7090, {    0xf6,     0x0 } }, // oum
    {  3, 0,  7093, {    0xa7,     0x0 } }, // sec
    {  3, 0,  7096, {  0x2271,     0x0 } }, // nge
    { 15, 0,  7099, {  0x2192,     0x0 } }, // ShortRightArrow
    {  4, 0,  7114, { 0x1d4be,     0x0 } }, // iscr
    {  2, 0,  7118, {  0x226b,     0x0 } }, // Gt
    {  5, 0,  7120, {  0x2212,     0x0 } }, // minus
    {  4, 0,  7125, { 0x1d565,     0x0 } }, // topf
    {  4, 0,  7129, { 0x1d550,     0x0 } }, // Yopf
    {  4, 1,  7133, {  0x2a8a,     0x0 } }, // gnap
    {  4, 0,  7137, {  0x2a9e,     0x0 } }, // simg
    { 11, 1,  7141, {  0x23b4,     0x0 } }, // OverBracket
    {  5, 1,  7152, {  0x27ec,     0x0 } }, // loang
    {  9, 0,  7157, {  0x22d4,     0x0 } }, // pitchfork
    {  3, 1,  7166, {  0x2a5d,     0x0 } }, // ord
    {  3, 1,  7169, {    0xaa,     0x0 } }, // ord
    {  3, 0,  7172, {    0xba,     0x0 } }, // ord
    {  6, 0,  7175, {    0xda,     0x0 } }, // Uacute
    {  4, 0,  7181, {    0xa9,     0x0 } }, // copy
    {  5, 1,  7185, {   0x3f6,     0x0 } }, // bepsi
    {  6, 0,  7190, {    0x7c,     0x0 } }, // verbar
    { 16, 0,  7196, {  0x22b3,     0x0 } }, // vartriangleright
    {  6, 0,  7212, {  0x2305,     0x0 } }, // barwed
    {  3, 0,  7218, {  0x2211,     0x0 } }, // sum
    {  4, 1,  7221, {  0x2ae7,     0x0 } }, // Barv
    {  5, 1,  7225, {  0x2717,     0x0 } }, // cross
    {  5, 0,  7230, {  0x21d6,     0x0 } }, // nwArr
    {  6, 0,  7235, {   0x3d1,     0x0 } }, // thetav
    {  5, 0,  7241, {  0xfb00,     0x0 } }, // fflig
    {  5, 0,  7246, {  0x29be,     0x0 } }, // olcir
    {  8, 1,  7251, {  0x2a48,     0x0 } }, // cupbrcap
    {  5, 0,  7259, {  0x2242,   0x338 } }, // nesim
    { 11, 0,  7264, {  0x2223,     0x0 } }, // VerticalBar
    {  5, 1,  7275, {  0x255f,     0x0 } }, // boxVr
    {  5, 0,  7280, {  0x22b4,     0x0 } }, // ltrie
    {  3, 1,  7285, {  0x211c,     0x0 } }, // Rfr
    {  2, 0,  7288, {   0x3bd,     0x0 } }, // nu
    {  4, 1,  7290, { 0x1d4b0,     0x0 } }, // Uscr
    {  5, 0,  7294, {  0x2203,     0x0 } }, // exist
    {  8, 0,  7299, {  0x2205,     0x0 } }, // emptyset
    {  5, 0,  7307, {  0x25b1,     0x0 } }, // fltns
    {  3, 0,  7312, {   0x437,     0x0 } }, // zcy
    {  4, 0,  7315, {    0xbd,     0x0 } }, // half
    {  6, 0,  7319, {  0x297d,     0x0 } }, // rfisht
    {  3, 1,  7325, {   0x423,     0x0 } }, // Ucy
    {  5, 1,  7328, {  0x2041,     0x0 } }, // caret
    {  3, 0,  7333, {    0xa0,     0x0 } }, // nbs
    {  5, 0,  7336, {  0x2773,     0x0 } }, // rbbrk
    {  5, 0,  7341, {  0x21ff,     0x0 } }, // hoarr
    {  6, 0,  7346, {  0x224e,     0x0 } }, // Bumpeq
    {  6, 1,  7352, {    0xc0,     0x0 } }, // Agrave
    {  5, 1,  7358, {   0x456,     0x0 } }, // iukcy
    {  6, 0,  7363, {  0x2262,     0x0 } }, // nequiv
    {  4, 0,  7369, {   0x120,     0x0 } }, // Gdot
    { 18, 0,  7373, {  0x27f7,     0x0 } }, // longleftrightarrow
    {  4, 0,  7391, {  0x21d1,     0x0 } }, // uArr
    { 12, 0,  7395, {  0x2253,     0x0 } }, // risingdotseq
    {  6, 0,  7407, {   0x44a,     0x0 } }, // hardcy
    {  4, 0,  7413, {  0x25c3,     0x0 } }, // ltri
    {  5, 1,  7417, {  0x227d,     0x0 } }, // sccue
    {  6, 0,  7422, {  0x2294,  0xfe00 } }, // sqcups
    {  4, 0,  7428, {    0xe4,     0x0 } }, // auml
    {  4, 0,  7432, {    0xca,     0x0 } }, // Ecir
    { 11, 1,  7436, {  0x2280,     0x0 } }, // NotPrecedes
    {  5, 0,  7447, {  0x2019,     0x0 } }, // rsquo
    {  3, 0,  7452, {  0x2ab4,     0x0 } }, // scE
    {  5, 1,  7455, {    0xa4,     0x0 } }, // curre
    {  6, 1,  7460, {  0x2238,     0x0 } }, // minusd
    {  3, 0,  7466, {  0x2a5b,     0x0 } }, // orv
    {  4, 0,  7469, { 0x1d538,     0x0 } }, // Aopf
    {  4, 0,  7473, { 0x1d560,     0x0 } }, // oopf
    {  6, 0,  7477, {   0x131,     0x0 } }, // inodot
    {  4, 0,  7483, {   0x452,     0x0 } }, // djcy
    {  4, 1,  7487, {    0xc2,     0x0 } }, // Acir
    {  5, 1,  7491, {   0x118,     0x0 } }, // Eogon
    {  4, 0,  7496, {  0x224e,     0x0 } }, // bump
    {  7, 1,  7500, {  0x29bb,     0x0 } }, // olcross
    {  5, 0,  7507, {  0x2283,  0x20d2 } }, // vnsup
    {  4, 1,  7512, {  0x2286,     0x0 } }, // sube
    {  4, 0,  7516, {  0x2195,     0x0 } }, // varr
    {  7, 0,  7520, {   0x3bf,     0x0 } }, // omicron
    {  8, 0,  7527, {  0x2260,     0x0 } }, // NotEqual
    { 16, 0,  7535, {  0x22eb,     0x0 } }, // NotRightTriangle
    {  9, 0,  7551, {  0x2204,     0x0 } }, // NotExists
    {  6, 0,  7560, {  0x2021,     0x0 } }, // Dagger
    { 13, 1,  7566, {  0x227e,     0x0 } }, // PrecedesTilde
    {  6, 1,  7579, {  0x2a7f,     0x0 } }, // lesdot
    {  6, 0,  7585, {  0x2119,     0x0 } }, // primes
    {  3, 1,  7591, { 0x1d517,     0x0 } }, // Tfr
    {  4, 0,  7594, {  0x2190,     0x0 } }, // larr
    {  9, 1,  7598, {  0x2213,     0x0 } }, // MinusPlus
    {  8, 0,  7607, {  0x29aa,     0x0 } }, // angmsdac
    {  6, 0,  7615, {  0x2043,     0x0 } }, // hybull
    {  5, 0,  7621, {   0x15c,     0x0 } }, // Scirc
    {  8, 0,  7626, {  0x2111,     0x0 } }, // imagpart
    {  6, 1,  7634, {    0xd1,     0x0 } }, // Ntilde
    {  2, 1,  7640, {  0x2264,     0x0 } }, // le
    { 14, 1,  7642, {  0x27f6,     0x0 } }, // longrightarrow
    { 10, 0,  7656, {  0x2192,     0x0 } }, // rightarrow
    {  3, 0,  7666, {    0xeb,     0x0 } }, // eum
    {  4, 0,  7669, { 0x1d4ae,     0x0 } }, // Sscr
    {  4, 0,  7673, {   0x3b6,     0x0 } }, // zeta
    {  5, 0,  7677, {  0x2007,     0x0 } }, // numsp
    {  5, 0,  7682, {  0x21e4,     0x0 } }, // larrb
    {  5, 0,  7687, {  0x2a71,     0x0 } }, // eplus
    { 17, 0,  7692, {  0x25be,     0x0 } }, // blacktriangledown
    {  2, 1,  7709, {    0xf0,     0x0 } }, // et
    {  6, 0,  7711, {  0x2ab0,     0x0 } }, // succeq
    {  3, 0,  7717, {  0x2113,     0x0 } }, // ell
    {  5, 0,  7720, {  0x255e,     0x0 } }, // boxvR
    {  3, 0,  7725, {    0xa2,     0x0 } }, // cen
    { 10, 1,  7728, {  0x22cf,     0x0 } }, // curlywedge
    {  2, 0,  7738, {    0x3e,     0x0 } }, // gt
    {  2, 1,  7740, {  0x2148,     0x0 } }, // ii
    {  4, 0,  7742, {   0x3c5,     0x0 } }, // upsi
    {  5, 0,  7746, {  0x21cb,     0x0 } }, // lrhar
    {  3, 0,  7751, {   0x3d6,     0x0 } }, // piv
    {  6, 1,  7754, {   0x145,     0x0 } }, // Ncedil
    {  6, 1,  7760, {   0x44c,     0x0 } }, // softcy
    {  4, 0,  7766, {  0x2ae8,     0x0 } }, // vBar
    {  4, 0,  7770, {  0x266a,     0x0 } }, // sung
    { 10, 0,  7774, {  0x2209,     0x0 } }, // NotElement
    { 31, 0,  7784, {  0x2233,     0x0 } }, // CounterClockwiseContourIntegral
    { 13, 0,  7815, {  0x21be,     0x0 } }, // RightUpVector
    { 15, 0,  7828, {  0x2275,     0x0 } }, // NotGreaterTilde
    {  3, 1,  7843, {  0x212d,     0x0 } }, // Cfr
    {  3, 1,  7846, {  0x200e,     0x0 } }, // lrm
    {  7, 0,  7849, {  0x2abf,     0x0 } }, // subplus
    { 13, 0,  7856, {  0x2266,     0x0 } }, // LessFullEqual
    {  4, 1,  7869, {   0x392,     0x0 } }, // Beta
    {  5, 0,  7873, {  0x223c,  0x20d2 } }, // nvsim
    {  6, 1,  7878, {  0x27e8,     0x0 } }, // langle
    {  5, 0,  7884, {  0x2282,  0x20d2 } }, // vnsub
    {  5, 0,  7889, {  0x2247,     0x0 } }, // ncong
    {  4, 0,  7894, {  0x21d2,     0x0 } }, // rArr
    { 12, 0,  7898, {  0x21bf,     0x0 } }, // LeftUpVector
    {  4, 0,  7910, {  0x22fb,     0x0 } }, // xnis
    {  4, 0,  7914, {  0x210b,     0x0 } }, // Hscr
    {  5, 0,  7918, {  0x2236,     0x0 } }, // ratio
    {  5, 0,  7923, {   0x149,     0x0 } }, // napos
    { 17, 1,  7928, {  0x2247,     0x0 } }, // NotTildeFullEqual
    {  4, 1,  7945, {   0x407,     0x0 } }, // YIcy
    {  3, 1,  7949, {   0x430,     0x0 } }, // acy
    {  6, 0,  7952, {  0x228d,     0x0 } }, // cupdot
    { 15, 0,  7958, {  0x29cf,     0x0 } }, // LeftTriangleBar
    { 11, 1,  7973, {  0x226a,   0x338 } }, // NotLessLess
    {  5, 1,  7984, {  0x2252,     0x0 } }, // efDot
    {  4, 1,  7989, {  0x2ab0,   0x338 } }, // nsce
    {  4, 0,  7993, {  0x2202,     0x0 } }, // part
    {  3, 1,  7997, {    0x26,     0x0 } }, // amp
    {  4, 0,  8000, {   0x445,     0x0 } }, // khcy
    {  5, 0,  8004, {  0x229d,     0x0 } }, // odash
    { 21, 1,  8009, {  0x22e1,     0x0 } }, // NotSucceedsSlantEqual
    {  6, 0,  8030, {   0x137,     0x0 } }, // kcedil
    { 11, 1,  8036, {  0x2297,     0x0 } }, // CircleTimes
    { 14, 0,  8047, {  0x2245,     0x0 } }, // TildeFullEqual
    {  6, 0,  8061, {  0x228a,  0xfe00 } }, // vsubne
    {  9, 0,  8067, {  0x2133,     0x0 } }, // Mellintrf
    {  6, 1,  8076, {   0x39b,     0x0 } }, // Lambda
    { 21, 0,  8082, {  0x22ed,     0x0 } }, // NotRightTriangleEqual
    {  4, 1,  8103, {  0x2551,     0x0 } }, // boxV
    {  4, 0,  8107, {  0x2720,     0x0 } }, // malt
    {  6, 0,  8111, {  0x2a98,     0x0 } }, // egsdot
    {  8, 1,  8117, {  0x2949,     0x0 } }, // Uarrocir
    {  3, 0,  8125, {  0x29c0,     0x0 } }, // olt
    {  6, 1,  8128, {   0x138,     0x0 } }, // kgreen
    {  3, 0,  8134, {  0x2281,     0x0 } }, // nsc
    { 14, 1,  8137, {  0x2194,     0x0 } }, // LeftRightArrow
    {  7, 0,  8151, {  0x224d,     0x0 } }, // asympeq
    {  4, 0,  8158, {   0x10a,     0x0 } }, // Cdot
    {  6, 0,  8162, {    0xd2,     0x0 } }, // Ograve
    {  7, 1,  8168, {  0x22a4,     0x0 } }, // DownTee
    {  9, 0,  8175, {  0x2a7e,   0x338 } }, // ngeqslant
    {  4, 0,  8184, {  0x2606,     0x0 } }, // star
    { 11, 1,  8188, {  0x2277,     0x0 } }, // GreaterLess
    {  4, 1,  8199, {  0x2115,     0x0 } }, // Nopf
    {  5, 0,  8203, {  0x228f,     0x0 } }, // sqsub
    {  6, 0,  8208, {    0xb7,     0x0 } }, // middot
    {  8, 0,  8214, {  0x2241,     0x0 } }, // NotTilde
    { 11, 1,  8222, {  0x2276,     0x0 } }, // LessGreater
    {  5, 1,  8233, {   0x113,     0x0 } }, // emacr
    {  6, 0,  8238, {  0x2200,     0x0 } }, // forall
    { 15, 1,  8244, {  0x2198,     0x0 } }, // LowerRightArrow
    { 14, 1,  8259, {  0x2193,     0x0 } }, // ShortDownArrow
    {  5, 1,  8273, {    0xdb,     0x0 } }, // Ucirc
    {  5, 1,  8278, {  0x255a,     0x0 } }, // boxUR
    {  5, 1,  8283, {  0x2a77,     0x0 } }, // eDDot
    {  6, 0,  8288, {  0x21ab,     0x0 } }, // larrlp
    {  6, 0,  8294, {  0x2902,     0x0 } }, // nvlArr
    {  5, 1,  8300, {    0xc5,     0x0 } }, // Aring
    {  6, 0,  8305, {  0x2283,     0x0 } }, // supset
    {  8, 1,  8311, {  0x24c8,     0x0 } }, // circledS
    {  3, 0,  8319, {  0x2a88,     0x0 } }, // gne
    { 17, 1,  8322, {  0x2956,     0x0 } }, // DownLeftVectorBar
    {  3, 0,  8339, {   0x412,     0x0 } }, // Vcy
    {  6, 0,  8342, {  0x2035,     0x0 } }, // bprime
    {  3, 0,  8348, { 0x1d51b,     0x0 } }, // Xfr
    {  3, 1,  8351, {   0x419,     0x0 } }, // Jcy
    {  5, 0,  8354, {    0xf3,     0x0 } }, // oacut
    {  2, 0,  8359, {    0xd0,     0x0 } }, // ET
    {  3, 1,  8361, {   0x411,     0x0 } }, // Bcy
    {  9, 0,  8364, {  0x226d,     0x0 } }, // NotCupCap
    {  8, 0,  8373, {  0x2124,     0x0 } }, // integers
    {  6, 0,  8381, {  0x2a37,     0x0 } }, // Otimes
    { 18, 0,  8387, {  0x25b8,     0x0 } }, // blacktriangleright
    {  8, 0,  8405, {  0x2a23,     0x0 } }, // plusacir
    {  5, 0,  8413, {  0x222d,     0x0 } }, // iiint
    { 17, 1,  8418, {  0x25fc,     0x0 } }, // FilledSmallSquare
    {  6, 0,  8435, {  0x2af0,     0x0 } }, // midcir
    {  6, 0,  8441, {  0x2009,     0x0 } }, // thinsp
    {  3, 1,  8447, { 0x1d508,     0x0 } }, // Efr
    { 13, 1,  8450, {  0x27f8,     0x0 } }, // Longleftarrow
    {  6, 0,  8463, {  0x2244,     0x0 } }, // nsimeq
    {  6, 1,  8469, {  0x2919,     0x0 } }, // latail
    {  6, 0,  8475, {  0x2a01,     0x0 } }, // xoplus
    { 14, 0,  8481, {  0x200b,     0x0 } }, // ZeroWidthSpace
    {  8, 1,  8495, {  0x2a0d,     0x0 } }, // fpartint
    {  4, 0,  8503, {  0x23b4,     0x0 } }, // tbrk
    { 12, 1,  8507, {  0x21a7,     0x0 } }, // DownTeeArrow
    {  5, 0,  8519, {  0x2a66,     0x0 } }, // sdote
    {  3, 1,  8524, {   0x41e,     0x0 } }, // Ocy
    {  1, 0,  8527, {    0x3e,     0x0 } }, // g
    { 17, 0,  8528, {  0x220c,     0x0 } }, // NotReverseElement
    {  3, 0,  8545, {   0x413,     0x0 } }, // Gcy
    {  5, 0,  8548, {   0x125,     0x0 } }, // hcirc
    {  6, 0,  8553, {    0x40,     0x0 } }, // commat
    {  5, 0,  8559, {  0x2205,     0x0 } }, // empty
    {  4, 1,  8564, {  0x223d,   0x331 } }, // race
    {  6, 0,  8568, {  0x2a6a,     0x0 } }, // simdot
    {  5, 0,  8574, {  0x2985,     0x0 } }, // lopar
    {  4, 0,  8579, {  0x2208,     0x0 } }, // isin
    {  5, 1,  8583, {  0x219b,     0x0 } }, // nrarr
    {  4, 1,  8588, {  0x22c5,     0x0 } }, // sdot
    {  6, 0,  8592, {   0x3c2,     0x0 } }, // sigmav
    { 19, 0,  8598, {  0x21c4,     0x0 } }, // RightArrowLeftArrow
    {  5, 0,  8617, {  0x229e,     0x0 } }, // plusb
    {  5, 0,  8622, {  0x22a9,     0x0 } }, // Vdash
    {  4, 0,  8627, { 0x1d54a,     0x0 } }, // Sopf
    {  6, 0,  8631, {   0x102,     0x0 } }, // Abreve
    {  5, 0,  8637, {  0x250c,     0x0 } }, // boxdr
    { 17, 0,  8642, {  0x27e6,     0x0 } }, // LeftDoubleBracket
    {  2, 0,  8659, {  0x2111,     0x0 } }, // Im
    {  6, 0,  8661, {  0x2155,     0x0 } }, // frac15
    {  4, 1,  8667, {  0x2aad,     0x0 } }, // late
    {  5, 1,  8671, {  0x2a79,     0x0 } }, // ltcir
    {  3, 0,  8676, {   0x3c6,     0x0 } }, // phi
    {  3, 1,  8679, {  0x2a86,     0x0 } }, // gap
    {  6, 1,  8682, {  0x25ae,     0x0 } }, // marker
    {  7, 0,  8688, {  0x2920,     0x0 } }, // rarrbfs
    { 13, 0,  8695, {  0x200a,     0x0 } }, // VeryThinSpace
    {  5, 0,  8708, {    0xf1,     0x0 } }, // ntild
    {  6, 0,  8713, {  0x2a47,     0x0 } }, // capcup
    {  6, 0,  8719, {  0x215a,     0x0 } }, // frac56
    {  6, 0,  8725, {    0x7d,     0x0 } }, // rbrace
    {  6, 0,  8731, {   0x157,     0x0 } }, // rcedil
    { 13, 0,  8737, {  0x2acb,  0xfe00 } }, // varsubsetneqq
    {  5, 1,  8750, {  0x2569,     0x0 } }, // boxHU
    {  5, 0,  8755, {   0x2dd,     0x0 } }, // dblac
    {  3, 1,  8760, {  0x22d3,     0x0 } }, // Cup
    {  3, 1,  8763, {    0xb0,     0x0 } }, // deg
    {  6, 0,  8766, {  0x296d,     0x0 } }, // lrhard
    {  4, 1,  8772, {  0x29a4,     0x0 } }, // ange
    {  5, 0,  8776, {  0x2207,     0x0 } }, // nabla
    { 21, 0,  8781, {  0x200b,     0x0 } }, // NegativeVeryThinSpace
    {  4, 0,  8802, { 0x1d54f,     0x0 } }, // Xopf
    {  7, 0,  8806, {  0x2134,     0x0 } }, // orderof
    {  4, 0,  8813, {  0x2a73,     0x0 } }, // Esim
    {  4, 1,  8817, {    0xe6,     0x0 } }, // aeli
    {  5, 0,  8821, {    0xb5,     0x0 } }, // micro
    {  5, 0,  8826, {  0x2986,     0x0 } }, // ropar
    {  5, 1,  8831, {  0x21c1,     0x0 } }, // rhard
    {  6, 0,  8836, {  0x2293,  0xfe00 } }, // sqcaps
    {  6, 1,  8842, {    0xf3,     0x0 } }, // oacute
    {  4, 0,  8848, {  0x2a9d,     0x0 } }, // siml
    {  5, 1,  8852, {   0x40b,     0x0 } }, // TSHcy
    {  7, 0,  8857, {  0x293d,     0x0 } }, // cularrp
    {  3, 0,  8864, {   0x43a,     0x0 } }, // kcy
    {  6, 1,  8867, {   0x15e,     0x0 } }, // Scedil
    {  5, 0,  8873, {  0x2122,     0x0 } }, // TRADE
    {  5, 0,  8878, {  0x22ab,     0x0 } }, // VDash
    {  9, 1,  8883, {  0x22cd,     0x0 } }, // backsimeq
    {  7, 1,  8892, {  0x2021,     0x0 } }, // ddagger
    {  3, 0,  8899, {  0x200f,     0x0 } }, // rlm
    { 18, 1,  8902, {  0x2957,     0x0 } }, // DownRightVectorBar
    { 14, 1,  8920, {  0x2500,     0x0 } }, // HorizontalLine
    {  7, 1,  8934, {  0x298d,     0x0 } }, // lbrkslu
    {  7, 1,  8941, {  0x2aaf,   0x338 } }, // npreceq
    {  6, 0,  8948, {   0x17a,     0x0 } }, // zacute
    { 16, 0,  8954, {  0x29d0,     0x0 } }, // RightTriangleBar
    {  6, 1,  8970, {  0x290d,     0x0 } }, // bkarow
    { 11, 0,  8976, {  0x229a,     0x0 } }, // circledcirc
    { 14, 1,  8987, {   0x2d9,     0x0 } }, // DiacriticalDot
    {  4, 0,  9001, { 0x1d4c0,     0x0 } }, // kscr
    {  8, 0,  9005, {  0x227a,     0x0 } }, // Precedes
    {  3, 0,  9013, {  0x22d1,     0x0 } }, // Sup
    {  5, 0,  9016, {  0x2253,     0x0 } }, // erDot
    {  6, 0,  9021, {  0x2255,     0x0 } }, // ecolon
    {  4, 0,  9027, {  0x2119,     0x0 } }, // Popf
    {  6, 0,  9031, {  0x22c9,     0x0 } }, // ltimes
    {  8, 1,  9037, {    0x5f,     0x0 } }, // UnderBar
    {  5, 0,  9045, {   0x3b3,     0x0 } }, // gamma
    {  9, 0,  9050, {  0x20db,     0x0 } }, // TripleDot
    {  6, 0,  9059, {  0x223c,     0x0 } }, // thksim
    {  4, 1,  9065, { 0x1d4bf,     0x0 } }, // jscr
    {  4, 0,  9069, {  0x200c,     0x0 } }, // zwnj
    { 10, 0,  9073, {  0x21d2,     0x0 } }, // Rightarrow
    {  3, 0,  9083, {    0xa8,     0x0 } }, // Dot
    {  4, 0,  9086, {  0x2aa6,     0x0 } }, // ltcc
    {  4, 1,  9090, {   0x451,     0x0 } }, // iocy
    {  4, 0,  9094, {   0x44f,     0x0 } }, // yacy
    {  2, 0,  9098, {  0x2a9a,     0x0 } }, // eg
    {  3, 1,  9100, {    0xa9,     0x0 } }, // COP
    {  7, 1,  9103, {  0x2948,     0x0 } }, // harrcir
    {  6, 0,  9110, {    0x2a,     0x0 } }, // midast
    { 16, 1,  9116, {   0x2dc,     0x0 } }, // DiacriticalTilde
    {  6, 1,  9132, {  0x2203,     0x0 } }, // Exists
    {  7, 0,  9138, {  0x2261,  0x20e5 } }, // bnequiv
    { 14, 1,  9145, {  0x2224,     0x0 } }, // NotVerticalBar
    {  5, 0,  9159, {  0x2198,     0x0 } }, // searr
    {  6, 1,  9164, {  0x2008,     0x0 } }, // puncsp
    {  7, 0,  9170, {  0x211b,     0x0 } }, // realine
    {  8, 1,  9177, {  0x231e,     0x0 } }, // llcorner
    {  5, 0,  9185, {  0x27f8,     0x0 } }, // xlArr
    {  8, 0,  9190, {  0x2238,     0x0 } }, // dotminus
    {  3, 0,  9198, { 0x1d52c,     0x0 } }, // ofr
    {  8, 0,  9201, {  0x29ae,     0x0 } }, // angmsdag
    {  8, 0,  9209, {  0x2910,     0x0 } }, // drbkarow
    {  5, 0,  9217, {  0x29cd,     0x0 } }, // trisb
    {  4, 0,  9222, {    0xc6,     0x0 } }, // AEli
    {  4, 1,  9226, {   0x130,     0x0 } }, // Idot
    {  4, 0,  9230, {  0x226f,     0x0 } }, // ngtr
    { 11, 1,  9234, {  0x29f4,     0x0 } }, // RuleDelayed
    {  6, 1,  9245, {    0x5b,     0x0 } }, // lbrack
    {  6, 0,  9251, {  0x27e9,     0x0 } }, // rangle
    {  6, 0,  9257, {  0x296b,     0x0 } }, // llhard
    {  8, 0,  9263, {  0x2283,     0x0 } }, // Superset
    {  5, 1,  9271, {  0x2ad9,     0x0 } }, // forkv
    {  3, 0,  9276, {  0x2a7e,     0x0 } }, // ges
    { 14, 0,  9279, {  0x22b4,     0x0 } }, // trianglelefteq
    {  3, 1,  9293, {  0x2280,     0x0 } }, // npr
    {  7, 0,  9296, {  0x227e,     0x0 } }, // precsim
    {  4, 0,  9303, { 0x1d4cc,     0x0 } }, // wscr
    {  5, 1,  9307, {    0xee,     0x0 } }, // icirc
    {  4, 0,  9312, {  0x2ac6,     0x0 } }, // supE
    { 23, 0,  9316, {  0x2aa2,   0x338 } }, // NotNestedGreaterGreater
    {  5, 1,  9339, {  0x2553,     0x0 } }, // boxDr
    { 16, 1,  9344, {  0x21c2,     0x0 } }, // downharpoonright
    {  8, 0,  9360, {  0x228f,     0x0 } }, // sqsubset
    {  3, 0,  9368, { 0x1d536,     0x0 } }, // yfr
    {  5, 1,  9371, {    0xc3,     0x0 } }, // Atild
    {  3, 0,  9376, {  0x22d0,     0x0 } }, // Sub
    {  7, 0,  9379, {  0x2990,     0x0 } }, // rbrkslu
    {  8, 1,  9386, {  0x29b4,     0x0 } }, // laemptyv
    {  3, 1,  9394, {  0x2267,   0x338 } }, // ngE
    {  4, 0,  9397, { 0x1d4c3,     0x0 } }, // nscr
    {  4, 1,  9401, { 0x1d4a2,     0x0 } }, // Gscr
    { 13, 1,  9405, {  0x21e5,     0x0 } }, // RightArrowBar
    {  5, 0,  9418, {    0xb8,     0x0 } }, // cedil
    {  5, 1,  9423, {  0x22c3,     0x0 } }, // Union
    { 15, 0,  9428, {  0x21ba,     0x0 } }, // circlearrowleft
    {  2, 0,  9443, {    0x3e,     0x0 } }, // GT
    {  6, 1,  9445, {  0x2016,     0x0 } }, // Verbar
    {  8, 1,  9451, {  0x29af,     0x0 } }, // angmsdah
    {  6, 0,  9459, {  0x2204,     0x0 } }, // nexist
    {  6, 1,  9465, {  0x2a40,     0x0 } }, // capdot
    {  6, 0,  9471, {  0x2925,     0x0 } }, // searhk
    {  8, 0,  9477, {  0x2a3a,     0x0 } }, // triminus
    {  5, 0,  9485, {   0x104,     0x0 } }, // Aogon
    { 15, 0,  9490, {  0x25bd,     0x0 } }, // bigtriangledown
    {  4, 0,  9505, { 0x1d55d,     0x0 } }, // lopf
    {  6, 0,  9509, {   0x110,     0x0 } }, // Dstrok
    {  4, 0,  9515, {  0x221d,     0x0 } }, // prop
    {  5, 0,  9519, {  0x22b3,     0x0 } }, // vrtri
    {  7, 1,  9524, {  0x220c,     0x0 } }, // notniva
    {  8, 1,  9531, {  0x29b3,     0x0 } }, // raemptyv
    {  6, 0,  9539, {  0x2abd,     0x0 } }, // subdot
    {  6, 0,  9545, {    0xc8,     0x0 } }, // Egrave
    {  7, 0,  9551, {  0x2973,     0x0 } }, // larrsim
    { 12, 1,  9558, {  0x221d,     0x0 } }, // Proportional
    {  5, 1,  9570, {  0x21fd,     0x0 } }, // loarr
    {  4, 0,  9575, {  0x29eb,     0x0 } }, // lozf
    {  8, 0,  9579, {  0x22c0,     0x0 } }, // bigwedge
    {  5, 0,  9587, {  0x2a8f,     0x0 } }, // lsimg
    {  5, 0,  9592, {    0xd5,     0x0 } }, // Otild
    {  5, 1,  9597, {  0x2560,     0x0 } }, // boxVR
    {  4, 0,  9602, {    0x7c,     0x0 } }, // vert
    {  5, 0,  9606, {  0x2afd,     0x0 } }, // parsl
    { 11, 0,  9611, {   0x3f6,     0x0 } }, // backepsilon
    {  4, 0,  9622, {  0x2130,     0x0 } }, // Escr
    {  3, 1,  9626, { 0x1d51e,     0x0 } }, // afr
    {  7, 1,  9629, {  0x2235,     0x0 } }, // because
    {  4, 0,  9636, {   0x447,     0x0 } }, // chcy
    { 13, 1,  9640, {  0x2061,     0x0 } }, // ApplyFunction
    {  5, 0,  9653, {  0x21c6,     0x0 } }, // lrarr
    {  4, 0,  9658, {  0x2225,     0x0 } }, // spar
    {  7, 0,  9662, {  0x25ca,     0x0 } }, // lozenge
    { 14, 0,  9669, {  0x22cb,     0x0 } }, // leftthreetimes
    {  7, 0,  9683, {  0x2ab0,   0x338 } }, // nsucceq
    {  6, 1,  9690, {  0x2254,     0x0 } }, // Assign
    {  5, 0,  9696, {  0x2593,     0x0 } }, // blk34
    { 10, 1,  9701, {  0x2242,     0x0 } }, // EqualTilde
    {  5, 1,  9711, {   0x3a9,     0x0 } }, // Omega
    { 14, 1,  9716, {  0x21ca,     0x0 } }, // downdownarrows
    {  4, 0,  9730, { 0x1d55b,     0x0 } }, // jopf
    {  6, 1,  9734, {  0x2a25,     0x0 } }, // plusdu
    {  4, 0,  9740, {   0x448,     0x0 } }, // shcy
    {  5, 1,  9744, {    0xc5,     0x0 } }, // angst
    {  4, 0,  9749, {  0x224d,  0x20d2 } }, // nvap
    {  9, 0,  9753, {  0x2261,     0x0 } }, // Congruent
    {  5, 0,  9762, {  0x22f0,     0x0 } }, // utdot
    {  3, 1,  9767, {  0x22d9,     0x0 } }, // ggg
    { 11, 0,  9770, {  0x21cf,     0x0 } }, // nRightarrow
    {  5, 0,  9781, {  0x29b9,     0x0 } }, // operp
    {  6, 1,  9786, {   0x142,     0x0 } }, // lstrok
    {  3, 0,  9792, { 0x1d52b,     0x0 } }, // nfr
    {  5, 0,  9795, {  0x21f5,     0x0 } }, // duarr
    { 16, 1,  9800, {  0x2aaf,   0x338 } }, // NotPrecedesEqual
    {  4, 0,  9816, {  0x22c4,     0x0 } }, // diam
    {  6, 1,  9820, {   0x11b,     0x0 } }, // ecaron
    {  5, 0,  9826, {  0x2a90,     0x0 } }, // gsiml
    { 19, 0,  9831, {  0x21ad,     0x0 } }, // leftrightsquigarrow
    { 16, 1,  9850, {    0xa0,     0x0 } }, // NonBreakingSpace
    {  6, 1,  9866, {  0x230a,     0x0 } }, // lfloor
    {  6, 0,  9872, {  0x296c,     0x0 } }, // rharul
    {  4, 0,  9878, {  0x2aaf,   0x338 } }, // npre
    {  9, 0,  9882, {  0x22a1,     0x0 } }, // dotsquare
    {  4, 0,  9891, { 0x1d53d,     0x0 } }, // Fopf
    {  3, 0,  9895, {   0x441,     0x0 } }, // scy
    {  6, 0,  9898, {   0x408,     0x0 } }, // Jsercy
    {  5, 1,  9904, {   0x12f,     0x0 } }, // iogon
    {  4, 0,  9909, {  0x2241,     0x0 } }, // nsim
    { 14, 1,  9913, {  0x27f9,     0x0 } }, // Longrightarrow
    {  5, 0,  9927, {    0x66,    0x6a } }, // fjlig
    { 10, 0,  9932, {  0x2ac6,   0x338 } }, // nsupseteqq
    {  4, 0,  9942, {  0x226a,   0x338 } }, // nLtv
    {  5, 0,  9946, {   0x109,     0x0 } }, // ccirc
    { 19, 1,  9951, {  0x2267,   0x338 } }, // NotGreaterFullEqual
    {  5, 1,  9970, {   0x16a,     0x0 } }, // Umacr
    {  6, 1,  9975, {    0x24,     0x0 } }, // dollar
    {  6, 0,  9981, {  0x22ac,     0x0 } }, // nvdash
    { 19, 0,  9987, {  0x2292,     0x0 } }, // SquareSupersetEqual
    { 21, 0, 10006, {  0x22e0,     0x0 } }, // NotPrecedesSlantEqual
    {  8, 1, 10027, {  0x2aa1,     0x0 } }, // LessLess
    {  5, 0, 10035, {  0x233d,     0x0 } }, // ovbar
    {  6, 0, 10040, {  0x2ac7,     0x0 } }, // subsim
    {  5, 1, 10046, {    0xec,     0x0 } }, // igrav
    {  4, 0, 10051, {  0x2936,     0x0 } }, // ldca
    {  5, 0, 10055, {   0x404,     0x0 } }, // Jukcy
    {  3, 1, 10060, {   0x3a7,     0x0 } }, // Chi
    {  3, 1, 10063, {  0x21b1,     0x0 } }, // Rsh
    {  8, 0, 10066, {  0x2286,     0x0 } }, // subseteq
    {  5, 1, 10074, {  0x256b,     0x0 } }, // boxVh
    {  5, 1, 10079, {  0x2242,     0x0 } }, // eqsim
    {  5, 1, 10084, {    0x60,     0x0 } }, // grave
    {  5, 0, 10089, {    0xbb,     0x0 } }, // raquo
    {  6, 0, 10094, {    0xfd,     0x0 } }, // yacute
    {  2, 1, 10100, {  0x22d9,     0x0 } }, // Gg
    {  5, 0, 10102, {   0x131,     0x0 } }, // imath
    { 17, 1, 10107, {  0x200b,     0x0 } }, // NegativeThinSpace
    {  6, 0, 10124, {  0x2254,     0x0 } }, // colone
    {  6, 0, 10130, {  0x215b,     0x0 } }, // frac18
    {  6, 0, 10136, {  0x291e,     0x0 } }, // rarrfs
    { 16, 1, 10142, {  0x2267,     0x0 } }, // GreaterFullEqual
    {  9, 1, 10158, {  0x2272,     0x0 } }, // LessTilde
    { 11, 1, 10167, {  0x21db,     0x0 } }, // Rrightarrow
    {  4, 0, 10178, {  0x2ab8,     0x0 } }, // scap
    {  4, 1, 10182, {    0xce,     0x0 } }, // Icir
    {  5, 0, 10186, {    0xf9,     0x0 } }, // ugrav
    {  8, 0, 10191, {  0x2a01,     0x0 } }, // bigoplus
    {  5, 1, 10199, {  0x2a75,     0x0 } }, // Equal
    {  6, 0, 10204, {  0x2993,     0x0 } }, // lparlt
    { 12, 0, 10210, {  0x2913,     0x0 } }, // DownArrowBar
    {  3, 0, 10222, { 0x1d537,     0x0 } }, // zfr
    {  6, 0, 10225, {    0xf8,     0x0 } }, // oslash
    { 12, 1, 10231, {  0x2970,     0x0 } }, // RoundImplies
    {  6, 1, 10243, {   0x429,     0x0 } }, // SHCHcy
    {  6, 1, 10249, {  0x2ae6,     0x0 } }, // Vdashl
    {  5, 0, 10255, {  0x251c,     0x0 } }, // boxvr
    { 12, 1, 10260, {  0x228f,     0x0 } }, // SquareSubset
    {  5, 0, 10272, {  0x2290,     0x0 } }, // sqsup
    {  4, 1, 10277, {   0x403,     0x0 } }, // GJcy
    {  9, 1, 10281, {  0x2282,  0x20d2 } }, // NotSubset
    {  4, 0, 10290, {  0x2278,     0x0 } }, // ntlg
    { 16, 1, 10294, {  0x25fb,     0x0 } }, // EmptySmallSquare
    {  5, 0, 10310, {  0x2250,     0x0 } }, // esdot
    {  5, 0, 10315, {  0x227c,     0x0 } }, // prcue
    {  5, 0, 10320, {  0x2a7a,     0x0 } }, // gtcir
    {  5, 0, 10325, {   0x3d2,     0x0 } }, // upsih
    {  6, 0, 10330, {  0x2273,     0x0 } }, // gtrsim
    {  8, 0, 10336, {  0x22e8,     0x0 } }, // precnsim
    {  4, 1, 10344, {  0x2251,     0x0 } }, // eDot
    {  6, 0, 10348, {  0x2abe,     0x0 } }, // supdot
    {  6, 1, 10354, {  0x21b7,     0x0 } }, // curarr
    {  6, 0, 10360, {  0x2322,     0x0 } }, // sfrown
    {  3, 0, 10366, {    0x22,     0x0 } }, // quo
    {  8, 1, 10369, {  0x2926,     0x0 } }, // hkswarow
    {  3, 0, 10377, {    0xfc,     0x0 } }, // uum
    {  2, 1, 10380, {  0x211c,     0x0 } }, // Re
    {  8, 0, 10382, {  0x294b,     0x0 } }, // ldrushar
    {  3, 1, 10390, {  0x222c,     0x0 } }, // Int
    {  6, 0, 10393, {  0x224f,   0x338 } }, // nbumpe
    {  6, 0, 10399, {    0xe3,     0x0 } }, // atilde
    {  8, 0, 10405, {  0x2a04,     0x0 } }, // biguplus
    { 13, 1, 10413, {  0x2ab0,     0x0 } }, // SucceedsEqual
    {  4, 0, 10426, {    0xf6,     0x0 } }, // ouml
    {  4, 0, 10430, {   0x116,     0x0 } }, // Edot
    {  5, 0, 10434, {  0x2534,     0x0 } }, // boxhu
    { 11, 0, 10439, {  0x25aa,     0x0 } }, // blacksquare
    {  3, 1, 10450, {   0x438,     0x0 } }, // icy
    {  3, 1, 10453, { 0x1d52d,     0x0 } }, // pfr
    {  5, 1, 10456, {  0x211d,     0x0 } }, // reals
    { 10, 0, 10461, {  0x2acc,     0x0 } }, // supsetneqq
    {  9, 0, 10471, {  0x2a86,     0x0 } }, // gtrapprox
    {  6, 0, 10480, {  0x2acb,  0xfe00 } }, // vsubnE
    {  4, 0, 10486, {    0xa1,     0x0 } }, // iexc
    {  6, 0, 10490, {  0x2234,     0x0 } }, // there4
    {  5, 0, 10496, {  0x2261,     0x0 } }, // equiv
    { 17, 1, 10501, {  0x2225,     0x0 } }, // DoubleVerticalBar
    { 14, 0, 10518, {  0x21a3,     0x0 } }, // rightarrowtail
    { 11, 1, 10532, {  0x2281,     0x0 } }, // NotSucceeds
    {  6, 1, 10543, {  0x25ec,     0x0 } }, // tridot
    {  3, 0, 10549, {  0x200d,     0x0 } }, // zwj
    {  4, 0, 10552, {  0x2245,     0x0 } }, // cong
    {  7, 0, 10556, {  0x2191,     0x0 } }, // UpArrow
    {  6, 1, 10563, {   0x10e,     0x0 } }, // Dcaron
    {  5, 1, 10569, {   0x172,     0x0 } }, // Uogon
    {  5, 1, 10574, {  0x224f,     0x0 } }, // bumpe
    {  4, 0, 10579, { 0x1d55a,     0x0 } }, // iopf
    {  5, 0, 10583, {  0x22b5,     0x0 } }, // rtrie
    {  3, 1, 10588, { 0x1d509,     0x0 } }, // Ffr
    {  4, 0, 10591, {  0x2022,     0x0 } }, // bull
    {  8, 1, 10595, {  0x2663,     0x0 } }, // clubsuit
    { 13, 1, 10603, {  0x21a9,     0x0 } }, // hookleftarrow
    { 13, 1, 10616, {  0x21ab,     0x0 } }, // looparrowleft
    {  8, 0, 10629, {  0x223c,     0x0 } }, // thicksim
    {  5, 0, 10637, {    0xde,     0x0 } }, // THORN
    {  5, 1, 10642, {  0xfb01,     0x0 } }, // filig
    {  4, 0, 10647, {  0x25b5,     0x0 } }, // utri
    {  6, 1, 10651, {  0x22d1,     0x0 } }, // Supset
    {  5, 0, 10657, {  0x256a,     0x0 } }, // boxvH
    {  5, 0, 10662, {    0xf7,     0x0 } }, // divid
    {  6, 0, 10667, {  0x2282,     0x0 } }, // subset
    { 19, 0, 10673, {  0x21c6,     0x0 } }, // LeftArrowRightArrow
    {  5, 1, 10692, {  0x25c2,     0x0 } }, // ltrif
    {  7, 0, 10697, {  0x2249,     0x0 } }, // napprox
    {  5, 1, 10704, {  0x21ca,     0x0 } }, // ddarr
    { 16, 0, 10709, {  0x22ed,     0x0 } }, // ntrianglerighteq
    {  5, 1, 10725, {   0x3b1,     0x0 } }, // alpha
    {  5, 0, 10730, {  0x25bd,     0x0 } }, // xdtri
    { 11, 0, 10735, {  0x22df,     0x0 } }, // curlyeqsucc
    {  5, 1, 10746, {    0xe5,     0x0 } }, // aring
    {  3, 0, 10751, {  0x2269,     0x0 } }, // gnE
    { 15, 0, 10754, {  0x2197,     0x0 } }, // UpperRightArrow
    {  5, 0, 10769, {   0x105,     0x0 } }, // aogon
    {  8, 1, 10774, {  0x29e5,     0x0 } }, // eqvparsl
    {  9, 1, 10782, {  0x2190,     0x0 } }, // leftarrow
    {  5, 0, 10791, {  0x21bc,     0x0 } }, // lharu
    {  3, 0, 10796, {    0x3d,  0x20e5 } }, // bne
    {  5, 0, 10799, {  0x22ea,     0x0 } }, // nltri
    { 16, 1, 10804, {    0xb4,     0x0 } }, // DiacriticalAcute
    {  4, 1, 10820, {  0x2271,     0x0 } }, // ngeq
    {  7, 0, 10824, {  0x27c9,     0x0 } }, // suphsol
    {  4, 1, 10831, {   0x426,     0x0 } }, // TScy
    {  5, 1, 10835, {  0x201a,     0x0 } }, // sbquo
    {  8, 0, 10840, {  0x2287,     0x0 } }, // supseteq
    {  3, 0, 10848, {   0x420,     0x0 } }, // Rcy
    {  6, 0, 10851, {  0x22ed,     0x0 } }, // nrtrie
    {  4, 0, 10857, {  0x211b,     0x0 } }, // Rscr
    {  4, 0, 10861, {    0xdc,     0x0 } }, // Uuml
    {  5, 1, 10865, {  0x22eb,     0x0 } }, // nrtri
    { 10, 0, 10870, {  0x2205,     0x0 } }, // varnothing
    { 20, 1, 10880, {  0x27f9,     0x0 } }, // DoubleLongRightArrow
    {  6, 0, 10900, {  0x210f,     0x0 } }, // planck
    {  4, 1, 10906, {  0x210d,     0x0 } }, // Hopf
    {  6, 0, 10910, {   0x127,     0x0 } }, // hstrok
    { 10, 0, 10916, {  0x21bc,     0x0 } }, // LeftVector
    {  2, 1, 10926, {  0x226b,     0x0 } }, // gg
    {  6, 0, 10928, {   0x3f0,     0x0 } }, // kappav
    {  2, 1, 10934, {    0x26,     0x0 } }, // AM
    {  5, 0, 10936, {    0xd3,     0x0 } }, // Oacut
    {  5, 0, 10941, {  0x27f7,     0x0 } }, // xharr
    {  3, 1, 10946, { 0x1d518,     0x0 } }, // Ufr
    {  3, 0, 10949, { 0x1d528,     0x0 } }, // kfr
    {  6, 0, 10952, {  0x2994,     0x0 } }, // rpargt
    { 15, 0, 10958, {  0x22b2,     0x0 } }, // vartriangleleft
    {  8, 0, 10973, {  0x2223,     0x0 } }, // shortmid
    {  7, 0, 10981, {  0x22a3,     0x0 } }, // LeftTee
    { 15, 1, 10988, {  0x294e,     0x0 } }, // LeftRightVector
    {  6, 0, 11003, {   0x143,     0x0 } }, // Nacute
    {  5, 0, 11009, {    0xc8,     0x0 } }, // Egrav
    {  5, 0, 11014, {  0x2309,     0x0 } }, // rceil
    {  4, 1, 11019, {   0x415,     0x0 } }, // IEcy
    { 13, 1, 11023, {  0x25b3,     0x0 } }, // bigtriangleup
    {  6, 0, 11036, {  0x2996,     0x0 } }, // ltrPar
    {  6, 1, 11042, {  0x29e3,     0x0 } }, // eparsl
    {  3, 0, 11048, {    0xae,     0x0 } }, // reg
    { 18, 0, 11051, {  0x27e7,     0x0 } }, // RightDoubleBracket
    {  4, 0, 11069, { 0x1d4cb,     0x0 } }, // vscr
    {  4, 1, 11073, {    0xde,     0x0 } }, // THOR
    {  2, 0, 11077, {  0x2a99,     0x0 } }, // el
    {  5, 0, 11079, {  0x2269,     0x0 } }, // gneqq
    {  8, 1, 11084, {  0x2a7e,     0x0 } }, // geqslant
    {  6, 0, 11092, {  0x2acc,  0xfe00 } }, // vsupnE
    { 15, 1, 11098, {  0x228f,   0x338 } }, // NotSquareSubset
    {  6, 1, 11113, {   0x168,     0x0 } }, // Utilde
    {  4, 0, 11119, { 0x1d4b5,     0x0 } }, // Zscr
    {  7, 0, 11123, {  0x2966,     0x0 } }, // luruhar
    {  2, 1, 11130, {  0x2277,     0x0 } }, // gl
    {  6, 0, 11132, {  0x2216,     0x0 } }, // ssetmn
    {  6, 0, 11138, {   0x42a,     0x0 } }, // HARDcy
    {  4, 0, 11144, { 0x1d49c,     0x0 } }, // Ascr
    {  4, 1, 11148, {    0x5c,     0x0 } }, // bsol
    {  6, 1, 11152, {  0x22e0,     0x0 } }, // nprcue
    {  6, 0, 11158, {    0x25,     0x0 } }, // percnt
    {  8, 0, 11164, {  0x2290,     0x0 } }, // sqsupset
    {  4, 0, 11172, { 0x1d4ca,     0x0 } }, // uscr
    {  5, 1, 11176, {  0x2552,     0x0 } }, // boxdR
    { 10, 0, 11181, {  0x229b,     0x0 } }, // circledast
    { 16, 1, 11191, {  0x2289,     0x0 } }, // NotSupersetEqual
    { 12, 0, 11207, {  0x228a,  0xfe00 } }, // varsubsetneq
    {  2, 0, 11219, {    0xae,     0x0 } }, // re
    {  7, 0, 11221, {  0x2ac0,     0x0 } }, // supplus
    {  3, 1, 11228, {  0x2aec,     0x0 } }, // Not
    {  4, 0, 11231, {  0x2025,     0x0 } }, // nldr
    {  5, 1, 11235, {  0x22c0,     0x0 } }, // Wedge
    {  4, 1, 11240, {    0xb4,     0x0 } }, // acut
    {  5, 0, 11244, {    0xbe,     0x0 } }, // frac3
    {  4, 1, 11249, { 0x1d4c7,     0x0 } }, // rscr
    {  8, 1, 11253, {  0x2216,     0x0 } }, // setminus
    {  9, 0, 11261, {  0x2ac6,     0x0 } }, // supseteqq
    {  6, 0, 11270, {    0xe1,     0x0 } }, // aacute
    {  5, 0, 11276, {  0x2275,     0x0 } }, // ngsim
    {  5, 0, 11281, {  0x29a5,     0x0 } }, // range
    {  4, 1, 11286, { 0x1d4b4,     0x0 } }, // Yscr
    {  5, 0, 11290, {  0x25fa,     0x0 } }, // lltri
    {  4, 1, 11295, {    0x22,     0x0 } }, // quot
    { 13, 0, 11299, {  0x2216,     0x0 } }, // smallsetminus
    {  4, 1, 11312, {  0x212c,     0x0 } }, // Bscr
    {  4, 1, 11316, {   0x121,     0x0 } }, // gdot
    {  7, 0, 11320, {  0x2a81,     0x0 } }, // lesdoto
    {  5, 0, 11327, {  0x2567,     0x0 } }, // boxHu
    {  6, 0, 11332, {  0x22ee,     0x0 } }, // vellip
    {  5, 1, 11338, {   0x12b,     0x0 } }, // imacr
    {  5, 0, 11343, {  0x2a3c,     0x0 } }, // iprod
    {  3, 1, 11348, { 0x1d50d,     0x0 } }, // Jfr
    {  5, 1, 11351, {   0x119,     0x0 } }, // eogon
    {  6, 0, 11356, {  0x291b,     0x0 } }, // lAtail
    {  3, 0, 11362, {  0x2aa4,     0x0 } }, // glj
    {  5, 1, 11365, {    0xe0,     0x0 } }, // agrav
    {  5, 1, 11370, {  0x2220,     0x0 } }, // angle
    {  6, 0, 11375, {    0xa6,     0x0 } }, // brvbar
    {  6, 0, 11381, {  0x2057,     0x0 } }, // qprime
    {  7, 0, 11387, {  0x2230,     0x0 } }, // Cconint
    {  6, 1, 11394, {  0x22d7,     0x0 } }, // gtrdot
    {  6, 0, 11400, {  0x291c,     0x0 } }, // rAtail
    {  5, 0, 11406, {   0x124,     0x0 } }, // Hcirc
    { 10, 0, 11411, {  0x2112,     0x0 } }, // Laplacetrf
    {  5, 0, 11421, {  0x22de,     0x0 } }, // cuepr
    { 10, 0, 11426, {  0x2148,     0x0 } }, // ImaginaryI
    {  4, 1, 11436, {    0xe2,     0x0 } }, // acir
    {  7, 0, 11440, {  0x266e,     0x0 } }, // natural
    {  9, 0, 11447, {  0x2226,     0x0 } }, // nparallel
    {  5, 1, 11456, {   0x14d,     0x0 } }, // omacr
    {  2, 0, 11461, {    0xa8,     0x0 } }, // um
    { 12, 1, 11463, {  0x224e,     0x0 } }, // HumpDownHump
    {  7, 0, 11475, {  0x2ada,     0x0 } }, // topfork
    {  3, 0, 11482, {    0xaf,     0x0 } }, // mac
    {  7, 1, 11485, {  0x2208,     0x0 } }, // Element
    {  8, 0, 11492, {  0x22a0,     0x0 } }, // boxtimes
    {  4, 0, 11500, {    0xdb,     0x0 } }, // Ucir
    {  6, 1, 11504, {   0x1f5,     0x0 } }, // gacute
    {  5, 0, 11510, {  0x227e,     0x0 } }, // prsim
    {  9, 0, 11515, {  0x22da,     0x0 } }, // lesseqgtr
    {  7, 1, 11524, {  0x22c4,     0x0 } }, // Diamond
    { 20, 1, 11531, {  0x25ab,     0x0 } }, // EmptyVerySmallSquare
    {  5, 0, 11551, {   0x16f,     0x0 } }, // uring
    {  4, 0, 11556, { 0x1d53c,     0x0 } }, // Eopf
    {  9, 0, 11560, {  0x2269,  0xfe00 } }, // gvertneqq
    {  5, 0, 11569, {  0x2208,     0x0 } }, // isinv
    { 19, 1, 11574, {  0x200b,     0x0 } }, // NegativeMediumSpace
    { 12, 1, 11593, {  0x29eb,     0x0 } }, // blacklozenge
    {  5, 1, 11605, {  0x2423,     0x0 } }, // blank
    {  6, 0, 11610, {  0x21aa,     0x0 } }, // rarrhk
    {  4, 0, 11616, {  0x223d,     0x0 } }, // bsim
    { 17, 1, 11620, {  0x2a7e,     0x0 } }, // GreaterSlantEqual
    {  6, 0, 11637, {  0x2a55,     0x0 } }, // andand
    {  5, 0, 11643, {  0x227f,     0x0 } }, // scsim
    {  6, 1, 11648, {  0x2a29,     0x0 } }, // mcomma
    {  6, 0, 11654, {   0x3d5,     0x0 } }, // varphi
    {  4, 0, 11660, {    0xab,     0x0 } }, // laqu
    {  6, 1, 11664, {  0x2222,     0x0 } }, // angsph
    {  4, 0, 11670, {   0x457,     0x0 } }, // yicy
    {  6, 0, 11674, {   0x159,     0x0 } }, // rcaron
    { 11, 0, 11680, {  0x2195,     0x0 } }, // UpDownArrow
    {  9, 1, 11691, {   0x311,     0x0 } }, // DownBreve
    {  6, 0, 11700, {  0x2218,     0x0 } }, // compfn
    { 10, 0, 11706, {  0x2248,     0x0 } }, // TildeTilde
    {  4, 0, 11716, {  0x21a1,     0x0 } }, // Darr
    {  5, 1, 11720, {  0x2562,     0x0 } }, // boxVl
    {  7, 1, 11725, {  0x2255,     0x0 } }, // eqcolon
    {  4, 0, 11732, {  0x2a43,     0x0 } }, // ncap
    {  3, 0, 11736, {   0x434,     0x0 } }, // dcy
    {  8, 0, 11739, {    0xae,     0x0 } }, // circledR
    {  4, 0, 11747, {  0x2102,     0x0 } }, // Copf
    {  6, 0, 11751, {   0x11e,     0x0 } }, // Gbreve
    { 13, 1, 11757, {  0x2146,     0x0 } }, // DifferentialD
    {  6, 0, 11770, {  0x21a2,     0x0 } }, // larrtl
    {  6, 0, 11776, {  0x231d,     0x0 } }, // urcorn
    {  6, 0, 11782, {   0x136,     0x0 } }, // Kcedil
    {  6, 0, 11788, {  0x22c0,     0x0 } }, // xwedge
    {  5, 1, 11794, {   0x2c7,     0x0 } }, // Hacek
    { 12, 1, 11799, {  0x22b2,     0x0 } }, // LeftTriangle
    {  6, 0, 11811, {  0x2316,     0x0 } }, // target
    {  4, 1, 11817, {   0x2c6,     0x0 } }, // circ
    {  5, 0, 11821, {   0x173,     0x0 } }, // uogon
    {  6, 0, 11826, {  0x2259,     0x0 } }, // wedgeq
    {  6, 0, 11832, {    0xc1,     0x0 } }, // Aacute
    {  7, 0, 11838, {  0x212d,     0x0 } }, // Cayleys
    {  5, 1, 11845, {  0x2566,     0x0 } }, // boxHD
    {  4, 1, 11850, { 0x1d4bd,     0x0 } }, // hscr
    {  4, 0, 11854, {    0x7b,     0x0 } }, // lcub
    {  8, 0, 11858, {  0x2a8a,     0x0 } }, // gnapprox
    {  6, 0, 11866, {  0x296a,     0x0 } }, // lharul
    {  4, 0, 11872, {  0x22b7,     0x0 } }, // imof
    {  4, 1, 11876, { 0x1d4af,     0x0 } }, // Tscr
    { 10, 0, 11880, {  0x2a8b,     0x0 } }, // lesseqqgtr
    { 22, 1, 11890, {  0x22e3,     0x0 } }, // NotSquareSupersetEqual
    {  8, 0, 11912, {  0x227b,     0x0 } }, // Succeeds
    {  3, 1, 11920, { 0x1d50f,     0x0 } }, // Lfr
    {  3, 1, 11923, { 0x1d51f,     0x0 } }, // bfr
    {  7, 0, 11926, {  0x2209,     0x0 } }, // notinva
    {  6, 0, 11933, {  0x215e,     0x0 } }, // frac78
    {  5, 0, 11939, {    0xb7,     0x0 } }, // middo
    {  4, 0, 11944, {    0xee,     0x0 } }, // icir
    {  4, 0, 11948, {  0x2a7d,   0x338 } }, // nles
    { 12, 1, 11952, {  0x21e4,     0x0 } }, // LeftArrowBar
    {  6, 0, 11964, {  0x2323,     0x0 } }, // ssmile
    {  3, 0, 11970, {   0x44d,     0x0 } }, // ecy
    {  6, 0, 11973, {  0x2926,     0x0 } }, // swarhk
    {  5, 0, 11979, {  0x2ac5,   0x338 } }, // nsubE
    { 15, 1, 11984, {  0x21d3,     0x0 } }, // DoubleDownArrow
    {  6, 0, 11999, {  0x2a2e,     0x0 } }, // roplus
    {  5, 0, 12005, {  0x2991,     0x0 } }, // langd
    {  6, 1, 12010, {  0x20dc,     0x0 } }, // DotDot
    {  4, 0, 12016, {   0x459,     0x0 } }, // ljcy
    {  5, 0, 12020, {    0xb1,     0x0 } }, // plusm
    { 14, 1, 12025, {  0x2196,     0x0 } }, // UpperLeftArrow
    {  4, 0, 12039, {  0x2284,     0x0 } }, // nsub
    {  4, 0, 12043, {  0x21d5,     0x0 } }, // vArr
    {  5, 1, 12047, {    0xf8,     0x0 } }, // oslas
    {  6, 0, 12052, {    0xf5,     0x0 } }, // otilde
    {  5, 0, 12058, {  0x29c5,     0x0 } }, // bsolb
    {  6, 0, 12063, {  0x2a33,     0x0 } }, // smashp
    {  8, 0, 12069, {  0x229f,     0x0 } }, // boxminus
    { 15, 0, 12077, {  0x21c4,     0x0 } }, // rightleftarrows
    {  6, 0, 12092, {  0x2159,     0x0 } }, // frac16
    { 15, 1, 12098, {  0x21b7,     0x0 } }, // curvearrowright
    {  6, 0, 12113, {  0x215d,     0x0 } }, // frac58
    {  3, 0, 12119, {  0x223c,     0x0 } }, // sim
    {  6, 0, 12122, {  0x22ec,     0x0 } }, // nltrie
    {  3, 1, 12128, {  0x22d2,     0x0 } }, // Cap
    {  5, 0, 12131, {  0x2ac6,   0x338 } }, // nsupE
    {  6, 0, 12136, {   0x107,     0x0 } }, // cacute
    { 13, 0, 12142, {  0x227f,     0x0 } }, // SucceedsTilde
    {  3, 1, 12155, {    0xcb,     0x0 } }, // Eum
    { 13, 0, 12158, {  0x2221,     0x0 } }, // measuredangle
    {  5, 0, 12171, {  0x27f9,     0x0 } }, // xrArr
    {  6, 0, 12176, {    0xe9,     0x0 } }, // eacute
    {  4, 0, 12182, {   0x10b,     0x0 } }, // cdot
    {  5, 0, 12186, {  0x2561,     0x0 } }, // boxvL
    { 21, 0, 12191, {  0x222f,     0x0 } }, // DoubleContourIntegral
    {  4, 0, 12212, { 0x1d49f,     0x0 } }, // Dscr
    {  3, 1, 12216, { 0x1d51a,     0x0 } }, // Wfr
    {  4, 1, 12219, {    0xa2,     0x0 } }, // cent
    {  5, 1, 12223, {    0xbf,     0x0 } }, // iques
    {  6, 0, 12228, {  0x2a02,     0x0 } }, // xotime
    {  6, 0, 12234, {  0x2933,   0x338 } }, // nrarrc
    {  7, 0, 12240, {  0x2ac3,     0x0 } }, // subedot
    {  4, 0, 12247, { 0x1d54d,     0x0 } }, // Vopf
    { 10, 0, 12251, {   0x3f5,     0x0 } }, // varepsilon
    {  7, 0, 12261, {  0x297b,     0x0 } }, // suplarr
    { 14, 1, 12268, {  0x2226,     0x0 } }, // nshortparallel
    {  2, 0, 12282, {  0x2118,     0x0 } }, // wp
    {  4, 0, 12284, {   0x17b,     0x0 } }, // Zdot
    {  5, 0, 12288, {  0x2663,     0x0 } }, // clubs
    {  9, 1, 12293, {  0x22db,     0x0 } }, // gtreqless
    {  3, 0, 12302, {   0x43f,     0x0 } }, // pcy
    { 17, 1, 12305, {  0x2290,   0x338 } }, // NotSquareSuperset
    { 18, 1, 12322, {  0x2955,     0x0 } }, // RightDownVectorBar
    {  5, 0, 12340, {  0x2013,     0x0 } }, // ndash
    {  3, 0, 12345, {   0x397,     0x0 } }, // Eta
    {  4, 0, 12348, {  0x2224,     0x0 } }, // nmid
    {  4, 0, 12352, {  0x2299,     0x0 } }, // odot
    {  5, 1, 12356, {    0xc7,     0x0 } }, // Ccedi
    {  3, 1, 12361, {   0x43b,     0x0 } }, // lcy
    {  4, 0, 12364, { 0x1d4c6,     0x0 } }, // qscr
    {  5, 1, 12368, {   0x3f5,     0x0 } }, // epsiv
    {  5, 0, 12373, {  0x298b,     0x0 } }, // lbrke
    {  5, 1, 12378, {  0x256c,     0x0 } }, // boxVH
    {  3, 0, 12383, {  0x226f,     0x0 } }, // ngt
    {  5, 1, 12386, {  0x21ae,     0x0 } }, // nharr
    {  5, 0, 12391, {   0x3d6,     0x0 } }, // varpi
    {  4, 1, 12396, {    0xcb,     0x0 } }, // Euml
    {  6, 1, 12400, {   0x158,     0x0 } }, // Rcaron
    {  4, 1, 12406, {  0x2962,     0x0 } }, // lHar
    {  6, 0, 12410, {  0x2292,     0x0 } }, // sqsupe
    { 16, 1, 12416, {    0x60,     0x0 } }, // DiacriticalGrave
    {  6, 0, 12432, {  0x2a46,     0x0 } }, // cupcap
    {  6, 0, 12438, {  0x231c,     0x0 } }, // ulcorn
    {  4, 1, 12444, {  0x2131,     0x0 } }, // Fscr
    {  7, 0, 12448, {  0x226e,     0x0 } }, // NotLess
    {  7, 1, 12455, {   0x3dd,     0x0 } }, // digamma
    { 11, 1, 12462, {  0x227c,     0x0 } }, // preccurlyeq
    {  5, 1, 12473, {  0x219d,     0x0 } }, // rarrw
    {  7, 0, 12478, {  0x29a7,     0x0 } }, // uwangle
    {  4, 1, 12485, {  0x21d4,     0x0 } }, // hArr
    {  7, 0, 12489, {  0x2198,     0x0 } }, // searrow
    {  6, 0, 12496, {    0xd8,     0x0 } }, // Oslash
    {  7, 0, 12502, {  0x29a6,     0x0 } }, // dwangle
    {  5, 1, 12509, {    0xed,     0x0 } }, // iacut
    {  5, 0, 12514, {  0x2199,     0x0 } }, // swarr
    {  7, 1, 12519, {  0x2060,     0x0 } }, // NoBreak
    {  4, 0, 12526, {  0x2aa7,     0x0 } }, // gtcc
    {  5, 0, 12530, {   0x101,     0x0 } }, // amacr
    { 11, 0, 12535, {   0x3d5,     0x0 } }, // straightphi
    { 12, 0, 12546, {  0x2147,     0x0 } }, // ExponentialE
    {  4, 0, 12558, {  0x2133,     0x0 } }, // Mscr
    {  5, 1, 12562, {  0x22a3,     0x0 } }, // dashv
    {  5, 0, 12567, {  0x21d7,     0x0 } }, // neArr
    { 17, 1, 12572, {  0x22b4,     0x0 } }, // LeftTriangleEqual
    {  5, 1, 12589, {    0x3a,     0x0 } }, // colon
    {  8, 0, 12594, {  0x231f,     0x0 } }, // lrcorner
    { 17, 0, 12602, {  0x21cc,     0x0 } }, // rightleftharpoons
    {  5, 0, 12619, {  0x2ae4,     0x0 } }, // Dashv
    {  4, 0, 12624, { 0x1d564,     0x0 } }, // sopf
    { 15, 0, 12628, {  0x224e,   0x338 } }, // NotHumpDownHump
    {  8, 0, 12643, {  0x2305,     0x0 } }, // barwedge
    {  6, 1, 12651, {    0xc3,     0x0 } }, // Atilde
    {  5, 0, 12657, {   0x176,     0x0 } }, // Ycirc
    {  5, 0, 12662, {  0x2666,     0x0 } }, // diams
    {  2, 0, 12667, {    0xae,     0x0 } }, // RE
    {  4, 0, 12669, { 0x1d552,     0x0 } }, // aopf
    { 17, 1, 12673, {  0x226b,   0x338 } }, // NotGreaterGreater
    {  7, 0, 12690, {  0x2605,     0x0 } }, // bigstar
    {  5, 0, 12697, {  0x2aba,     0x0 } }, // scnap
    {  3, 0, 12702, {   0x3c4,     0x0 } }, // tau
    {  4, 0, 12705, {    0xcf,     0x0 } }, // Iuml
    {  5, 1, 12709, {    0xcc,     0x0 } }, // Igrav
    {  6, 1, 12714, {  0x22aa,     0x0 } }, // Vvdash
    {  6, 0, 12720, {  0x2a93,     0x0 } }, // lesges
    {  3, 1, 12726, {  0x2211,     0x0 } }, // Sum
    {  3, 1, 12729, {  0x223e,   0x333 } }, // acE
    {  2, 1, 12732, {  0x2208,     0x0 } }, // in
    {  4, 0, 12734, {  0x2265,  0x20d2 } }, // nvge
    {  5, 1, 12738, {  0x2568,     0x0 } }, // boxhU
    {  3, 0, 12743, {  0x21a6,     0x0 } }, // map
    {  4, 0, 12746, {  0x22c2,     0x0 } }, // xcap
    {  4, 1, 12750, { 0x1d569,     0x0 } }, // xopf
    {  4, 0, 12754, { 0x1d56a,     0x0 } }, // yopf
    { 11, 0, 12758, {  0x22de,     0x0 } }, // curlyeqprec
    {  4, 0, 12769, {  0x219f,     0x0 } }, // Uarr
    {  3, 0, 12773, {  0x2111,     0x0 } }, // Ifr
    { 12, 1, 12776, {  0x2270,     0x0 } }, // NotLessEqual
    {  9, 0, 12788, {  0x2234,     0x0 } }, // therefore
    {  5, 0, 12797, {    0xd9,     0x0 } }, // Ugrav
    { 13, 0, 12802, {  0x2240,     0x0 } }, // VerticalTilde
    {  5, 1, 12815, {   0x1b5,     0x0 } }, // imped
    {  6, 0, 12820, {    0xfa,     0x0 } }, // uacute
    {  6, 0, 12826, {    0xd5,     0x0 } }, // Otilde
    {  6, 1, 12832, {  0x2904,     0x0 } }, // nvHarr
    {  6, 0, 12838, {  0x230f,     0x0 } }, // ulcrop
    {  5, 1, 12844, {    0xa6,     0x0 } }, // brvba
    {  5, 0, 12849, {  0x2aae,     0x0 } }, // bumpE
    {  6, 1, 12854, {  0x22d0,     0x0 } }, // Subset
    {  3, 1, 12860, {   0x417,     0x0 } }, // Zcy
    {  3, 0, 12863, {   0x444,     0x0 } }, // fcy
    {  3, 0, 12866, { 0x1d52a,     0x0 } }, // mfr
    {  9, 1, 12869, {  0x2210,     0x0 } }, // Coproduct
    { 12, 0, 12878, {  0x25c3,     0x0 } }, // triangleleft
    {  5, 1, 12890, {  0x253c,     0x0 } }, // boxvh
    {  5, 0, 12895, {  0x2ad1,     0x0 } }, // csube
    {  6, 0, 12900, {  0x2210,     0x0 } }, // coprod
    { 14, 1, 12906, {  0x2062,     0x0 } }, // InvisibleTimes
    {  8, 1, 12920, {  0x29dd,     0x0 } }, // infintie
    {  3, 0, 12928, {  0x25ca,     0x0 } }, // loz
    {  6, 0, 12931, {   0x106,     0x0 } }, // Cacute
    { 18, 1, 12937, {  0x27f7,     0x0 } }, // LongLeftRightArrow
    { 18, 1, 12955, {  0x27fa,     0x0 } }, // Longleftrightarrow
    {  6, 0, 12973, {  0xfb04,     0x0 } }, // ffllig
    { 13, 1, 12979, {  0x22c7,     0x0 } }, // divideontimes
    {  6, 0, 12992, {  0x2133,     0x0 } }, // phmmat
    {  5, 1, 12998, {  0x2044,     0x0 } }, // frasl
    { 11, 1, 13003, {  0x219b,     0x0 } }, // nrightarrow
    {  5, 0, 13014, {  0x2196,     0x0 } }, // nwarr
    {  9, 1, 13019, {  0x2193,     0x0 } }, // DownArrow
    {  4, 0, 13028, {  0x2adb,     0x0 } }, // mlcp
    {  7, 0, 13032, {   0x395,     0x0 } }, // Epsilon
    {  6, 0, 13039, {   0x128,     0x0 } }, // Itilde
    {  5, 1, 13045, {   0x2d8,     0x0 } }, // Breve
    {  3, 0, 13050, {  0x2228,     0x0 } }, // vee
    {  6, 1, 13053, {   0x126,     0x0 } }, // Hstrok
    {  6, 0, 13059, {  0x2a80,     0x0 } }, // gesdot
    {  6, 0, 13065, {   0x13a,     0x0 } }, // lacute
    {  7, 0, 13071, {  0x29de,     0x0 } }, // nvinfin
    {  5, 0, 13078, {  0x219a,     0x0 } }, // nlarr
    {  6, 0, 13083, {  0x25aa,     0x0 } }, // squarf
    {  3, 0, 13089, {   0x3a6,     0x0 } }, // Phi
    {  3, 1, 13092, {  0x2a95,     0x0 } }, // els
    {  3, 0, 13095, {  0x226b,  0x20d2 } }, // nGt
    {  4, 1, 13098, { 0x1d4c8,     0x0 } }, // sscr
    {  6, 0, 13102, {  0x292a,     0x0 } }, // swnwar
    {  8, 1, 13108, {  0x220b,     0x0 } }, // SuchThat
    {  8, 0, 13116, {  0x2a17,     0x0 } }, // intlarhk
    {  3, 0, 13124, {  0x2207,     0x0 } }, // Del
    {  4, 1, 13127, {  0x21a0,     0x0 } }, // Rarr
    {  5, 0, 13131, {    0xf4,     0x0 } }, // ocirc
    {  3, 1, 13136, {  0x2a70,     0x0 } }, // apE
    {  4, 0, 13139, {  0x210a,     0x0 } }, // gscr
    {  4, 1, 13143, {  0x2256,     0x0 } }, // ecir
    {  4, 1, 13147, {    0xea,     0x0 } }, // ecir
    {  5, 0, 13151, {  0x225a,     0x0 } }, // veeeq
    {  5, 0, 13156, {    0xdf,     0x0 } }, // szlig
    {  4, 0, 13161, {  0x2279,     0x0 } }, // ntgl
    {  9, 1, 13165, {  0x2a02,     0x0 } }, // bigotimes
    {  5, 1, 13174, {  0x22f2,     0x0 } }, // disin
    {  4, 0, 13179, {  0x2226,     0x0 } }, // npar
    {  5, 0, 13183, {  0x296f,     0x0 } }, // duhar
    { 14, 1, 13188, {  0x21bd,     0x0 } }, // DownLeftVector
    {  4, 0, 13202, {  0x2736,     0x0 } }, // sext
    {  5, 0, 13206, {  0x22f4,     0x0 } }, // isins
    {  4, 1, 13211, { 0x1d4c5,     0x0 } }, // pscr
    {  5, 0, 13215, {  0x25ef,     0x0 } }, // xcirc
    { 13, 0, 13220, {  0x21a6,     0x0 } }, // RightTeeArrow
    {  5, 0, 13233, {  0x22ce,     0x0 } }, // cuvee
    {  6, 1, 13238, {  0x201a,     0x0 } }, // lsquor
    {  5, 0, 13244, {  0x2580,     0x0 } }, // uhblk
    {  4, 0, 13249, {  0x2aeb,     0x0 } }, // Vbar
    {  5, 1, 13253, {    0xc6,     0x0 } }, // AElig
    {  4, 0, 13258, { 0x1d4aa,     0x0 } }, // Oscr
    {  5, 0, 13262, {  0x223a,     0x0 } }, // mDDot
    {  3, 0, 13267, {  0x2223,     0x0 } }, // mid
    { 13, 0, 13270, {  0x2287,     0x0 } }, // SupersetEqual
    {  3, 1, 13283, {   0x41a,     0x0 } }, // Kcy
    {  6, 0, 13286, {  0x228b,  0xfe00 } }, // vsupne
    { 15, 1, 13292, {  0x21c2,     0x0 } }, // RightDownVector
    {  7, 1, 13307, {  0x291f,     0x0 } }, // larrbfs
    {  6, 0, 13314, {  0x2291,     0x0 } }, // sqsube
    {  5, 0, 13320, {  0x21fe,     0x0 } }, // roarr
    {  5, 1, 13325, {   0x133,     0x0 } }, // ijlig
    {  5, 0, 13330, {  0x296e,     0x0 } }, // udhar
    {  6, 1, 13335, {  0x2235,     0x0 } }, // becaus
    {  5, 1, 13341, {  0x252c,     0x0 } }, // boxhd
    {  4, 0, 13346, {  0x229b,     0x0 } }, // oast
    {  6, 0, 13350, {  0x2205,     0x0 } }, // emptyv
    {  5, 1, 13356, {  0x2224,     0x0 } }, // nsmid
    {  4, 0, 13361, {    0x7d,     0x0 } }, // rcub
    {  6, 0, 13365, {   0x15f,     0x0 } }, // scedil
    { 20, 1, 13371, {  0x201c,     0x0 } }, // OpenCurlyDoubleQuote
    {  9, 1, 13391, {  0x228e,     0x0 } }, // UnionPlus
    {  6, 0, 13400, {   0x17e,     0x0 } }, // zcaron
    {  5, 0, 13406, {  0x224b,   0x338 } }, // napid
    {  4, 0, 13411, {  0x2642,     0x0 } }, // male
    {  7, 0, 13415, {  0x2ac2,     0x0 } }, // supmult
    {  3, 1, 13422, {  0x2a7d,     0x0 } }, // les
    {  8, 0, 13425, {  0x294a,     0x0 } }, // lurdshar
    {  7, 0, 13433, {    0xb8,     0x0 } }, // Cedilla
    {  2, 0, 13440, {  0x22d8,     0x0 } }, // Ll
    {  4, 0, 13442, {  0x21d0,     0x0 } }, // lArr
    {  4, 0, 13446, {  0x2003,     0x0 } }, // emsp
    {  3, 1, 13450, {    0xd0,     0x0 } }, // ETH
    {  5, 0, 13453, {  0x25f8,     0x0 } }, // ultri
    {  7, 1, 13458, {  0x2272,     0x0 } }, // lesssim
    {  9, 1, 13465, {  0x2268,  0xfe00 } }, // lvertneqq
    {  4, 0, 13474, { 0x1d4c9,     0x0 } }, // tscr
    {  2, 1, 13478, {  0x2213,     0x0 } }, // mp
    {  6, 0, 13480, {   0x163,     0x0 } }, // tcedil
    { 10, 1, 13486, {  0x2243,     0x0 } }, // TildeEqual
    {  6, 0, 13496, {  0x22cc,     0x0 } }, // rthree
    {  6, 0, 13502, {  0x210f,     0x0 } }, // plankv
    {  4, 0, 13508, {  0x2963,     0x0 } }, // uHar
    {  5, 0, 13512, {  0x22d6,     0x0 } }, // ltdot
    {  6, 1, 13517, {    0xbd,     0x0 } }, // frac12
    {  5, 1, 13523, {  0x2018,     0x0 } }, // lsquo
    {  4, 1, 13528, { 0x1d55f,     0x0 } }, // nopf
    {  4, 0, 13532, {  0x29b7,     0x0 } }, // opar
    {  4, 1, 13536, { 0x1d557,     0x0 } }, // fopf
    {  5, 0, 13540, {   0x454,     0x0 } }, // jukcy
    {  5, 0, 13545, {  0x21bd,     0x0 } }, // lhard
    {  6, 0, 13550, {    0xdd,     0x0 } }, // Yacute
    { 20, 0, 13556, {  0x2145,     0x0 } }, // CapitalDifferentialD
    {  5, 0, 13576, {  0x2acc,     0x0 } }, // supnE
    {  8, 0, 13581, {  0x2a12,     0x0 } }, // rppolint
    {  5, 0, 13589, {    0xe1,     0x0 } }, // aacut
    {  4, 0, 13594, {  0x2112,     0x0 } }, // Lscr
    {  6, 0, 13598, {  0x2118,     0x0 } }, // weierp
    {  4, 0, 13604, {    0xba,     0x0 } }, // ordm
    {  4, 0, 13608, { 0x1d54c,     0x0 } }, // Uopf
    {  6, 0, 13612, {   0x139,     0x0 } }, // Lacute
    {  4, 0, 13618, {    0xdf,     0x0 } }, // szli
    {  8, 1, 13622, {  0x222b,     0x0 } }, // Integral
    {  6, 0, 13630, {    0xa4,     0x0 } }, // curren
    {  5, 0, 13636, {  0x27e6,     0x0 } }, // lobrk
    {  3, 0, 13641, { 0x1d51c,     0x0 } }, // Yfr
    {  6, 0, 13644, {  0x232d,     0x0 } }, // cylcty
    { 15, 1, 13650, {  0x2958,     0x0 } }, // LeftUpVectorBar
    {  3, 0, 13665, {    0xe4,     0x0 } }, // aum
    {  3, 1, 13668, {   0x410,     0x0 } }, // Acy
    {  5, 0, 13671, {  0x221f,     0x0 } }, // angrt
    {  5, 0, 13676, {  0x298c,     0x0 } }, // rbrke
    { 17, 1, 13681, {  0x2a7d,   0x338 } }, // NotLessSlantEqual
    {  6, 1, 13698, {  0x2112,     0x0 } }, // lagran
    { 10, 0, 13704, {  0x21a4,     0x0 } }, // mapstoleft
    {  3, 0, 13714, {    0xef,     0x0 } }, // ium
    {  2, 1, 13717, {    0x26,     0x0 } }, // am
    {  7, 0, 13719, {  0x299a,     0x0 } }, // vzigzag
    {  7, 0, 13726, {  0x25ef,     0x0 } }, // bigcirc
    {  7, 1, 13733, {  0x21d1,     0x0 } }, // Uparrow
    { 15, 0, 13740, {  0x22b5,     0x0 } }, // trianglerighteq
    {  4, 0, 13755, {  0x20db,     0x0 } }, // tdot
    {  4, 0, 13759, {  0x211d,     0x0 } }, // Ropf
    {  3, 1, 13763, { 0x1d521,     0x0 } }, // dfr
    {  5, 0, 13766, {  0x2226,     0x0 } }, // nspar
    {  4, 1, 13771, {  0x2267,     0x0 } }, // geqq
    {  4, 0, 13775, {  0x2285,     0x0 } }, // nsup
    {  6, 1, 13779, {   0x166,     0x0 } }, // Tstrok
    {  4, 1, 13785, {    0x3b,     0x0 } }, // semi
    {  7, 0, 13789, {   0x3c5,     0x0 } }, // upsilon
    {  4, 0, 13796, {    0xa9,     0x0 } }, // COPY
    {  5, 0, 13800, {  0x2563,     0x0 } }, // boxVL
    {  6, 0, 13805, {  0x29bc,     0x0 } }, // odsold
    { 18, 1, 13811, {  0x227c,     0x0 } }, // PrecedesSlantEqual
    {  8, 1, 13829, {  0x2a10,     0x0 } }, // cirfnint
    {  5, 1, 13837, {   0x237,     0x0 } }, // jmath
    {  5, 0, 13842, {    0xfe,     0x0 } }, // thorn
    {  6, 1, 13847, {  0x21a9,     0x0 } }, // larrhk
    {  4, 0, 13853, { 0x1d55e,     0x0 } }, // mopf
    {  4, 0, 13857, { 0x1d53e,     0x0 } }, // Gopf
    {  3, 1, 13861, {   0x433,     0x0 } }, // gcy
    {  5, 0, 13864, {    0xa1,     0x0 } }, // iexcl
    {  7, 0, 13869, {  0x29b0,     0x0 } }, // bemptyv
    { 13, 0, 13876, {  0x27f5,     0x0 } }, // longleftarrow
    {  6, 0, 13889, {  0x203a,     0x0 } }, // rsaquo
    {  6, 0, 13895, {   0x17d,     0x0 } }, // Zcaron
    {  2, 1, 13901, {  0x2061,     0x0 } }, // af
    {  3, 0, 13903, {  0x2a85,     0x0 } }, // lap
    {  5, 0, 13906, {  0x21be,     0x0 } }, // uharr
    {  4, 1, 13911, {  0x210f,     0x0 } }, // hbar
    {  5, 1, 13915, {  0x2014,     0x0 } }, // mdash
    {  5, 1, 13920, {  0x2281,     0x0 } }, // nsucc
    {  5, 0, 13925, {  0x21c5,     0x0 } }, // udarr
    {  5, 0, 13930, {  0x2564,     0x0 } }, // boxHd
    { 10, 0, 13935, {  0x2131,     0x0 } }, // Fouriertrf
    {  9, 0, 13945, {  0x2190,     0x0 } }, // LeftArrow
    { 10, 1, 13954, {  0x205f,  0x200a } }, // ThickSpace
    {  6, 1, 13964, {  0x22c8,     0x0 } }, // bowtie
    {  3, 0, 13970, {  0x2a87,     0x0 } }, // lne
    { 10, 1, 13973, {  0x21a5,     0x0 } }, // UpTeeArrow
    {  5, 0, 13983, {    0xf2,     0x0 } }, // ograv
    { 14, 0, 13988, {  0x2194,     0x0 } }, // leftrightarrow
    {  8, 0, 14002, {  0x231c,     0x0 } }, // ulcorner
    {  2, 0, 14010, {   0x39e,     0x0 } }, // Xi
    {  8, 0, 14012, {  0x29ab,     0x0 } }, // angmsdad
    {  8, 0, 14020, {  0x2911,     0x0 } }, // DDotrahd
    {  2, 1, 14028, {  0x226a,     0x0 } }, // ll
    {  6, 1, 14030, {  0x229f,     0x0 } }, // minusb
    {  4, 0, 14036, {  0x22a5,     0x0 } }, // perp
    {  3, 0, 14040, {   0x3a9,     0x0 } }, // ohm
    {  5, 1, 14043, {   0x112,     0x0 } }, // Emacr
    {  5, 1, 14048, {   0x174,     0x0 } }, // Wcirc
    {  9, 0, 14053, {  0x225c,     0x0 } }, // triangleq
    { 10, 1, 14062, {  0x2a85,     0x0 } }, // lessapprox
    {  7, 0, 14072, {  0x2ad8,     0x0 } }, // supdsub
    {  3, 1, 14079, {    0x22,     0x0 } }, // QUO
    {  6, 0, 14082, {  0x22b9,     0x0 } }, // hercon
    {  5, 0, 14088, {  0x2288,     0x0 } }, // nsube
    {  6, 0, 14093, {  0x2af1,     0x0 } }, // topcir
    {  6, 1, 14099, {  0x2221,     0x0 } }, // angmsd
    {  5, 0, 14105, {  0x2a45,     0x0 } }, // cupor
    {  4, 1, 14110, {    0x5b,     0x0 } }, // lsqb
    {  6, 0, 14114, {  0x2a06,     0x0 } }, // xsqcup
    { 12, 0, 14120, {    0x7c,     0x0 } }, // VerticalLine
    { 21, 0, 14132, {  0x201d,     0x0 } }, // CloseCurlyDoubleQuote
    {  5, 1, 14153, {   0x394,     0x0 } }, // Delta
    {  4, 0, 14158, { 0x1d558,     0x0 } }, // gopf
    { 12, 1, 14162, {  0x2191,     0x0 } }, // ShortUpArrow
    {  6, 0, 14174, {    0xb1,     0x0 } }, // plusmn
    {  2, 0, 14180, {  0x220b,     0x0 } }, // ni
    {  3, 1, 14182, {  0x25a1,     0x0 } }, // squ
    {  6, 0, 14185, {  0x2034,     0x0 } }, // tprime
    {  4, 1, 14191, {   0x455,     0x0 } }, // dscy
    {  6, 0, 14195, {  0xfb03,     0x0 } }, // ffilig
    {  6, 0, 14201, {  0x2929,     0x0 } }, // seswar
    {  3, 0, 14207, {    0x26,     0x0 } }, // AMP
    {  8, 0, 14210, {   0x3c2,     0x0 } }, // varsigma
    {  5, 1, 14218, {  0x223c,     0x0 } }, // Tilde
    {  6, 0, 14223, {  0x2939,     0x0 } }, // larrpl
    { 15, 1, 14229, {  0x222e,     0x0 } }, // ContourIntegral
    {  5, 0, 14244, {  0x2289,     0x0 } }, // nsupe
    {  5, 0, 14249, {  0x2992,     0x0 } }, // rangd
    {  5, 1, 14254, {    0xc2,     0x0 } }, // Acirc
    {  5, 1, 14259, {  0x22a5,     0x0 } }, // UpTee
    {  2, 1, 14264, {  0x2248,     0x0 } }, // ap
    {  3, 0, 14266, {   0x3c1,     0x0 } }, // rho
    {  5, 1, 14269, {   0x2d8,     0x0 } }, // breve
    {  6, 0, 14274, {  0x221d,     0x0 } }, // propto
    {  7, 0, 14280, {  0x2235,     0x0 } }, // Because
    {  5, 0, 14287, {    0xe8,     0x0 } }, // egrav
    {  4, 1, 14292, {  0x27eb,     0x0 } }, // Rang
    {  5, 0, 14296, {  0x2524,     0x0 } }, // boxvl
    {  4, 1, 14301, {   0x405,     0x0 } }, // DScy
    {  4, 0, 14305, {  0x227b,     0x0 } }, // succ
    {  3, 1, 14309, {  0x2a53,     0x0 } }, // And
    {  6, 0, 14312, {   0x164,     0x0 } }, // Tcaron
    { 12, 0, 14318, {  0x2274,     0x0 } }, // NotLessTilde
    {  3, 0, 14330, {  0x222a,     0x0 } }, // cup
    {  5, 1, 14333, {   0x152,     0x0 } }, // OElig
    {  7, 1, 14338, {   0x3b5,     0x0 } }, // epsilon
    {  6, 0, 14345, {  0x2039,     0x0 } }, // lsaquo
    {  4, 1, 14351, {   0x401,     0x0 } }, // IOcy
    {  7, 0, 14355, {  0x227f,     0x0 } }, // succsim
    {  3, 1, 14362, { 0x1d525,     0x0 } }, // hfr
    { 11, 0, 14365, {  0x2aba,     0x0 } }, // succnapprox
    { 20, 0, 14376, {  0x22e2,     0x0 } }, // NotSquareSubsetEqual
    {  1, 0, 14396, {    0x3c,     0x0 } }, // L
    {  6, 0, 14397, {  0x2923,     0x0 } }, // nwarhk
    {  7, 0, 14403, {  0x2a50,     0x0 } }, // ccupssm
};

static const uint16_t entitiesHashtbl[] = {
    0,
    1,
    2,
    4,
    0, // unused
    5,
    6,
    7,
    8,
    10,
    0, // unused
    11,
    12,
    0, // unused
    14,
    15,
    0, // unused
    0, // unused
    16,
    17,
    18,
    19,
    21,
    22,
    23,
    0, // unused
    0, // unused
    24,
    0, // unused
    0, // unused
    0, // unused
    25,
    26,
    0, // unused
    27,
    28,
    30,
    31,
    34,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    36,
    37,
    41,
    44,
    45,
    47,
    48,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    52,
    0, // unused
    54,
    0, // unused
    55,
    0, // unused
    58,
    0, // unused
    0, // unused
    59,
    0, // unused
    62,
    63,
    64,
    65,
    66,
    0, // unused
    68,
    69,
    70,
    72,
    73,
    76,
    77,
    78,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    79,
    0, // unused
    0, // unused
    82,
    0, // unused
    84,
    85,
    86,
    0, // unused
    0, // unused
    0, // unused
    88,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    89,
    91,
    0, // unused
    0, // unused
    92,
    94,
    95,
    98,
    0, // unused
    102,
    104,
    106,
    0, // unused
    0, // unused
    0, // unused
    107,
    108,
    0, // unused
    0, // unused
    0, // unused
    109,
    111,
    0, // unused
    112,
    0, // unused
    113,
    114,
    115,
    116,
    0, // unused
    119,
    120,
    121,
    0, // unused
    0, // unused
    123,
    125,
    0, // unused
    0, // unused
    0, // unused
    126,
    0, // unused
    129,
    0, // unused
    0, // unused
    130,
    0, // unused
    132,
    0, // unused
    133,
    135,
    0, // unused
    0, // unused
    136,
    138,
    0, // unused
    140,
    142,
    145,
    146,
    0, // unused
    0, // unused
    147,
    148,
    0, // unused
    150,
    0, // unused
    0, // unused
    151,
    0, // unused
    152,
    153,
    0, // unused
    154,
    156,
    0, // unused
    0, // unused
    0, // unused
    157,
    159,
    0, // unused
    161,
    162,
    163,
    0, // unused
    165,
    167,
    0, // unused
    168,
    0, // unused
    0, // unused
    169,
    171,
    176,
    0, // unused
    179,
    180,
    0, // unused
    0, // unused
    182,
    183,
    185,
    188,
    192,
    193,
    195,
    196,
    199,
    0, // unused
    0, // unused
    201,
    0, // unused
    0, // unused
    203,
    204,
    0, // unused
    205,
    206,
    207,
    0, // unused
    209,
    211,
    212,
    214,
    215,
    0, // unused
    217,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    219,
    221,
    222,
    224,
    0, // unused
    0, // unused
    0, // unused
    225,
    226,
    228,
    231,
    0, // unused
    0, // unused
    232,
    233,
    235,
    236,
    239,
    0, // unused
    241,
    243,
    247,
    249,
    0, // unused
    250,
    252,
    0, // unused
    254,
    255,
    257,
    0, // unused
    0, // unused
    258,
    0, // unused
    259,
    260,
    261,
    262,
    263,
    0, // unused
    264,
    266,
    267,
    269,
    0, // unused
    0, // unused
    270,
    0, // unused
    0, // unused
    273,
    275,
    0, // unused
    276,
    277,
    278,
    280,
    281,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    282,
    286,
    287,
    289,
    290,
    0, // unused
    291,
    292,
    0, // unused
    293,
    295,
    296,
    0, // unused
    298,
    0, // unused
    0, // unused
    0, // unused
    300,
    0, // unused
    0, // unused
    303,
    305,
    307,
    0, // unused
    308,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    309,
    310,
    0, // unused
    0, // unused
    311,
    312,
    313,
    0, // unused
    0, // unused
    315,
    316,
    317,
    0, // unused
    319,
    320,
    321,
    324,
    0, // unused
    0, // unused
    325,
    0, // unused
    0, // unused
    327,
    0, // unused
    331,
    0, // unused
    335,
    337,
    338,
    0, // unused
    339,
    340,
    341,
    0, // unused
    344,
    346,
    0, // unused
    348,
    350,
    0, // unused
    352,
    353,
    0, // unused
    354,
    356,
    358,
    359,
    360,
    0, // unused
    361,
    362,
    0, // unused
    364,
    0, // unused
    367,
    369,
    0, // unused
    370,
    372,
    373,
    374,
    0, // unused
    0, // unused
    375,
    0, // unused
    376,
    0, // unused
    0, // unused
    378,
    379,
    380,
    381,
    384,
    385,
    0, // unused
    390,
    391,
    392,
    393,
    395,
    397,
    398,
    400,
    0, // unused
    401,
    403,
    0, // unused
    406,
    0, // unused
    407,
    0, // unused
    408,
    410,
    0, // unused
    0, // unused
    411,
    412,
    0, // unused
    415,
    0, // unused
    416,
    421,
    422,
    423,
    424,
    426,
    428,
    0, // unused
    0, // unused
    0, // unused
    430,
    0, // unused
    0, // unused
    432,
    433,
    0, // unused
    0, // unused
    0, // unused
    434,
    435,
    436,
    0, // unused
    437,
    440,
    442,
    0, // unused
    0, // unused
    0, // unused
    443,
    444,
    0, // unused
    445,
    447,
    448,
    449,
    450,
    0, // unused
    452,
    453,
    454,
    455,
    456,
    457,
    459,
    0, // unused
    0, // unused
    0, // unused
    461,
    463,
    465,
    468,
    0, // unused
    469,
    470,
    472,
    473,
    475,
    0, // unused
    0, // unused
    476,
    0, // unused
    478,
    479,
    480,
    481,
    483,
    0, // unused
    484,
    485,
    0, // unused
    0, // unused
    487,
    0, // unused
    0, // unused
    489,
    492,
    0, // unused
    493,
    0, // unused
    494,
    496,
    500,
    0, // unused
    504,
    505,
    506,
    507,
    508,
    509,
    0, // unused
    510,
    0, // unused
    0, // unused
    511,
    513,
    0, // unused
    516,
    518,
    0, // unused
    0, // unused
    0, // unused
    520,
    0, // unused
    521,
    522,
    0, // unused
    0, // unused
    523,
    526,
    528,
    530,
    531,
    534,
    535,
    0, // unused
    536,
    537,
    0, // unused
    538,
    541,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    543,
    0, // unused
    545,
    0, // unused
    546,
    547,
    0, // unused
    548,
    549,
    550,
    0, // unused
    551,
    0, // unused
    0, // unused
    0, // unused
    552,
    0, // unused
    553,
    554,
    0, // unused
    560,
    561,
    0, // unused
    562,
    565,
    0, // unused
    566,
    568,
    570,
    571,
    0, // unused
    0, // unused
    572,
    0, // unused
    0, // unused
    574,
    575,
    0, // unused
    0, // unused
    578,
    579,
    580,
    0, // unused
    581,
    582,
    583,
    0, // unused
    0, // unused
    0, // unused
    584,
    586,
    0, // unused
    0, // unused
    588,
    589,
    0, // unused
    591,
    594,
    595,
    597,
    0, // unused
    0, // unused
    598,
    599,
    600,
    605,
    0, // unused
    0, // unused
    606,
    607,
    609,
    610,
    611,
    612,
    0, // unused
    0, // unused
    613,
    0, // unused
    615,
    620,
    621,
    622,
    623,
    624,
    625,
    0, // unused
    626,
    627,
    628,
    629,
    630,
    631,
    0, // unused
    633,
    0, // unused
    634,
    636,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    637,
    638,
    0, // unused
    0, // unused
    0, // unused
    639,
    0, // unused
    0, // unused
    642,
    0, // unused
    643,
    0, // unused
    644,
    645,
    646,
    647,
    0, // unused
    648,
    653,
    654,
    0, // unused
    655,
    656,
    0, // unused
    657,
    658,
    0, // unused
    659,
    660,
    661,
    662,
    0, // unused
    0, // unused
    664,
    665,
    667,
    668,
    669,
    670,
    0, // unused
    672,
    0, // unused
    673,
    675,
    0, // unused
    0, // unused
    676,
    0, // unused
    679,
    681,
    0, // unused
    683,
    0, // unused
    0, // unused
    0, // unused
    685,
    686,
    0, // unused
    688,
    0, // unused
    689,
    0, // unused
    0, // unused
    690,
    692,
    694,
    0, // unused
    695,
    0, // unused
    0, // unused
    696,
    697,
    699,
    700,
    0, // unused
    701,
    703,
    704,
    706,
    708,
    710,
    713,
    0, // unused
    716,
    718,
    721,
    722,
    723,
    0, // unused
    724,
    0, // unused
    725,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    726,
    727,
    0, // unused
    0, // unused
    728,
    729,
    730,
    731,
    0, // unused
    732,
    733,
    0, // unused
    735,
    738,
    0, // unused
    741,
    744,
    745,
    746,
    748,
    749,
    750,
    0, // unused
    751,
    752,
    753,
    755,
    756,
    758,
    761,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    762,
    0, // unused
    0, // unused
    766,
    768,
    0, // unused
    769,
    770,
    0, // unused
    0, // unused
    771,
    774,
    776,
    778,
    779,
    782,
    0, // unused
    786,
    787,
    789,
    790,
    0, // unused
    794,
    796,
    0, // unused
    801,
    803,
    0, // unused
    804,
    0, // unused
    805,
    808,
    0, // unused
    810,
    811,
    0, // unused
    812,
    813,
    0, // unused
    815,
    0, // unused
    817,
    0, // unused
    820,
    822,
    824,
    0, // unused
    825,
    826,
    0, // unused
    0, // unused
    828,
    829,
    830,
    831,
    834,
    835,
    836,
    837,
    0, // unused
    838,
    0, // unused
    840,
    841,
    0, // unused
    0, // unused
    843,
    844,
    846,
    847,
    0, // unused
    848,
    0, // unused
    850,
    851,
    856,
    858,
    0, // unused
    859,
    0, // unused
    860,
    862,
    865,
    866,
    0, // unused
    0, // unused
    0, // unused
    867,
    868,
    0, // unused
    869,
    871,
    872,
    873,
    0, // unused
    874,
    0, // unused
    0, // unused
    0, // unused
    875,
    879,
    0, // unused
    881,
    883,
    884,
    0, // unused
    886,
    887,
    888,
    0, // unused
    890,
    891,
    894,
    897,
    899,
    900,
    901,
    902,
    0, // unused
    903,
    905,
    907,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    908,
    909,
    910,
    0, // unused
    911,
    0, // unused
    0, // unused
    912,
    0, // unused
    915,
    916,
    0, // unused
    0, // unused
    917,
    919,
    921,
    0, // unused
    0, // unused
    923,
    925,
    0, // unused
    0, // unused
    0, // unused
    926,
    927,
    929,
    0, // unused
    931,
    933,
    0, // unused
    935,
    937,
    938,
    939,
    0, // unused
    940,
    942,
    0, // unused
    944,
    0, // unused
    945,
    946,
    0, // unused
    948,
    950,
    953,
    955,
    956,
    0, // unused
    957,
    959,
    0, // unused
    0, // unused
    960,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    962,
    963,
    964,
    969,
    0, // unused
    0, // unused
    971,
    0, // unused
    973,
    0, // unused
    974,
    975,
    976,
    979,
    980,
    0, // unused
    0, // unused
    0, // unused
    981,
    982,
    983,
    0, // unused
    985,
    0, // unused
    986,
    987,
    0, // unused
    989,
    0, // unused
    0, // unused
    0, // unused
    992,
    994,
    996,
    997,
    0, // unused
    999,
    1000,
    1001,
    1003,
    0, // unused
    1004,
    1006,
    0, // unused
    1008,
    1009,
    1011,
    0, // unused
    0, // unused
    1013,
    1014,
    0, // unused
    1015,
    1017,
    1019,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1020,
    0, // unused
    1022,
    1024,
    1026,
    1028,
    1029,
    1031,
    1033,
    0, // unused
    1034,
    0, // unused
    1035,
    1037,
    1038,
    1039,
    1040,
    0, // unused
    1041,
    1044,
    1045,
    0, // unused
    1046,
    1048,
    1049,
    1051,
    1052,
    1053,
    1054,
    0, // unused
    0, // unused
    0, // unused
    1057,
    1059,
    1062,
    1063,
    0, // unused
    0, // unused
    1064,
    0, // unused
    1065,
    1066,
    1068,
    1069,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1072,
    1073,
    1074,
    0, // unused
    0, // unused
    1075,
    0, // unused
    1076,
    0, // unused
    0, // unused
    0, // unused
    1078,
    1080,
    0, // unused
    0, // unused
    1081,
    1082,
    1083,
    1084,
    1085,
    0, // unused
    1087,
    1088,
    1089,
    1091,
    0, // unused
    0, // unused
    1092,
    0, // unused
    1095,
    1099,
    0, // unused
    1101,
    1103,
    0, // unused
    1104,
    1107,
    1108,
    1109,
    0, // unused
    1110,
    1111,
    1112,
    1113,
    1114,
    1116,
    1119,
    1122,
    1123,
    1124,
    1126,
    1127,
    1128,
    1129,
    0, // unused
    0, // unused
    1132,
    1133,
    0, // unused
    0, // unused
    0, // unused
    1134,
    1135,
    1137,
    0, // unused
    1138,
    1140,
    1142,
    1144,
    1145,
    0, // unused
    0, // unused
    1146,
    0, // unused
    1147,
    0, // unused
    1148,
    1149,
    1152,
    1153,
    0, // unused
    1154,
    0, // unused
    1155,
    0, // unused
    1158,
    1159,
    0, // unused
    1160,
    1161,
    0, // unused
    0, // unused
    1162,
    0, // unused
    1163,
    0, // unused
    1164,
    0, // unused
    0, // unused
    1166,
    1167,
    0, // unused
    1168,
    1170,
    1171,
    1174,
    1175,
    1176,
    0, // unused
    1177,
    1178,
    1181,
    0, // unused
    1183,
    0, // unused
    0, // unused
    0, // unused
    1185,
    1186,
    0, // unused
    1187,
    0, // unused
    1188,
    1189,
    0, // unused
    0, // unused
    1190,
    1193,
    1195,
    0, // unused
    1197,
    1198,
    1199,
    1200,
    1204,
    1205,
    1206,
    1207,
    0, // unused
    1208,
    1209,
    0, // unused
    1210,
    0, // unused
    1211,
    1213,
    0, // unused
    1214,
    1215,
    1216,
    1218,
    0, // unused
    0, // unused
    1220,
    1221,
    1222,
    1225,
    1226,
    1227,
    0, // unused
    1228,
    0, // unused
    1229,
    1230,
    0, // unused
    1233,
    0, // unused
    0, // unused
    1234,
    1236,
    1238,
    1239,
    1240,
    1241,
    0, // unused
    0, // unused
    1242,
    1243,
    1244,
    1245,
    1249,
    1250,
    1254,
    1256,
    0, // unused
    1257,
    0, // unused
    1259,
    1261,
    0, // unused
    1262,
    1263,
    1265,
    0, // unused
    0, // unused
    1267,
    1268,
    1270,
    1272,
    0, // unused
    1274,
    0, // unused
    0, // unused
    1275,
    1276,
    1278,
    0, // unused
    0, // unused
    1279,
    1282,
    1283,
    1284,
    1287,
    0, // unused
    0, // unused
    1293,
    1294,
    0, // unused
    1296,
    1298,
    1300,
    0, // unused
    1301,
    0, // unused
    0, // unused
    1302,
    1304,
    1305,
    1307,
    1308,
    1309,
    1310,
    1311,
    1312,
    0, // unused
    1314,
    0, // unused
    0, // unused
    1315,
    1318,
    1320,
    0, // unused
    1321,
    0, // unused
    1323,
    1325,
    1327,
    1328,
    1329,
    0, // unused
    0, // unused
    1330,
    0, // unused
    0, // unused
    0, // unused
    1331,
    0, // unused
    0, // unused
    1332,
    1334,
    1335,
    1336,
    0, // unused
    0, // unused
    1339,
    1340,
    0, // unused
    1341,
    0, // unused
    1342,
    0, // unused
    0, // unused
    1343,
    0, // unused
    1344,
    1345,
    1346,
    0, // unused
    1347,
    0, // unused
    0, // unused
    1348,
    1351,
    1354,
    1355,
    1356,
    1357,
    1358,
    0, // unused
    0, // unused
    1359,
    1360,
    1361,
    1363,
    0, // unused
    0, // unused
    1366,
    1368,
    0, // unused
    1369,
    0, // unused
    0, // unused
    1370,
    1371,
    1372,
    1374,
    0, // unused
    1375,
    1377,
    0, // unused
    1379,
    0, // unused
    1381,
    0, // unused
    1382,
    0, // unused
    0, // unused
    1384,
    1385,
    1388,
    1393,
    1394,
    1396,
    0, // unused
    0, // unused
    1398,
    0, // unused
    1399,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1400,
    1401,
    1402,
    0, // unused
    1403,
    1404,
    1406,
    1407,
    1408,
    1410,
    1411,
    1412,
    1413,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1415,
    1416,
    1419,
    1422,
    0, // unused
    1424,
    0, // unused
    1426,
    1428,
    0, // unused
    1429,
    0, // unused
    0, // unused
    1430,
    1431,
    1432,
    0, // unused
    1433,
    1434,
    1436,
    1439,
    1440,
    0, // unused
    1441,
    0, // unused
    0, // unused
    1443,
    1444,
    0, // unused
    0, // unused
    1446,
    1447,
    1449,
    1450,
    1453,
    1454,
    1456,
    1457,
    1460,
    0, // unused
    1463,
    1465,
    1466,
    1469,
    1471,
    1472,
    0, // unused
    1473,
    0, // unused
    1474,
    1475,
    1476,
    1477,
    1478,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1481,
    1482,
    0, // unused
    0, // unused
    1483,
    1486,
    1487,
    1488,
    1489,
    1491,
    1492,
    0, // unused
    1493,
    1494,
    1497,
    1499,
    1500,
    1501,
    1502,
    1503,
    0, // unused
    1505,
    0, // unused
    0, // unused
    1509,
    0, // unused
    1511,
    1513,
    0, // unused
    0, // unused
    1514,
    0, // unused
    1515,
    1517,
    1518,
    1520,
    0, // unused
    1521,
    1523,
    0, // unused
    1525,
    1526,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1529,
    1530,
    1531,
    1532,
    0, // unused
    1533,
    1534,
    1536,
    1538,
    1539,
    1540,
    1541,
    1545,
    1546,
    0, // unused
    1547,
    1549,
    0, // unused
    1550,
    0, // unused
    1552,
    1553,
    0, // unused
    1556,
    1560,
    0, // unused
    0, // unused
    1561,
    1563,
    0, // unused
    1565,
    1566,
    1567,
    0, // unused
    1571,
    0, // unused
    0, // unused
    1573,
    1574,
    0, // unused
    1576,
    0, // unused
    1577,
    1578,
    1579,
    0, // unused
    0, // unused
    1583,
    1585,
    1588,
    1590,
    0, // unused
    0, // unused
    1591,
    1592,
    1593,
    0, // unused
    1594,
    0, // unused
    0, // unused
    1595,
    0, // unused
    0, // unused
    1597,
    1599,
    1600,
    1602,
    0, // unused
    0, // unused
    1604,
    1606,
    1607,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1608,
    1610,
    1611,
    1612,
    1613,
    1617,
    0, // unused
    1618,
    1619,
    1620,
    1621,
    0, // unused
    0, // unused
    1622,
    0, // unused
    0, // unused
    1624,
    0, // unused
    1627,
    1628,
    1629,
    1633,
    1634,
    1636,
    1640,
    1641,
    0, // unused
    1643,
    1645,
    1646,
    0, // unused
    1647,
    1648,
    0, // unused
    1650,
    1652,
    1654,
    1655,
    1657,
    1658,
    0, // unused
    1659,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1662,
    1663,
    1664,
    1667,
    1670,
    1671,
    1672,
    1673,
    1674,
    1676,
    1678,
    1680,
    1681,
    1683,
    1685,
    1686,
    0, // unused
    0, // unused
    0, // unused
    1688,
    0, // unused
    1689,
    1690,
    0, // unused
    1691,
    1692,
    1694,
    1695,
    1696,
    1699,
    0, // unused
    1701,
    0, // unused
    1702,
    0, // unused
    0, // unused
    1703,
    1705,
    1706,
    1708,
    1711,
    1712,
    1714,
    1715,
    1716,
    1719,
    1720,
    1721,
    1723,
    0, // unused
    0, // unused
    1725,
    1726,
    1727,
    1729,
    0, // unused
    1732,
    1735,
    1736,
    1737,
    1738,
    1740,
    0, // unused
    0, // unused
    1742,
    1745,
    1746,
    0, // unused
    0, // unused
    0, // unused
    1747,
    1749,
    1752,
    1753,
    0, // unused
    1756,
    1757,
    0, // unused
    1758,
    0, // unused
    1760,
    0, // unused
    0, // unused
    0, // unused
    1761,
    1762,
    0, // unused
    1763,
    0, // unused
    1764,
    0, // unused
    1766,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1767,
    0, // unused
    0, // unused
    0, // unused
    1769,
    1771,
    1772,
    1774,
    0, // unused
    1775,
    0, // unused
    1777,
    1778,
    0, // unused
    1781,
    0, // unused
    1782,
    0, // unused
    1783,
    0, // unused
    1784,
    1788,
    1789,
    1791,
    0, // unused
    1792,
    0, // unused
    1794,
    1795,
    1797,
    1798,
    1799,
    0, // unused
    0, // unused
    0, // unused
    1801,
    1802,
    0, // unused
    1803,
    0, // unused
    0, // unused
    1806,
    0, // unused
    1807,
    1808,
    1809,
    0, // unused
    1810,
    1812,
    0, // unused
    1813,
    1814,
    1815,
    0, // unused
    1818,
    0, // unused
    1820,
    1821,
    1822,
    1823,
    0, // unused
    0, // unused
    0, // unused
    1826,
    0, // unused
    1827,
    1828,
    1829,
    1831,
    0, // unused
    0, // unused
    1833,
    0, // unused
    1836,
    0, // unused
    1837,
    1838,
    0, // unused
    0, // unused
    1839,
    1840,
    0, // unused
    1842,
    1843,
    1844,
    1845,
    1847,
    1848,
    0, // unused
    0, // unused
    1850,
    0, // unused
    0, // unused
    1851,
    1853,
    0, // unused
    1854,
    0, // unused
    1856,
    0, // unused
    1857,
    1858,
    1859,
    1860,
    0, // unused
    1861,
    1863,
    0, // unused
    0, // unused
    1864,
    1865,
    0, // unused
    1867,
    1868,
    0, // unused
    1869,
    1871,
    1872,
    1873,
    0, // unused
    1874,
    0, // unused
    0, // unused
    1875,
    0, // unused
    1876,
    1877,
    1881,
    0, // unused
    0, // unused
    1882,
    1883,
    0, // unused
    0, // unused
    1884,
    0, // unused
    1885,
    0, // unused
    0, // unused
    1886,
    1888,
    0, // unused
    1889,
    1890,
    0, // unused
    0, // unused
    1892,
    1895,
    1896,
    0, // unused
    1897,
    1898,
    0, // unused
    1901,
    1903,
    0, // unused
    0, // unused
    0, // unused
    1905,
    0, // unused
    1907,
    1911,
    1913,
    1914,
    1916,
    1920,
    1922,
    1923,
    0, // unused
    1924,
    1926,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1928,
    0, // unused
    0, // unused
    1929,
    1930,
    1931,
    1932,
    1934,
    1937,
    1938,
    1939,
    1940,
    0, // unused
    1941,
    0, // unused
    0, // unused
    1942,
    1944,
    0, // unused
    0, // unused
    1945,
    0, // unused
    0, // unused
    1946,
    0, // unused
    1947,
    0, // unused
    1949,
    0, // unused
    1950,
    1951,
    1952,
    0, // unused
    1955,
    1959,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    1961,
    1962,
    1964,
    0, // unused
    0, // unused
    1965,
    1966,
    1967,
    1969,
    1970,
    1971,
    1973,
    1974,
    1976,
    1978,
    0, // unused
    0, // unused
    1981,
    1982,
    0, // unused
    1984,
    0, // unused
    1986,
    0, // unused
    0, // unused
    0, // unused
    1987,
    1990,
    1991,
    1994,
    1996,
    1999,
    0, // unused
    2001,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    2002,
    0, // unused
    2003,
    2005,
    2007,
    2008,
    2009,
    2010,
    2011,
    2012,
    0, // unused
    2014,
    0, // unused
    2016,
    2018,
    2019,
    0, // unused
    2021,
    0, // unused
    0, // unused
    2023,
    2026,
    0, // unused
    2027,
    2028,
    0, // unused
    2031,
    2032,
    2034,
    2035,
    2037,
    2038,
    0, // unused
    2039,
    2041,
    2042,
    2044,
    2045,
    2046,
    2047,
    2049,
    0, // unused
    2052,
    0, // unused
    2053,
    0, // unused
    0, // unused
    2055,
    0, // unused
    2058,
    0, // unused
    0, // unused
    2059,
    2061,
    2062,
    2065,
    2066,
    0, // unused
    2067,
    0, // unused
    0, // unused
    2068,
    0, // unused
    0, // unused
    2070,
    2071,
    2072,
    0, // unused
    0, // unused
    0, // unused
    2073,
    2074,
    0, // unused
    0, // unused
    0, // unused
    2076,
    2079,
    2081,
    2083,
    2084,
    0, // unused
    0, // unused
    0, // unused
    2085,
    2086,
    2090,
    2092,
    0, // unused
    0, // unused
    2093,
    0, // unused
    2094,
    2095,
    2096,
    2097,
    2098,
    2099,
    0, // unused
    2100,
    2101,
    2102,
    2103,
    2104,
    0, // unused
    2106,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    2107,
    2108,
    0, // unused
    0, // unused
    0, // unused
    2109,
    0, // unused
    2111,
    2113,
    0, // unused
    2114,
    2117,
    2118,
    2120,
    0, // unused
    0, // unused
    2121,
    2123,
    2124,
    0, // unused
    2125,
    2127,
    2129,
    2132,
    2133,
    2134,
    2135,
    2139,
    0, // unused
    2141,
    2142,
    2144,
    2145,
    0, // unused
    0, // unused
    0, // unused
    2146,
    0, // unused
    0, // unused
    2147,
    0, // unused
    2148,
    0, // unused
    2150,
    2151,
    2155,
    2156,
    2157,
    2158,
    2161,
    0, // unused
    2163,
    0, // unused
    0, // unused
    0, // unused
    0, // unused
    2164,
    2165,
    2166,
    0, // unused
    0, // unused
    2167,
    0, // unused
    2168,
    2171,
    0, // unused
    2172,
    2175,
    0, // unused
    2177,
    2179,
    2180,
    0, // unused
    2181,
    2183,
    0, // unused
    2185,
    2186,
    0, // unused
    2187,
    0, // unused
    0, // unused
    2189,
    2191,
    0, // unused
    0, // unused
    0, // unused
    2192,
    2194,
    0, // unused
    0, // unused
    2196,
    2197,
    0, // unused
    2198,
    2199,
    2201,
    2203,
    0, // unused
    2204,
    2208,
    0, // unused
    0, // unused
    2210,
    2211,
    0, // unused
    2212,
    2214,
    2216,
    2218,
    0, // unused
    2219,
    2220,
    2223,
    0, // unused
    2225,
    2227,
    2228,
    2229,
    0, // unused
    2230,
};

static const uint16_t entitiesSize = 2231;
