#ifndef TUIWIDGETS_ZLAYOUT_P_INCLUDED
#define TUIWIDGETS_ZLAYOUT_P_INCLUDED

#include <Tui/ZLayout.h>

TUIWIDGETS_NS_START

class ZLayoutPrivate {
};

TUIWIDGETS_NS_END

#endif // TUIWIDGETS_ZLAYOUT_P_INCLUDED
